zitadel/zitadel

README.md

As imgshield is consistent slow i replace the badges with `badgen`

docs(badges): replace imgshield with badgen

---

.dependabot/config.yml

https://dependabot.com/docs/config-file/

chore(dependabot): config

---

.github/workflows/release.yml

chore: docker vars

---

.github/workflows/release.yml
.releaserc.js

This should fix the docker release step in semrel

chore(semantic-release): docker-release 

---

go.mod

fixes https://github.com/caos/zitadel/pull/80

chore: add correct upstream

---

.github/workflows/release.yml
.releaserc.js
build/docker/prod

- upload artifact to release page
- matrix build

chore: matrix build

---

build/docker/prod

Revert "disable login and console in docker"

---

k8s/base/deployment.yaml
k8s/base/flow.yaml
k8s/base/kustomization.yaml
k8s/base/output.yaml
k8s/base/service-accounts.yaml
k8s/base/service-api-admin.yaml
k8s/base/service-api-auth.yaml
k8s/base/service-api-mangagement.yaml
k8s/base/service-console.yaml

for seperate base and overlay config we move the base to software repo

chore: deployment manifest, kaniko

---

internal/admin/repository/eventsourcing/view/error_event.go
internal/auth/repository/eventsourcing/view/error_event.go
internal/authz/repository/eventsourcing/view/error_event.go
internal/management/repository/eventsourcing/view/error_event.go
internal/notification/repository/eventsourcing/view/error_event.go
migrations/cockroach/V1.24__failed_events.sql

please merge relating mergerequest in ops repo first
https://github.com/caos/zitadel-ops/pull/11

fix: rename tables failed_event to failed_events

---

pkg/console/console.go

fix(console): header overwrite

---

k8s/base/kustomization.yaml

chore(infra):added flow for logging

---

internal/ui/login/handler/login.go

fix: send csrf on root path

---

internal/api/authz/context.go
internal/api/authz/permissions_test.go
internal/api/authz/token.go
internal/api/grpc/server/middleware/auth_interceptor_test.go
internal/authz/repository/eventsourcing/eventstore/token_verifier.go
internal/authz/repository/eventsourcing/handler/handler.go
internal/authz/repository/eventsourcing/handler/org.go
internal/authz/repository/eventsourcing/view/org.go
internal/authz/repository/token_verifier.go
migrations/cockroach/V1.6__authz_orgs.sql

Merge after migrataions on dev/ ch done
https://github.com/caos/zitadel-ops/pull/23

feat: check if org exists

---

console/src/app/app.component.html
console/src/app/pages/iam/iam-members/iam-members.component.ts
console/src/app/pages/orgs/org-create/org-create.component.ts
console/src/app/pages/orgs/org-detail/org-detail.component.ts
console/src/app/pages/orgs/org-members/org-members.component.ts
console/src/app/pages/orgs/password-policy/password-policy.component.html
console/src/app/pages/projects/granted-projects/granted-project-list/granted-project-list.component.scss
console/src/app/pages/projects/owned-projects/owned-project-detail/applications/applications.component.ts
console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-list.component.scss
console/src/app/pages/users/user-detail/auth-user-detail/auth-user-mfa/auth-user-mfa.component.html
console/src/app/pages/users/user-detail/user-detail/user-mfa/user-mfa.component.html
console/src/app/services/auth.service.ts
console/src/app/services/grpc.service.ts

fix(console): rm mfa link, policy issues, consistency for table spacing

---

console/package-lock.json
console/src/app/pages/projects/apps/app-create/app-create.component.ts
console/src/app/pages/projects/apps/app-detail/app-detail.component.html
console/src/app/pages/projects/apps/app-detail/app-detail.component.ts

fix(console): allow authmethod none for web, remove secret from authmethod none

---

console/src/app/pages/orgs/org-detail/org-detail.component.ts
console/src/app/pages/orgs/org-members/org-members.component.html
console/src/app/pages/orgs/org-members/org-members.component.scss
console/src/app/pages/projects/granted-projects/granted-project-detail/granted-project-detail.component.ts
console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.ts
console/src/app/pages/users/user-detail/auth-user-detail/auth-user-mfa/auth-user-mfa.component.ts

fix(console): mfa refresh after verification, member eventemitter

---

console/src/app/app-routing.module.ts
console/src/app/app.component.html
console/src/app/pages/orgs/org-detail/org-detail.component.html
console/src/app/pages/orgs/org-detail/org-detail.component.scss
console/src/app/pages/orgs/org-detail/org-detail.component.ts
console/src/app/services/grpc-auth.service.ts
console/src/app/services/mgmt.service.ts
console/src/assets/i18n/de.json
console/src/assets/i18n/en.json

feat(console): set primary domain, fix org create permission

---

console/src/app/pages/users/user-detail/auth-user-detail/auth-user-mfa/auth-user-mfa.component.ts
console/src/app/pages/users/user-detail/user-detail.module.ts
console/src/assets/i18n/de.json
console/src/assets/i18n/en.json

fix(console): otp delete comfirmation

---

internal/eventstore/internal/repository/sql/push.go

It should not be a problem as long as we create all events via `EventCreator` but i'd like to fix it before we're in trouble ;)

fix(eventstore): check if creation date is not zero

---

console/src/app/pages/orgs/org-detail/domain-verification/domain-verification.component.html
console/src/app/pages/orgs/org-detail/domain-verification/domain-verification.component.scss
console/src/app/pages/orgs/org-detail/domain-verification/domain-verification.component.ts
console/src/app/pages/orgs/org-detail/org-detail.component.ts
console/src/assets/i18n/de.json

fix(console): start verification flow on domain create, show verification if token is requested

---

console/src/assets/i18n/de.json
console/src/assets/i18n/en.json

suggest to use us-en consistently and use "more correct" version of the German word.

chore(translation): suggest different translations

---

README.md

* Update readme
* Apply suggestions from code review but features
Co-authored-by: Florian Forster <florian@caos.ch>
* Update README.md
Co-authored-by: Florian Forster <florian@caos.ch>
Co-authored-by: Maximilian Panne <maximilian.panne@gmail.com>
Co-authored-by: Florian Forster <florian@caos.ch>
(cherry picked from commit 5c5b13cf84aca3641ec8fd43036c7ec25479d598)

docs: update readme (#1460)

---

console/src/app/app.module.ts
console/src/app/guards/auth.guard.ts
console/src/app/guards/role.guard.ts
console/src/app/modules/policy-grid/policy-grid.component.scss
console/src/app/pages/iam/iam.component.scss
console/src/app/pages/orgs/org-detail/org-detail.component.html
console/src/app/pages/orgs/org-detail/org-detail.component.scss
console/src/app/pages/orgs/org-detail/org-detail.component.ts
console/src/app/pages/user-grant-create/user-grant-create.component.ts
console/src/app/pages/users/user-detail/auth-user-detail/auth-user-mfa/auth-user-mfa.component.html
console/src/app/pages/users/user-detail/auth-user-detail/auth-user-mfa/auth-user-mfa.component.ts
console/src/app/pages/users/user-detail/user-detail/user-mfa/user-mfa.component.html
console/src/app/pages/users/user-detail/user-detail/user-mfa/user-mfa.component.ts
console/src/assets/i18n/de.json
console/src/assets/i18n/en.json

fix(console): bugs and some imperfections

---

SECURITY.md

refactor: Version 1

---

docs/docusaurus.config.js

Settings available here https://github.com/algolia/docsearch-configs/blob/master/configs/zitadel.json

docs(search): integrated algolia (thank you 🥳 )

---

docs/docs/quickstarts/go.md
docs/sidebars.js

waiting for https://github.com/caos/zitadel-go/pull/1 to be merged

docs: add quickstart for go

---

console/src/app/modules/project-members/project-members-datasource.ts
console/src/app/modules/user-grants/user-grants-datasource.ts
console/src/app/pages/iam/iam.component.ts
console/src/app/pages/orgs/org-detail/org-detail.component.ts
console/src/app/pages/projects/apps/app-secret-dialog/app-secret-dialog.component.html
console/src/app/pages/projects/apps/app-secret-dialog/app-secret-dialog.component.scss
console/src/app/pages/projects/granted-projects/granted-project-detail/granted-project-detail.component.ts
console/src/app/pages/projects/granted-projects/granted-project-list/granted-project-list.component.ts
console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.ts
console/src/app/pages/projects/owned-projects/owned-project-detail/project-grants/project-grants-datasource.ts
console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-list.component.ts
console/src/app/pages/users/user-create-machine/user-create-machine.component.html
console/src/app/pages/users/user-create/user-create.component.html
console/src/app/pages/users/user-detail/external-idps/external-idps.component.ts
console/src/app/pages/users/user-detail/memberships/memberships.component.ts
console/src/app/pages/users/user-detail/user-detail/user-detail.component.html
console/src/app/pages/users/user-list/user-table/user-table.component.ts
console/src/assets/i18n/de.json
console/src/assets/i18n/en.json

adds info for user if no secret is provided on app create
Closes #1640
Closes #1642
Closes #1638
Closes #1671

fix(console): ui issues

---

console/src/app/app.component.html

fix(console): show org only with regex org.read

---

console/src/app/modules/password-complexity-view/password-complexity-view.component.html

fix(console): correct value for password complexity description

---

docs/docs/quickstarts/flutter.md
docs/docusaurus.config.js
docs/yarn.lock

Signed-off-by: Christoph Bühler <cbuehler@rootd.ch>

docs: improve Flutter quick start

---

docs/package.json
docs/yarn.lock

This PR does update docusaurus to the latest release `beta 3`

docs: update to beta 3

---

docs/docs/concepts/eventstore.md
docs/sidebars.js

It might be a trivial comment, yet seems to me worth mentioning. When we have more patterns/concepts we can bundle those together as explainer within this section of the docs.

docs: eventstore

---

.github/workflows/zitadel.yml

fix: set version for sentry release

---

go.mod
go.sum

fix: update oidc lib to fix userinfo claims in id_token

---

docs/docs/legal/dedicated-instance-annex.md
docs/docs/legal/service-level-description.md
docs/docs/legal/support-services.md
docs/docs/legal/terms-of-service-dedicated.md
docs/docs/legal/terms-of-service.md
docs/sidebars.js

docs: additional terms for dedicated instance

---

.github/workflows/zitadel.yml
internal/notification/repository/eventsourcing/handler/notification.go

fix: custom mail texts

---

console/src/app/pages/users/user-detail/auth-user-detail/auth-passwordless/auth-passwordless.component.ts
console/src/app/pages/users/user-detail/auth-user-detail/auth-passwordless/dialog-passwordless/dialog-passwordless.component.html
console/src/app/pages/users/user-detail/auth-user-detail/auth-passwordless/dialog-passwordless/dialog-passwordless.component.scss
console/src/app/pages/users/user-detail/auth-user-detail/auth-passwordless/dialog-passwordless/dialog-passwordless.component.ts
console/src/app/pages/users/user-detail/auth-user-detail/auth-user-detail.component.html
console/src/app/pages/users/user-detail/user-detail.module.ts
console/src/app/pages/users/user-detail/user-detail/passwordless/passwordless.component.html
console/src/app/pages/users/user-detail/user-detail/passwordless/passwordless.component.scss
console/src/app/pages/users/user-detail/user-detail/passwordless/passwordless.component.ts
console/src/app/pages/users/user-detail/user-detail/user-detail.component.html
console/src/app/services/grpc-auth.service.ts
console/src/app/services/mgmt.service.ts
console/src/assets/i18n/de.json
console/src/assets/i18n/en.json
internal/auth/repository/eventsourcing/eventstore/auth_request.go

feat(console): advanced passwordless api

---

docs/docs/apis/ratelimits/accounts.md
docs/docs/apis/ratelimits/api.md

- updated to current state
- removed the ones currently no set (maybe we should set them, at least on simulate)

docs: update rate limits

---

internal/auth_request/repository/cache/cache.go
migrations/cockroach/V1.73__auth_request_times.sql

fix: save creation and change date of auth requests in db

---

build/local/local.env

chore: set localhost as local default domain

---

console/src/app/pages/projects/project-role-create/project-role-create.component.html
console/src/app/pages/projects/project-role-create/project-role-create.component.scss
console/src/app/pages/users/user-detail/user-detail/user-detail.component.html

fix(console): project role ui optimization, disable resend init mail btn for reader

---

docs/docs/apis/introduction.mdx

merge after #2656 is deployed on production

docs: add swagger editor links

---

docs/docs/guides/installation/crd.md
docs/docs/guides/installation/gitops.md

docs: document Ambassador v1.x requirement

---

console/src/app/pages/users/user-detail/detail-form/detail-form.component.html
console/src/app/pages/users/user-detail/detail-form/detail-form.component.ts
console/src/app/pages/users/user-detail/user-detail/passwordless/passwordless.component.html
console/src/app/pages/users/user-detail/user-detail/passwordless/passwordless.component.ts
console/src/app/pages/users/user-detail/user-detail/user-detail.component.html

fix(console): disable user action if viewer only

---

internal/query/projection/user.go
migrations/cockroach/V1.99__reset_user_projections.sql

merge after https://github.com/caos/zitadel/pull/2728

fix: user projection

---

go.mod
go.sum
internal/admin/repository/eventsourcing/eventstore/iam.go
internal/config/config.go
internal/i18n/i18n.go
internal/management/repository/eventsourcing/eventstore/org.go

replaces abandoned ghodss/yaml with supported and maintained sigs.k8s.io/yaml package

chore(deps): replace "github.com/ghodss/yaml" with "sigs.k8s.io/yaml"

---

console/src/app/pages/users/user-create-machine/user-create-machine.component.html
console/src/app/pages/users/user-create/user-create.component.html
console/src/app/pages/users/user-create/user-create.component.scss
console/src/app/pages/users/user-create/user-create.component.ts
console/src/app/pages/users/user-create/user-create.module.ts
console/src/app/pages/users/user-detail/auth-user-detail/auth-user-detail.component.scss
console/src/app/pages/users/user-detail/auth-user-detail/auth-user-detail.component.ts
console/src/app/pages/users/user-detail/auth-user-detail/edit-dialog/edit-dialog.component.html
console/src/app/pages/users/user-detail/auth-user-detail/edit-dialog/edit-dialog.component.scss
console/src/app/pages/users/user-detail/auth-user-detail/edit-dialog/edit-dialog.component.ts
console/src/app/pages/users/user-detail/user-detail/user-detail.component.scss
console/src/app/pages/users/user-detail/user-detail/user-detail.component.ts
console/src/app/services/mgmt.service.ts
console/src/assets/i18n/de.json
console/src/assets/i18n/en.json
console/src/assets/i18n/it.json

feat(console): set email verified on change, user create

---

console/src/app/modules/password-complexity-view/password-complexity-view.component.html
console/src/app/modules/password-complexity-view/password-complexity-view.component.scss
console/src/app/pages/users/user-create/user-create.component.html
console/src/app/pages/users/user-create/user-create.component.scss
console/src/app/pages/users/user-create/user-create.component.ts
console/src/app/pages/users/user-create/user-create.module.ts
console/src/assets/i18n/de.json
console/src/assets/i18n/en.json
console/src/assets/i18n/it.json

feat(console): set initial password on user create

---

docs/docs/apis/introduction.mdx
docs/docs/guides/authentication/authmethods.mdx
docs/docs/guides/authentication/authmethods/implicit.mdx
docs/docs/guides/authentication/authmethods/pkce.mdx
docs/docs/guides/authentication/authmethods/pkcenative.mdx
docs/docs/guides/authentication/login-users.mdx
docs/docs/guides/basics/get-started.mdx
docs/package.json
docs/yarn.lock

The broken docusaurus release will be fixed in #2643 but as this pr is not ready and #2889 is stuck due to the broken pipeline I cherry-picked the changes into this PR to get the problem sorted faster.

docs: fix broken docs pipeline

---

console/src/app/modules/warn-dialog/warn-dialog.component.html
console/src/app/modules/warn-dialog/warn-dialog.component.ts
console/src/app/modules/warn-dialog/warn-dialog.module.ts
console/src/app/pages/users/user-list/user-table/user-table.component.ts
console/src/app/services/grpc-auth.service.ts
console/src/assets/i18n/de.json
console/src/assets/i18n/en.json
console/src/assets/i18n/it.json

feat(console): add confirmation field for user deletion, self warning

---

README.md

- Changes link to discord server (permanent)
- Adds elixir library by joshmartin

docs(readme): Updates readme

---

docs/docusaurus.config.js

This PR does proxy the plausible script through our domain and also the events fired from it.
Due to some constraints in the docusaurus plugin I removed it.
@livio-a please have a look at this PR

chore: proxy plausible

---

internal/query/user.go
internal/query/user_test.go

https://status.zitadel.ch/incidents/74678

fix: user search with login_name (e.g. password reset)

---

console/src/app/modules/features/features.component.html
console/src/app/modules/features/features.component.scss
console/src/app/modules/features/features.component.ts
console/src/app/pages/actions/action-table/action-table.component.html
console/src/app/pages/actions/action-table/action-table.component.scss
console/src/app/pages/actions/action-table/action-table.component.ts
console/src/app/pages/actions/actions.component.html
console/src/app/pages/actions/actions.component.scss
console/src/app/pages/actions/actions.component.ts
console/src/app/services/mgmt.service.ts
console/src/assets/i18n/de.json
console/src/assets/i18n/en.json
console/src/assets/i18n/it.json

feat(console): limited actions

---

go.mod
go.sum
internal/api/assets/asset.go
internal/command/statics.go

Remove exif data on upload of an image

feat: remove exif data from uploaded images

---

docs/docs/guides/installation/crd.md
docs/docs/guides/installation/gitops.md

docs: fix $SID => $TWILIO_SID

---

docs/docs/concepts/structure/_user_description.mdx
docs/docs/concepts/structure/users.md
docs/sidebars.js

- Expand sidebar
- Add more information to user
- remove imports where not required

docs: Update concepts

---

.github/workflows/zitadel.yml
.goreleaser.yaml
.releaserc.js

BREAKING CHANGE: 🧨 increment major version

ci: publish releases

---

docs/docusaurus.config.js

This adds a banner as notice for the docs page towards the old page

docs: add banner

---

CONTRIBUTING.md
README.md
SECURITY.md
cmd/admin/admin.go
cmd/zitadel.go
console/src/assets/i18n/de.json
console/src/assets/i18n/en.json
internal/api/ui/login/static/i18n/de.yaml
internal/api/ui/login/static/i18n/en.yaml

Fixes various typos across readmes, console, login

fix: various typos

---

internal/notification/static/i18n/en.yaml
internal/static/i18n/de.yaml
internal/static/i18n/en.yaml

More typos in internal and notifications in de, en

chore: more typos

---

internal/api/ui/login/static/resources/scripts/change_password_check.js
internal/api/ui/login/static/resources/scripts/password_policy_check.js

fix: password check policy correctly

---

docs/docs/guides/basics/organizations.mdx

chore(docs): fix typo

---

docs/docusaurus.config.js
docs/package.json
docs/yarn.lock

- Replace image zoom plugin
- Add background colors

fix(docs): image zoom plugin

---

console/src/app/modules/form-field/form-field.component.scss
console/src/app/pages/users/user-create/user-create.component.scss
console/src/app/pages/users/user-create/user-create.component.ts

fix(console): username overflow when suffix is shown

---

docs/docs/guides/customization/branding.md

example was pointing to accounts.zitadel.ch

fix(docs): primary domain scope

---

console/src/app/pages/actions/action-table/action-table.component.html
console/src/app/pages/signedout/signedout.component.html

fix(console): asset path on signout route, stop event propagation in actions table

---

console/src/app/pages/projects/apps/app-secret-dialog/app-secret-dialog.component.html
console/src/app/pages/users/user-detail/auth-user-detail/auth-factor-dialog/auth-factor-dialog.component.html
console/src/app/pages/users/user-detail/auth-user-detail/auth-factor-dialog/auth-factor-dialog.component.scss
console/src/app/pages/users/user-detail/auth-user-detail/auth-factor-dialog/auth-factor-dialog.component.ts

Closes #3994 
the secret is now shown below

fix(console): show otp secret

---

console/src/app/modules/info-row/info-row.component.html
console/src/app/modules/info-row/info-row.component.ts
console/src/app/pages/instance/instance.component.html
console/src/app/pages/instance/instance.component.scss
console/src/app/pages/instance/instance.component.ts
console/src/app/pages/instance/instance.module.ts
console/src/app/services/admin.service.ts
console/src/assets/i18n/de.json
console/src/assets/i18n/en.json
console/src/assets/i18n/fr.json
console/src/assets/i18n/it.json

feat(console): show instance detail

---

internal/api/grpc/management/org.go
internal/command/org.go
internal/command/org_domain.go
internal/command/org_domain_test.go
internal/command/org_member_test.go
internal/command/org_test.go
internal/command/preparation_test.go
internal/command/project_application_api_test.go
internal/command/project_application_oidc_test.go
internal/command/project_test.go
internal/command/user.go
internal/command/user_human_test.go
internal/query/projection/user.go
internal/query/projection/user_test.go

fix: set domain verified if domain policy does not require validation

---

.github/workflows/release-channels.yml

fix to copy multichannel architectures

chore: copy multiarchitecture manifests

---

docs/docs/guides/integrate/export-and-import.md

This PR fixes the wrong heading and improves the wording to reduce redundancy in the headings

docs(import/export): improve and fix heading

---

.github/workflows/e2e.yml

added firefox and chrome for finished releases, PR stay electron for speed

chore: added multiple browser support

---

.goreleaser.yaml
.releaserc.js

This PR fixes the problem that the arm container included the amd binary

fix: release version for arm broken

---

internal/auth/repository/eventsourcing/eventstore/auth_request.go
internal/command/org.go
internal/command/org_test.go
internal/command/user.go
internal/command/user_human.go
internal/command/user_human_test.go
internal/command/user_test.go
internal/domain/org.go

fix: trim spaces for usernames and organization names

---

console/src/app/modules/members-table/members-table.component.ts

fix(console): membership role deletion

---

cmd/start/start.go
internal/authz/authz.go
internal/authz/repository/eventsourcing/eventstore/token_verifier.go
internal/authz/repository/eventsourcing/repository.go

feat: allow JWT for ZITADEL APIs

---

internal/api/ui/login/init_password_handler.go
internal/api/ui/login/init_user_handler.go
internal/api/ui/login/mail_verify_handler.go
internal/api/ui/login/renderer.go

fix: read custom texts for pages called directly form mail link

---

internal/admin/repository/eventsourcing/eventstore/administrator.go
internal/query/projection/user_auth_method.go
internal/query/projection/user_auth_method_test.go
internal/query/user_auth_method_test.go
internal/webauthn/webauthn.go

- fix: WebAuthN when running under non default port
- fix: auth method column type in user auth methods
- fix: remove notification schema from list of views / failed events

fix: WebAuthN (registration / login) and list on users

---

README.md

Add support for postgres to readme

docs(readme): postgres

---

SECURITY.md

Zitadel v2 is released, so remove outdated note

chore: Update Security policy

---

console/src/app/modules/shortcuts/shortcuts.component.ts

fix(console): create org shortcut

---

docs/docs/apis/openidoauth/grant-types.md
docs/docs/concepts/features/selfservice.md
docs/docs/concepts/structure/_user_description.mdx
docs/docs/concepts/structure/users.md
docs/docs/guides/integrate/azuread-oidc.md
docs/docs/guides/integrate/serviceusers.md

Additionally: 
- typos
- saml in user grant

docs(concepts): update user concept

---

docs/docs/concepts/structure/_instance_description.mdx
docs/docs/concepts/structure/instance.mdx

Describes the concept of virtual instances and their benefits

docs(concepts): describe virtual instances

---

console/src/app/modules/policies/domain-policy/domain-policy.component.ts

fix(console): get instance domain policy

---

internal/api/grpc/admin/import.go
internal/api/grpc/management/user.go
internal/api/ui/login/external_register_handler.go
internal/api/ui/login/login_handler.go
internal/api/ui/login/register_handler.go
internal/auth/repository/eventsourcing/eventstore/auth_request.go
internal/auth/repository/eventsourcing/eventstore/auth_request_test.go
internal/auth/repository/eventsourcing/repository.go
internal/command/user_human.go
internal/command/user_human_test.go
internal/domain/human.go

- [fix: send email verification instead of init code for idp users](https://github.com/zitadel/zitadel/commit/eef4f506a0a5726126349ed11d9a8ee79e818121)
- [fix: select single idp of external only users](https://github.com/zitadel/zitadel/commit/790370d579d97542ee2e640d4f8d7a24803034a0)
- [fix: use single idp on login](https://github.com/zitadel/zitadel/commit/3d9564b34cbea16c612976577b8d8e1b1008224a)

fix: idp usage

---

console/src/app/modules/org-table/org-table.component.ts

fix(console): org table limit

---

docs/docs/guides/deploy/loadbalancing-example/docker-compose.yaml
docs/docs/guides/deploy/loadbalancing-example/example-zitadel-secrets.yaml

Creates and uses client certificates for the unprivileged database user

docs(deploy): fix lb example

---

docs/docs/guides/manage/self-hosted/production.md
docs/docs/guides/manage/self-hosted/reverseproxy/_caddy.mdx
docs/docs/guides/manage/self-hosted/reverseproxy/_httpd.mdx
docs/docs/guides/manage/self-hosted/reverseproxy/_nginx.mdx
docs/docs/guides/manage/self-hosted/reverseproxy/reverse_proxy.mdx

Also contains minor production checklist improvements.

docs(proxy): add Apache httpd example

---

docs/docusaurus.config.js
docs/src/pages/index.js

https://docusaurus.io/docs/next/seo#single-page-metadata
https://validator.schema.org/#url=https%3A%2F%2Fdocs.zitadel.com%2F
@peintnermax any other ideas for seo of docs?

docs: metadata

---

internal/api/api.go

fix: redirect / to login UI

---

README.md

I worked through the basics in the OpenSSF badge and think we can apply this.
This closes #4651

chore: openSSF badge

---

console/src/app/modules/policies/login-texts/helper.ts

fix(console): fix login text ref

---

docs/docs/guides/manage/self-hosted/http2.mdx

apache restructured their links

docs: fix h2c link

---

internal/command/org_domain.go
internal/command/org_policy_domain.go
internal/command/user.go
internal/command/user_domain_policy.go
internal/command/user_domain_policy_test.go
internal/command/user_human.go

maintenance fix of https://github.com/zitadel/zitadel/pull/4872

fix: ensure domain policy is read for the correct org

---

internal/command/main_test.go
internal/command/org.go
internal/command/org_test.go
internal/static/i18n/de.yaml
internal/static/i18n/en.yaml
internal/static/i18n/fr.yaml
internal/static/i18n/it.yaml
internal/static/i18n/zh.yaml

fix: protect default and zitadel project org from remove

---

cmd/defaults.yaml
cmd/setup/setup.go
cmd/start/config.go
cmd/start/start.go
internal/command/main_test.go
internal/eventstore/config.go
internal/eventstore/eventstore.go
internal/eventstore/example_test.go
internal/eventstore/handler/crdb/handler_stmt_test.go
internal/eventstore/handler/handler_projection_test.go
internal/query/projection/main_test.go

* push with timeout
* test: config for eventstore
(cherry picked from commit b9156da76d0f03075589b50eafbf9f48160a0301)

fix: push timeout (#4882)

---

internal/api/grpc/management/user_converter.go
internal/query/user.go

fix: user queries

---

docs/docs/apis/ratelimits/ratelimits.md

according to
https://github.com/caos/zitadel.cloud/pull/52

docs: increase rate limit for api calls

---

.releaserc.js

chore(release): build sprint branch

---

docs/docs/apis/proto/auth.md
internal/api/grpc/auth/policy.go
proto/zitadel/auth.proto

feat(auth api): expose login policy of authenticated user

---

internal/api/ui/login/static/templates/password.html

Adds the description to the password screen.

fix: add description to password screen

---

docs/docs/legal/introduction.mdx
docs/docs/legal/service-level-description.md
docs/docs/legal/support-services.md
docs/docusaurus.config.js

chore: sunset v1 docs

---

internal/api/grpc/management/policy_login.go

fix: only remove idp links from users of own organisation

---

console/src/app/pages/projects/apps/app-detail/app-detail.component.ts

fix(console): replace attr names in app detail

---

docs/vercel.json

chore: fix vercel 404

---

docs/docs/apis/proto/admin.md
docs/docs/apis/proto/management.md
proto/zitadel/admin.proto
proto/zitadel/management.proto

fix(api): correct http methods for provider templates endpoints

---

cmd/setup/08.go
cmd/setup/08.sql
cmd/setup/config.go
cmd/setup/setup.go

fix(storage): add indexes for `auth.tokens`

---

go.mod
go.sum

fix: update saml dependency to v0.0.10

---

cmd/defaults.yaml
go.mod
go.sum

fix: cherry picks

---

internal/actions/object/auth_request.go
internal/api/ui/login/custom_action.go
internal/api/ui/login/external_register_handler.go

* fix(actions): provide browser info and handle nil pointer
* fix(actions): use correct user id in post registration
---------
```[tasklist]
```

fix(actions): provide browser info and handle nil pointer (#5277)

---

docs/docs/guides/manage/user/reg-create-user.md
proto/zitadel/management.proto

docs: verified email

---

console/src/app/pages/users/user-detail/user-detail/user-detail.component.html

fix(console): doc link on user detail

---

docs/docs/manuals/troubleshooting.md

docs: troubleshoot instance not found

---

internal/query/idp_login_policy_link_test.go
internal/query/idp_template_test.go
internal/query/idp_user_link_test.go
internal/query/projection/idp_template.go
internal/query/projection/idp_template_test.go

fix: handling of (old) IDPConfigChangedEvent projection

---

internal/query/idp_login_policy_link_test.go
internal/query/idp_template_test.go
internal/query/idp_user_link_test.go
internal/query/projection/idp_template.go
internal/query/projection/idp_template_test.go

fix: handling of (old) IDPConfigChangedEvent projection (#5384)

---

README.md
docs/src/pages/index.js

docs: links in readme and banner

---

README.md

Add Quickstart Guide, Replace static thumbnails with gif, Make them look similar
```[tasklist]
```

docs(readme): showcase

---

docs/docs/apis/openidoauth/claims.md

docs(openidoauth): add description for custom claims

---

docs/docs/guides/integrate/identity-providers/introduction.md

docs: update introduction.md

---

console/src/app/pages/users/user-detail/auth-user-detail/edit-dialog/edit-dialog.component.ts
internal/api/ui/login/static/i18n/de.yaml
internal/api/ui/login/static/i18n/en.yaml
internal/api/ui/login/static/i18n/fr.yaml
internal/api/ui/login/static/i18n/it.yaml
internal/api/ui/login/static/i18n/pl.yaml
internal/api/ui/login/static/i18n/zh.yaml

fix: open dialogs

---

docs/src/pages/index.js

Some urls on homepage were missing. These are added in this PR
```[tasklist]
```

docs: fix urls on homepage

---

internal/actions/object/user_grant.go

fix: possible nil pointer in actions

---

console/src/app/modules/idp-table/idp-table.component.ts
console/src/app/modules/providers/provider-azure-ad/provider-azure-ad.component.ts
console/src/app/modules/providers/provider-github-es/provider-github-es.component.ts
console/src/app/modules/providers/provider-github/provider-github.component.ts
console/src/app/modules/providers/provider-gitlab-self-hosted/provider-gitlab-self-hosted.component.html
console/src/app/modules/providers/provider-gitlab-self-hosted/provider-gitlab-self-hosted.component.ts
console/src/app/modules/providers/provider-gitlab/provider-gitlab.component.ts
console/src/app/modules/providers/provider-google/provider-google.component.ts
console/src/app/modules/providers/provider-jwt/provider-jwt.component.html
console/src/app/modules/providers/provider-jwt/provider-jwt.component.ts
console/src/app/modules/providers/provider-oauth/provider-oauth.component.ts
console/src/app/modules/providers/provider-oidc/provider-oidc.component.ts
console/src/app/services/admin.service.ts
console/src/app/services/mgmt.service.ts

Closes #5489 
Fixes an issue where the new provider templates could not be removed
```[tasklist]
```

fix(console): delete provider, refactor add and update methods

---

console/src/app/app.component.ts
console/src/app/app.module.ts
console/src/app/modules/policies/login-texts/login-texts.component.ts
console/src/app/modules/policies/message-texts/message-texts.component.ts
console/src/app/pages/org-create/org-create.component.ts
console/src/app/pages/users/user-create/user-create.component.ts
console/src/app/pages/users/user-detail/auth-user-detail/auth-user-detail.component.ts
console/src/app/pages/users/user-detail/user-detail/user-detail.component.ts
console/src/app/pipes/localized-date-pipe/localized-date.pipe.ts
console/src/assets/i18n/de.json
console/src/assets/i18n/en.json
console/src/assets/i18n/fr.json
console/src/assets/i18n/it.json
console/src/assets/i18n/ja.json
console/src/assets/i18n/pl.json
console/src/assets/i18n/zh.json
docs/docs/guides/manage/customize/texts.md
internal/api/ui/login/static/i18n/de.yaml
internal/api/ui/login/static/i18n/en.yaml
internal/api/ui/login/static/i18n/fr.yaml
internal/api/ui/login/static/i18n/it.yaml
internal/api/ui/login/static/i18n/ja.yaml
internal/api/ui/login/static/i18n/pl.yaml
internal/api/ui/login/static/i18n/zh.yaml
internal/api/ui/login/static/templates/external_not_found_option.html
internal/notification/static/i18n/ja.yaml
internal/static/i18n/ja.yaml

Close #3990 
Close #5443 
- Add Japanese translations to all i18n files

feat: internationalization Japanese (recreated)

---

console/src/app/modules/memberships-table/memberships-table.component.ts
console/src/app/modules/policies/secret-generator/secret-generator.component.ts
console/src/app/modules/providers/provider-azure-ad/provider-azure-ad.component.ts
console/src/app/modules/providers/provider-github-es/provider-github-es.component.ts
console/src/app/modules/providers/provider-github/provider-github.component.ts
console/src/app/modules/providers/provider-gitlab-self-hosted/provider-gitlab-self-hosted.component.ts
console/src/app/modules/providers/provider-gitlab/provider-gitlab.component.ts
console/src/app/modules/providers/provider-google/provider-google.component.ts
console/src/app/modules/providers/provider-jwt/provider-jwt.component.ts
console/src/app/modules/providers/provider-oauth/provider-oauth.component.ts
console/src/app/modules/providers/provider-oidc/provider-oidc.component.ts
console/src/app/pages/projects/owned-projects/project-grant-detail/project-grant-detail.component.ts
console/src/app/pages/users/user-detail/auth-user-detail/edit-dialog/edit-dialog.component.ts
console/src/app/pages/users/user-detail/user-detail/user-detail.component.ts
e2e/cypress/support/api/orgs.ts

fix(console): initialize provider options

---

internal/actions/object/metadata.go

fix: map metadata directly in actions

---

internal/actions/object/metadata.go
internal/api/ui/login/custom_action.go

fix: map metadata correctly in actions

---

internal/actions/object/metadata.go
internal/api/ui/login/custom_action.go

fix: map metadata correctly in actions (#5526)

---

docs/docs/apis/ratelimits/ratelimits.md

docs: Fix typo in ratelimits

---

docs/docs/examples/login/angular.md

Updates the documentation for #5189
```[tasklist]
```

docs: add refresh token section to angular guide

---

console/src/app/modules/policies/message-texts/message-texts.component.ts
console/src/app/services/mgmt.service.ts

fix(console): message text setter

---

docs/docs/apis/actions/complement-token.md
docs/docs/apis/actions/external-authentication.md

docs(actions): correct tokens in post authentication

---

go.mod
go.sum
internal/api/oidc/client.go

fix: role claims mapping

---

.github/workflows/zitadel.yml

chore: change action timeout

---

internal/auth/repository/eventsourcing/view/refresh_token.go

fix: update correct current sequence for refresh tokens

---

cmd/start/start.go
go.mod
go.sum
internal/api/oidc/op.go
internal/api/saml/provider.go

fix: update saml to v0.0.11

---

internal/api/grpc/management/idp_converter.go

fix(idp): handle scopes in azureAD

---

README.md

- add LDAP
- structure and update features
```[tasklist]
```

docs(readme): update features

---

docs/docs/guides/integrate/identity-providers/_activate.mdx
docs/docs/guides/integrate/identity-providers/_how_ldap_idp_works.mdx
docs/docs/guides/integrate/identity-providers/_idps_overview.mdx
docs/docs/guides/integrate/identity-providers/azure-ad.mdx
docs/docs/guides/integrate/identity-providers/github.mdx
docs/docs/guides/integrate/identity-providers/gitlab.mdx
docs/docs/guides/integrate/identity-providers/google.mdx
docs/docs/guides/integrate/identity-providers/ldap.mdx
docs/docs/guides/integrate/identity-providers/openldap.mdx

docs: improve idp docs

---

cmd/setup/10.sql

fix(setup): step 10 for postgres

---

internal/eventstore/repository/sql/crdb.go

docs: Fix typo

---

cmd/setup/10.go
cmd/setup/10.sql
cmd/setup/config.go
cmd/setup/setup.go
cmd/setup/steps.yaml

fix(setup): smaller transactions

---

internal/api/grpc/user/v2/user.go
internal/command/instance.go
internal/command/org.go
internal/command/user_human.go
internal/command/user_human_test.go

fix: handle userID and context correctly

---

cmd/setup/cleanup.go
cmd/setup/setup.go
internal/migration/command.go
internal/migration/migration.go

feat(cli): add `setup cleanup` sub command

---

internal/api/http/middleware/access_interceptor.go

fix: correct tracing in access interceptor

---

internal/api/ui/login/custom_action.go

fix: use correct org id for external authentication actions

---

internal/api/ui/login/custom_action.go

fix: use correct org id for external authentication actions (#5793)

---

.github/workflows/zitadel.yml

chore: bump Helm charts from next

---

.dockerignore

chore: speed up local console docker build

---

.github/pull_request_template.md

chore: add dry to pr template

---

go.mod
go.sum

chore: update oidc

---

.goreleaser.yaml

chore: backward compatible stub gen

---

internal/api/ui/login/external_provider_handler.go
internal/api/ui/login/external_provider_handler_test.go
internal/command/user_human_email.go
internal/command/user_human_email_test.go
internal/command/user_human_phone.go
internal/command/user_human_phone_test.go

fix: token for post authentication action and change phone and email

---

docs/docs/apis/openidoauth/endpoints.mdx
docs/docs/apis/saml/endpoints.md

- Info about caching and key rotation for OIDC /keys endpoint
- h1 for search
- titles in sentence case

docs(api): add info about key rotation and caching on /keys endpoint

---

internal/eventstore/repository/sql/crdb.go

fix: more silence

---

cmd/setup/10.go
cmd/setup/10/10_count_wrong_events.sql
cmd/setup/10/10_empty_table.sql
cmd/setup/10/10_fill_table.sql
cmd/setup/11.go
cmd/setup/11/11_fetch_events.sql
cmd/setup/11/cockroach/create_index.sql
cmd/setup/11/cockroach/drop_index.sql
cmd/setup/11/postgres/create_index.sql
cmd/setup/11/postgres/drop_index.sql
cmd/setup/config.go
cmd/setup/setup.go
cmd/setup/steps.yaml

fix(setup): steps 10 and 11

---

docs/docs/guides/migrate/introduction.md

docs(migrate): applications

---

proto/zitadel/user/v2alpha/user_service.proto

chore(v2): user register factors proto definitions

---

console/src/app/pages/users/user-detail/u2f-util.ts

fix(console): url safe base64 to array buffer

---

internal/api/ui/login/external_provider_handler.go
internal/auth/repository/auth_request.go
internal/auth/repository/eventsourcing/eventstore/auth_request.go

fix: update linking users if action changed values

---

internal/api/saml/storage.go

fix: check if application is active in saml logic

---

internal/api/ui/login/external_provider_handler.go
internal/domain/auth_request.go

fix: external user check

---

internal/api/ui/login/static/i18n/fr.yaml

chore: translation error in fr

---

docs/docs/guides/start/quickstart.mdx

docs:Update quickstart.mdx

---

docs/sidebars.js

docs: right link

---

internal/api/oidc/auth_request.go
internal/api/oidc/auth_request_converter.go
internal/auth/repository/eventsourcing/eventstore/auth_request.go
internal/command/auth_request.go
internal/command/auth_request_model.go
internal/command/auth_request_test.go
internal/command/command.go
internal/command/main_test.go
internal/domain/auth_request.go
internal/query/projection/auth_request.go
internal/query/projection/auth_request_test.go
internal/query/projection/projection.go
internal/query/query.go
internal/repository/authrequest/aggregate.go
internal/repository/authrequest/auth_request.go
internal/repository/authrequest/eventstore.go
internal/static/i18n/bg.yaml
internal/static/i18n/de.yaml
internal/static/i18n/en.yaml
internal/static/i18n/es.yaml
internal/static/i18n/fr.yaml
internal/static/i18n/it.yaml
internal/static/i18n/ja.yaml
internal/static/i18n/pl.yaml
internal/static/i18n/zh.yaml

feat: parse and create auth request

---

internal/api/grpc/management/policy_label_converter.go

fix: add font color on new label policy

---

proto/zitadel/management.proto

based on: https://discord.com/channels/927474939156643850/1127916776559235152/1127916776559235152

fix: management proto delete machine key

---

internal/api/ui/login/static/templates/change_password.html
internal/api/ui/login/static/templates/init_user.html
internal/api/ui/login/static/templates/password.html

fix: autofill related issues

---

docs/vercel.json

chore: redirect api path

---

console/src/app/app.module.ts
console/src/assets/i18n/de.json
console/src/assets/i18n/en.json
console/src/assets/i18n/es.json
console/src/assets/i18n/fr.json
console/src/assets/i18n/it.json
console/src/assets/i18n/ja.json
console/src/assets/i18n/pl.json
console/src/assets/i18n/pt.json
console/src/assets/i18n/zh.json

chore: linting in console

---

internal/api/grpc/management/user_grant.go
internal/query/user_grant.go

fix: user grant by id

---

.github/workflows/build.yml

chore: remove on push and merge_group from pipeline execution

---

docs/docs/support/technical_advisory.mdx

docs: add version to technical advisory

---

Makefile

fix: build css for login correctly

---

.github/workflows/build.yml
.github/workflows/release.yml
.releaserc.js

chore: build release on `next` branch

---

proto/zitadel/system.proto

docs: fix add instance domain description

---

e2e/cypress/e2e/quotas/quotas.cy.ts

test: more generous quota e2e timeout

---

docs/docs/guides/integrate/identity-providers/migrate.mdx

docs: fix formatting of idp migration

---

internal/authz/repository/eventsourcing/eventstore/token_verifier.go

fix: trigger session by id in verifySessionToken

---

e2e/cypress/e2e/quotas/quotas.cy.ts

test(e2e): skip quota notifications for now

---

internal/command/oidc_session_test.go

test: fix oidc session test

---

.github/workflows/build.yml

chore: delete ignore paths to run required jobs

---

docs/package.json
docs/yarn.lock

chore(docs): downgrade react

---

internal/query/projection/smtp.go
internal/query/projection/smtp_test.go

close [#5532](https://github.com/zitadel/zitadel/issues/5532)

fix: delete SMTP correctly

---

docs/sidebars.js

Adds a link to resources on our blog on how to integrate with Nextcloud and Cloudflare Workers.

docs(integrate): add nextcloud, cf workers

---

internal/api/oidc/client.go
internal/api/saml/storage.go

fix: setMetadata in saml and pre access token triggers

---

internal/api/ui/login/static/i18n/bg.yaml
internal/api/ui/login/static/i18n/de.yaml
internal/api/ui/login/static/i18n/es.yaml
internal/api/ui/login/static/i18n/fr.yaml
internal/api/ui/login/static/i18n/it.yaml
internal/api/ui/login/static/i18n/ja.yaml
internal/api/ui/login/static/i18n/mk.yaml
internal/api/ui/login/static/i18n/pl.yaml
internal/api/ui/login/static/i18n/pt.yaml
internal/api/ui/login/static/i18n/zh.yaml

fix(login): add some missing translations for OTP

---

docs/yarn.lock
proto/zitadel/oidc/v2alpha/oidc_service.proto
proto/zitadel/org/v2beta/org_service.proto
proto/zitadel/session/v2alpha/session_service.proto
proto/zitadel/settings/v2alpha/settings_service.proto
proto/zitadel/user/v2alpha/user_service.proto

Add Auth Header to the API docs of the new resource API services

docs: add auth header to new api docs

---

internal/api/grpc/admin/idp_converter.go
internal/api/grpc/management/idp_converter.go

fix(api): handle id_token_mapping in generic oidc provider correctly

---

docs/docs/self-hosting/manage/configure/_compose.mdx

chore(docs): update paths for wget downloads

---

internal/api/ui/login/static/i18n/de.yaml

feat: Improve German translations

---

docs/docs/support/advisory/a10002.md
docs/docs/support/technical_advisory.mdx

docs: extend technical advisory

---

README.md

chore: Update discord chat invite

---

docs/docs/apis/actions/objects.md

Resolves #6524
This PR addresses #6524. It fixes the documentation for the userGrant object. Specifically, projectID and projectGrantID.

docs: Fix userGrant object documentation.

---

docs/sidebars.js

docs(integrate): add zoho, boldbi

---

.devcontainer/devcontainer.json

Devcontainer fails to build as we have some 1.21 specific code.

chore(devcontainer): upgrade go

---

internal/webauthn/webauthn.go

adds some debug logs for webauthn errors

chore(webauthn): add logs

---

internal/api/assets/asset.go

fix: typo in "file too big" error message

---

internal/command/quota_model_test.go

test: duplicate quota notifications

---

go.mod
go.sum

Upgrade passwap to include the above feature.
Related to https://github.com/zitadel/zitadel-tools/pull/98

feat(passwap): base64 standard encoding for pbkdf2

---

internal/api/ui/login/static/resources/themes/scss/styles/mfa/mfa_base.scss

Fixes clickable target for the mfa selection for firefox

fix(login): firefox MFA radio mouse target

---

README.md

- Updates authentication methods
- Passkeys instead of passwordless with FIDO2
- Weave in tagline
- Rephrase the free tier and emphasise that cloud is the same version as oss

docs(readme): update authentication methods

---

internal/notification/handlers/origin.go
internal/notification/types/user_email.go
internal/notification/types/user_phone.go
internal/repository/session/session.go
internal/repository/user/human_mfa_otp.go
internal/repository/user/human_phone.go

fix(notification): get origin from all relevant events and fix nil pointer

---

console/src/app/pages/projects/apps/app-detail/app-detail.component.html
console/src/app/pages/projects/apps/app-detail/app-detail.component.scss
console/src/styles/lato-font.scss

fix(console): Load local font asset, remove style override, clockskew reactive forms

---

console/src/app/modules/input/input.directive.ts

fix(console): placeholder accessor

---

console/src/app/modules/policies/private-labeling-policy/private-labeling-policy.component.ts
console/src/app/services/theme.service.ts

fix(console): dont apply colors from branding settings

---

docs/docs/support/advisory/a10002.md
docs/docs/support/technical_advisory.mdx

docs(technical advisory): add version to console branding

---

docs/docs/apis/openidoauth/claims.md

docs: correct spelling in claims.md

---

SECURITY.md

docs(security.md): update link to disclosure policy

---

internal/eventstore/v3/unique_constraints.go

fix(eventstore): correct handling of wrong unique fields

---

docs/docs/guides/integrate/login-ui/_logout.mdx

docs: update session termination documentation

---

go.mod
go.sum

fix: upgrade saml to v0.1.3

---

internal/auth/repository/eventsourcing/eventstore/auth_request.go
internal/auth/repository/eventsourcing/eventstore/auth_request_test.go
internal/auth/repository/eventsourcing/eventstore/refresh_token.go
internal/auth/repository/eventsourcing/eventstore/token.go
internal/auth/repository/eventsourcing/eventstore/user.go
internal/auth/repository/eventsourcing/handler/user.go
internal/auth/repository/eventsourcing/view/user.go
internal/authz/repository/eventsourcing/eventstore/token_verifier.go
internal/user/repository/view/query.go

fix: reduce eventual consistency

---

internal/query/projection/user_grant.go
internal/query/projection/user_grant_test.go

created follow up issue to correct current projection: https://github.com/zitadel/zitadel/issues/7124

fix(projection): correct type cast of user grant reactivated

---

internal/api/oidc/client.go
internal/query/user_by_id.sql
internal/query/user_by_login_name.sql
internal/query/user_notify_by_id.sql
internal/query/user_notify_by_login_name.sql

decreases the query latency of user queries drastically

perf(query): increase speed of user by login name queries

---

internal/query/user_by_id.sql
internal/query/user_by_login_name.sql
internal/query/user_notify_by_id.sql
internal/query/user_notify_by_login_name.sql

* perf(query): increase speed of user queries

perf(query): increase speed of user queries (#7126)

---

cmd/initialise/init.go
cmd/initialise/verify_zitadel.go
cmd/initialise/verify_zitadel_test.go
cmd/key/key.go
cmd/setup/03.go
cmd/start/encryption_keys.go
cmd/start/start.go
cmd/start/start_from_init.go
cmd/start/start_from_setup.go
internal/admin/repository/eventsourcing/view/view.go
internal/crypto/database/database.go
internal/crypto/database/database_test.go
internal/crypto/key_storage.go
internal/eventstore/handler/v2/handler.go
internal/eventstore/handler/v2/state_test.go
internal/eventstore/local_crdb_test.go
internal/eventstore/repository/sql/local_crdb_test.go
internal/eventstore/v3/push.go
internal/query/current_state.go

used to cancel on context done

fix(db): always use begin tx

---

internal/eventstore/handler/v2/handler.go
internal/eventstore/handler/v2/statement.go

execution errors now corretly update failed events and continue after max failed events is reached

fix(handler): updated failed events

---

internal/migration/command.go

instead of an error errors of errors are now unmarshaled into a string

fix(setup): unmarshal of failed step

---

cmd/setup/cleanup.go
cmd/setup/config_change.go
cmd/setup/projections.go
internal/migration/command.go
internal/migration/migration.go
internal/migration/step.go
internal/migration/step_test.go

instead of just the last executed step its now possible to clean up all stuck steps

fix(cleanup): cleanup all stuck states

---

internal/domain/policy_login.go

During a refactoring I removed too much code. The code is added again now

fix(login): correct rendering of idps

---

docs/docs/guides/manage/cloud/billing.md
docs/docs/guides/manage/cloud/settings.md

- Missing docs: Settings, specifically how to delete the account. This reference is useful for support requests.
- Outdated billing docs (tax id)

docs: Update settings, billing for mange cloud

---

internal/query/login_policy.go

This change moves IDPLoginPolicyLinks out of the scan function Login Policy queries in order to prevent potential deadlocks.

fix(query): separate login policy queries

---

console/yarn.lock

chore(console): regenerate yarn lockfile

---

cmd/setup/20.go
cmd/setup/20.sql
cmd/setup/config.go
cmd/setup/setup.go
internal/auth/repository/eventsourcing/handler/user_session.go
internal/auth/repository/eventsourcing/handler/user_session_test.go

fix(auth): efficient user session projection

---

internal/view/repository/query.go
internal/view/repository/requests.go

fix: add RollbackUnlessCommitted for gorm transactions

---

docs/README.md
docs/docs/apis/openidoauth/claims.md
docs/docs/apis/saml/endpoints.md

docs: Add reference to Actions for custom claims and custom attributes

---

internal/eventstore/handler/v2/handler.go

fix(handler): handle trigger err correctly

---

docs/docs/examples/login/vue.md

docs: fix install @zitadel/vue

---

internal/api/grpc/user/v2/query_integration_test.go

test(integration, user): fix flakiness

---

docs/docs/examples/introduction.mdx
docs/docs/examples/secure-api/dot-net.md
docs/sidebars.js

docs: update links of examples

---

docs/docs/support/advisory/a10008.md
docs/docs/support/technical_advisory.mdx

Add additional versions to advisory

docs(a10008): add versions 2.43.6 and 2.42.12

---

docs/docs/self-hosting/manage/updating_scaling.md
docs/docs/support/advisory/a10008.md

docs: fix init-projections flag value

---

docs/docs/guides/integrate/authmethods/_pkce.mdx

docs: add missing word

---

internal/database/cockroach/crdb.go
internal/database/postgres/pg.go

fix: db MaxOpenConns setting

---

docs/docs/guides/integrate/logout.md

docs(integrate): fix typo in logout page

---

docs/docs/concepts/features/custom-domain.md
docs/docs/guides/integrate/login/login-users.mdx
docs/docs/guides/start/quickstart.mdx

docs: remove localhost from links

---

docs/docs/guides/start/quickstart.mdx
docs/docusaurus.config.js
docs/package.json
docs/src/components/player.jsx
docs/src/css/custom.css
docs/yarn.lock

This PR adds a component ResponsivePlayer that allows embedding of videos into mdx pages. 
Since we have a quickstart video, this should be added to the quickstart and make it easier to follow-along.
The quick start is also added to the header of the docs for easy access.

docs: add video to quickstart

---

cmd/setup/23.go
cmd/setup/23.sql
cmd/setup/config.go
cmd/setup/setup.go
internal/eventstore/v3/unique_constraints.go

Instance domains must be unique within the whole zitadel deployment. This fix ensures global uniqueness of instance domains.

fix(eventstore): consider `IsGlobal`-flag of constraints

---

internal/renderer/renderer.go

Corrects the package used to render HTML in the login UI. This makes sure output is safe against code injection.

fix: use correct template package

---

docs/docs/apis/actions/complement-token.md
docs/docs/apis/actions/customize-samlresponse.md
docs/docs/apis/actions/external-authentication.md
docs/docs/apis/actions/internal-authentication.md
proto/zitadel/management.proto

Make clear which flow and trigger types work in combination.
closes https://github.com/zitadel/zitadel/issues/5264

docs: describe combinations of flow and trigger types

---

docs/docs/guides/integrate/login-ui/session-validation.mdx
docs/docs/guides/integrate/login-ui/username-password.mdx
docs/sidebars.js

This PR adds a page in the login UI section on how to validate and expire sessions and their factors.
close #7454

docs: describe session validation

---

.github/workflows/container.yml

chore: fix artifact upload for container build

---

docs/docs/guides/integrate/identity-providers/additional-information.mdx

docs: Update additional-information.mdx

---

internal/query/event.go

Removes span which bloats traces

chore: remove bloating span

---

README.md

We introduced new features and created new docs.

chore: Update readme with new features and links

---

proto/zitadel/admin.proto

chore: typo in api docs

---

docs/docs/guides/manage/console/default-settings.mdx

Add note about what a symbol means in the password policy.

docs: add note about symbol of passwords

---

internal/command/instance.go
internal/command/smtp.go
internal/repository/instance/smtp_config.go

Backport to v2.50 as #6932 was released in v2.50.2

fix(smtp): enable default instance config (#7925)

---

.github/workflows/ready_for_review.yml

It is not very clear if the author or the reviewer of a PR should tick the boxes.
The author of the PR is tagged in the comment.
This makes it clear, who is addressed.

chore: tag author in ready for review comment

---

docs/docs/concepts/features/audit-trail.md

duplicated content
reference to primary conent

docs(features): clean up audit trail feature

---

internal/api/oidc/userinfo.go

During tests of 2.53.3 we noticed that in cases where the `idTokenRoleAssertion` was disabled, claims set in the preAccessTokenTrigger where also set in the id_token.
The userinfo of the id_token now uses a correct copy of their own.
None.
- relates to #7822 
- relates to #8046

fix(oidc): make sure id_token does not contain any info from access token actions

---

MEETING_SCHEDULE.md

Added new info for next office hours

docs(office-hours): add new resource api

---

.github/workflows/docsusaurus.yml

chore(docs): fix prod build for vercel

---

.github/workflows/build.yml
.github/workflows/docsusaurus.yml

This PR tries to fix the upload of the docs preview to vercel which was not working due to the not available secret.

chore(docs): fix ci

---

internal/api/grpc/admin/org.go
internal/api/grpc/management/actions.go
internal/api/oidc/auth_request.go
internal/api/oidc/userinfo.go
internal/command/idp_intent.go

We found multiple cases where either the error was not properly handled, which led to panics.
Handle the errors.
None.
- noticed internally

fix: error handling to prevent panics

---

docs/docs/apis/actions/code-examples.mdx

The docs currently link to the wrong trigger.
Changed the links.

docs(actions): correct actions examples

---

console/src/app/services/grpc-auth.service.ts

This fixes a problem where the org settings were hidden.
The console reads the context from either a query param or the local storage. When one context was found, it executed a single request with orgId filter. This let to a single org and then to a hidden org setting, as we hide org settings for instances with a single result.

fix(console): fill cachedorgs when read from local storage

---

docs/docs/examples/secure-api/pylon.mdx

Add a link to the Pylon website.

docs: update pylon.mdx

---

MEETING_SCHEDULE.md

Announces office hours `login UI deepdive`

docs: add office hour #4

---

.gitignore
load-test/Makefile
load-test/README.md
load-test/package-lock.json
load-test/package.json
load-test/src/oidc.ts
load-test/src/use_cases/machine_jwt_profile_grant.ts
load-test/src/user.ts
load-test/webpack.config.js

Currently there was no load test present for machine jwt profile grant. This test is now added
K6 test implemented.
- part of https://github.com/zitadel/zitadel/issues/8352

test(load): machine jwt profile grant

---

docs/docs/support/software-release-cycles-support.md

Charts support is not described anywhere
It is listed in https://zitadel.com/docs/support/software-release-cycles-support#enterprise-supported along the LDAP IDP and the Terraform Provider

docs: enterprise support for charts

---

console/src/assets/i18n/en.json
internal/api/ui/login/static/i18n/en.yaml

- English typo and grammar fixes.

docs: some English spelling and grammar fixes

---

README.md

Update readme with regions, and a link to the change log

docs: Update regions and link to changelog changelog

---

proto/zitadel/user/v2/user_service.proto

Use body for update user endpoint on user v2 API.

fix: use body for update user on user v2 API

---

MEETING_SCHEDULE.md

Added meeting schedule for office hours

docs(office_hours): add Q&A on 2024-09-25

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yaml

We want to use the new issue types of github

chore: test issue type

---

.gitignore
load-test/Makefile

Load tests currently do not output details about the data messured.
Added the `--out` flag to all load tests

chore(load-test): add csv output

---

docs/docs/apis/actions/modules.md

Updated the example to fit with the actual logger signature. Solves #8811.

docs: update logger example for action modules

---

ADOPTERS.md
README.md

We want to give adopters a platform to show that they are using ZITADEL
Addding an ADOPTERS.md file
none
none

chore: adding an adopters file for our community

---

ADOPTERS.md

This improves the `ADOPTERS.md` file to better understand its purpose.
Adding additional instructions to the `ADOPTERS.md` file

chore: improve adopters file

---

ADOPTERS.md

docs(adopter): RawkodeAcademy

---

ADOPTERS.md

I love Zitadel, and we have been using it for a while. It's the most complete solution out there. ❤️

docs: Add adopters

---

ADOPTERS.md

docs(adopter): devOS: Sanity Edition org

---

docs/docs/legal/subprocessors.md

Link list of subprocessors to our trust center

docs(legal): link subprocessors to trust center

---

ADOPTERS.md

docs(adopters): add roclub

---

docs/docs/guides/integrate/zitadel-apis/example-zitadel-api-with-dot-net.md
docs/docs/support/troubleshooting.mdx

- This replaces the old aud claim from Zitadel in two places.
- Relates to [this discord thread](https://discord.com/channels/927474939156643850/1305853084743766067)

docs: change scope for zitadel audience

---

internal/api/scim/authz.go
internal/api/scim/integration_test/users_create_test.go
internal/api/scim/integration_test/users_delete_test.go
internal/api/scim/resources/resource_handler.go
internal/api/scim/resources/resource_handler_adapter.go
internal/api/scim/resources/user.go
internal/api/scim/resources/user_mapping.go
internal/api/scim/server.go
internal/integration/scim/assertions.go
internal/integration/scim/client.go

- Adds support for the user delete SCIM v2 endpoint
- Adds support for the user delete SCIM v2 endpoint under `DELETE /scim/v2/{orgID}/Users/{id}`
Part of #8140

feat: delete user scim v2 endpoint

---

docs/docs/concepts/features/selfservice.md

Small update to docs/docs/concepts/features/selfservice.md to fix issue in grammar

docs: small update to docs/docs/concepts/features/selfservice.md

---

cmd/defaults.yaml
internal/api/scim/authz.go
internal/api/scim/config/config.go
internal/api/scim/integration_test/bulk_test.go
internal/api/scim/integration_test/scim_test.go
internal/api/scim/integration_test/testdata/bulk_test_errors.json
internal/api/scim/integration_test/testdata/bulk_test_fail_on_errors.json
internal/api/scim/integration_test/testdata/bulk_test_full.json
internal/api/scim/integration_test/users_list_test.go
internal/api/scim/integration_test/users_update_test.go
internal/api/scim/metadata/context.go
internal/api/scim/middleware/scim_context_middleware.go
internal/api/scim/resources/bulk.go
internal/api/scim/resources/patch/patch.go
internal/api/scim/resources/resource_handler.go
internal/api/scim/resources/resource_handler_adapter.go
internal/api/scim/resources/resource_list.go
internal/api/scim/resources/user.go
internal/api/scim/resources/user_mapping.go
internal/api/scim/schemas/schemas.go
internal/api/scim/serrors/errors.go
internal/api/scim/server.go
internal/integration/scim/client.go

* Adds support for the bulk SCIM v2 endpoint
* Adds support for the bulk SCIM v2 endpoint under `POST /scim/v2/{orgID}/Bulk`
Part of #8140

feat: bulk scim v2 endpoint

---

README.md

Removal of Community Call reference for the moment until further reviewed on next steps forward from group.
Removed table and text of Community call out.

docs: Zitadel README.md Community Call Ref

---

console/src/app/modules/filter-org/filter-org.component.ts
console/src/app/modules/filter-project/filter-project.component.ts
console/src/app/modules/filter-user-grants/filter-user-grants.component.ts
console/src/app/modules/filter-user/filter-user.component.html
console/src/app/modules/filter-user/filter-user.component.ts
console/src/app/modules/filter/filter.component.ts
console/src/app/pages/users/user-detail/auth-user-detail/auth-user-detail.component.html
console/src/app/pages/users/user-detail/auth-user-detail/auth-user-detail.component.ts
console/src/app/pages/users/user-detail/detail-form-machine/detail-form-machine.component.html
console/src/app/pages/users/user-list/user-list.component.html
console/src/app/pages/users/user-list/user-list.component.ts
console/src/app/pages/users/user-list/user-table/user-table.component.html
console/src/app/pages/users/user-list/user-table/user-table.component.ts
console/src/app/services/user.service.ts

- Fixed filtering in overview
- Only get users from current organization
- Use V2 api to get auth user
Added the organization filter to the List queries
Get current User ID from ID Token to get auth user by id
Refactored the UserList
- Closes #9382

fix: v2 user console errors

---

internal/api/grpc/admin/org.go
internal/api/grpc/user/v2/integration_test/query_test.go
internal/api/grpc/user/v2beta/integration_test/query_test.go

Enhancing `v2/ListUsers()` tests by adding code to run all test with and without `permission_check_v2` flag set
- Closes https://github.com/zitadel/zitadel/issues/9356

chore(tests): test ListUsers with and without permission_check_v2 flag set

---

console/src/app/app.component.html
console/src/app/components/features/features.component.html
console/src/app/components/features/features.component.ts
console/src/app/modules/header/header.component.ts
console/src/app/modules/providers/provider-oidc/provider-oidc.component.ts
console/src/app/pages/users/user-create/user-create.component.html
console/src/app/pages/users/user-create/user-create.component.scss
console/src/app/pages/users/user-create/user-create.component.ts
console/src/app/services/grpc-auth.service.ts

- Correctly load Avatar on first load
- The Avatar issue was mostly due to how we resolved the current user, I changed this behaviour
- Removed V2 create human code till seperate page is finished
- Remove Console Use V2 API feature flag from features page (till new page is added)
- Partially fixes #9382
- This will get implemented next week https://github.com/zitadel/zitadel/issues/9382#issuecomment-2681347477

fix: Create Human V1

---

internal/api/ui/login/static/resources/scripts/webauthn.js
internal/api/ui/login/static/resources/scripts/webauthn_login.js
internal/api/ui/login/static/resources/scripts/webauthn_register.js

This PR improves error handling around webauthn functions in the login.

fix(login): improve webauthn error handling

---

cmd/setup/49/01-permitted_orgs_function.sql

SQL error in `cmd/setup/49/01-permitted_orgs_function.sql`
Updating `cmd/setup/49/01-permitted_orgs_function.sql`
- Closes https://github.com/zitadel/zitadel/issues/9461

fix(permission): sql error in cmd/setup/49/01-permitted_orgs_function.sql

---

internal/api/grpc/oidc/v2/integration_test/oidc_test.go
internal/api/grpc/oidc/v2beta/integration_test/oidc_test.go

Integration tests for OIDC service failed irregularly.
Add eventual consistent checks for querying endpoints to the integration tests for the OIDC service.
None
None

chore: correct integration tests for query endpoints eventual consistent

---

console/src/app/modules/policies/oidc-webkeys/oidc-webkeys-table/oidc-webkeys-table.component.html
console/src/styles/table.scss

This PR changes the colors for the webkeys feature.
Ref: https://github.com/zitadel/zitadel/pull/9526#issuecomment-2735722478

fix: webkeys colors

---

docs/docs/guides/integrate/login-ui/external-login.mdx

This PR improves the readability of the difference in the IDP callback of the new V2 login compared to the legacy login.

docs: improve readability of idps callback

---

cmd/setup/config.go
cmd/setup/setup.go

Step 54 was not executed during setup.
Added the step to setup jobs
none
- the step was added in https://github.com/zitadel/zitadel/pull/9837
- thanks to @zhirschtritt for raising this.

fix(setup): execute s54

---

API_DESIGN.md

There were some misunderstandings on how different points would be needed to be applied into existing API definitions.
- Added structure to the API design
- Added points to context information in requests and responses
- Added examples to responses with context information
- Corrected available pagination messages
- Added pagination and filter examples
None
None

docs: extend api design with additional information and examples

---

cmd/mirror/projections.go
internal/query/projection/projection.go

- fields projections were not projected during mirror
- an extra step during projections was added to mirror the fields 
none
none

fix(mirror): include fields in mirror projections

---

docs/docs/guides/manage/console/default-settings.mdx

Broken links on the default settings page.
Fixed the reference

docs: fix broken link

---

.github/workflows/ready_for_review.yml

make review comment more clear what is expected

chore: update review comment

---

login/apps/login/src/lib/saml.ts
login/apps/login/src/lib/zitadel.ts

Fixes issues where SAML identity provider authentication would fail silently, leaving users unable to complete the login flow through external SAML providers.
changes `saml.ts`:
- Enhanced [setSAMLFormCookie()](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) with proper error handling and logging
- Improved [getSAMLFormCookie()](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html) with detailed error reporting
- Added cookie size validation and warnings
changes `zitadel.ts`:
- Enhanced [startIdentityProviderFlow()](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs …

fix(login): better error handling for saml cookie serialization

---

.github/workflows/build.yml
.github/workflows/compile.yml
.github/workflows/lint.yml
.github/workflows/login-container.yml

We hit a rate limit for our current plan at Depot https://github.com/zitadel/zitadel/actions/runs/16589101600/job/46920267954?pr=10342.
Let's remove Depot for now, make things work and then optimize with caching.

chore: remove depot

---

load-test/Makefile
load-test/package-lock.json
load-test/package.json
load-test/src/login_ui.ts
load-test/src/membership.ts
load-test/src/metadata.ts
load-test/src/oidc.ts
load-test/src/use_cases/users_by_metadata_key.ts
load-test/src/use_cases/users_by_metadata_value.ts
load-test/src/user.ts
load-test/src/user_grant.ts

Introduce load tests to benchmark user creation and retrieval based on metadata. Update dependencies and improve code readability.

test(benchmarks): tests for users by metadata

---

backend/v3/storage/database/query.go
backend/v3/storage/database/repository/doc.go

There is no implementation of the permission framework in the new repository pattern. We risk frogetting permission options as we are already migrating the service layer to the new pattern.
Add a placeholder query permission option.
- none 
- Draft design: https://github.com/zitadel/zitadel/wiki/Internal-AuthZ#enforcement

feat(repository): add permission check option

---

docs/vercel.json

Added a redirect from the old billing docs page to the new knowledge base section.

docs: added a redirect from the old billing docs page to the new knowledge base section
