zitadel/zitadel

- .codecov/codecov.yml
This makes all `codecov` features configurable within the repo. Right now we use the default settings.
See [here](https://docs.codecov.io/v4.3.0/docs/codecov-yaml) for the options
> chore(codecov): make codecov configurable in repo

- go.mod
This not existing packet version does block dependabot.
I therefore removed it. As the build still passes i think everything is great.
> chore: remove not existing upstream

- cmd/zitadel/startup.yaml
not sure if `ssl=true` should be removed as well
> fix: missing password config

- .github/workflows/codeql-analysis.yml
👋🏻  Hello, I'm a product manager at GitHub. I noticed that you're using CodeQL, but your workflow follows an older template of ours. This updated template reduces duplicate analyses by only running on push to master, or PRs to master. 
Let me know if you have any questions
> Optimize CodeQL analysis

- .github/workflows/docs.yml
- .github/workflows/release.yml
- build/docker/Dockerfile
This PR will:
- Remove **anchore** as we rely on scratch
- Update the docker file so that only **ZITADEL** files are copied into scratch
> fix(container): stop copying / and instead only copy zitadel

- internal/project/repository/eventsourcing/eventstore.go
- internal/static/i18n/de.yaml
- internal/static/i18n/en.yaml
- don't fail if OIDCClientSecretCheckSucceeded event can not be pushed
- improve error message (client secret invalid)
> fix: improved OIDC Client Secret Check

- .github/workflows/docs.yml
- site/README.md
tags-ignore does only work with branches defined as well: https://github.community/t/using-on-push-tags-ignore-and-paths-ignore-together/16931/2
> chore(workflow): run docs on any branch

- internal/api/authz/context.go
header will only be needed if an other org / multiple orgs a necessary
> feat: make x-zitadel-orgid optional (resource owner by default)

- docs/docs/concepts/architecture.md
The `P` in `CAP` stands for network partition tolerance (see https://en.wikipedia.org/wiki/CAP_theorem).
Instead of CAP, you might want to refer to [PACELC](https://en.wikipedia.org/wiki/PACELC_theorem) instead, which is more applicable IMO.
> docs: fix CAP theorem acronym resolution

- .github/workflows/zitadel.yml
- README.md
This PR prepares our pipeline so that we can accept external pull request (e.g. forked ones).
And also it removes my `PAT` and uses the `GH_TOKEN`
There is a bug with GH Actions so that the `on: pull_request` does terminate with a 403 [GH Bug](https://github.community/t/403-error-on-container-registry-push-from-github-action/173071/20?u=fforootd)
> chore: remove PAT and use GH Token

- README.md
@fforootd How should we add videos / gifs to the README.
I would like to show passwordless Login (iOS + Win) and setting up an application in ZITADEL for preview. We have those videos as .mp4
> docs: update run and start section texts

- console/src/app/modules/client-keys/client-keys.component.ts
- console/src/app/modules/show-key-dialog/show-key-dialog.component.html
- console/src/app/modules/show-key-dialog/show-key-dialog.component.ts
- console/src/app/pages/projects/apps/app-create/app-create.component.html
- console/src/app/pages/projects/apps/app-create/app-create.component.ts
- console/src/app/pages/projects/apps/app-detail/app-detail.component.html
- console/src/app/pages/projects/apps/app-detail/app-detail.component.ts
- console/src/assets/i18n/de.json
- console/src/assets/i18n/en.json
> fix(console): add model for api keys, fix toast, binding

- console/src/app/app.component.html
- docs/docusaurus.config.js
- internal/ui/login/static/i18n/de.yaml
- internal/ui/login/static/i18n/en.yaml
Should update the links to Terms of Service and the Privacy Policy throughout ZITADEL (footers, logins, ...)
> fix: tos and privacy links

- internal/ui/login/static/resources/scripts/input_suffix_offset.js
fixes js error when no domain suffix is displayed:
> fix: eventListener in input_suffix_offset.js

- console/src/app/app.component.ts
- console/src/app/services/grpc-auth.service.ts
- console/src/app/services/storage.service.ts
This remembers the last selected org
in localstorage instead of session storage to improve the UX. Furthermore,
the list of organizations is ordered by
name instead of just the returned result set.
> feat(org-selector): Remember the last selected org and order the list.

- docs/docs/guides/customization/branding.md
Adds a usable example on how to use the primary domain scope.
> docs(guides): adds example for primary domain scope

- .github/workflows/release-notification.yaml
When a new release is published, then a webhook is sent to discord. Skip pre-releases.
> chore: Adds release notification action

- internal/auth/repository/eventsourcing/handler/user.go
- internal/eventstore/handler/handler_projection.go
- internal/notification/repository/eventsourcing/handler/notify_user.go
- internal/user/repository/view/model/notify_user.go
- internal/user/repository/view/model/user.go
- migrations/cockroach/V1.112__login_names.sql
Some login names and preferred login names were incorrectly built in views required during login. They had an additional login names entry with missing domain suffix from org, which then was also set as their preferred login name.
The new projection tables are correct and are used for looking up the user when trying to reset the password for example. therefor the users could not be found due to the different data.
This also fixes a similar issue in the notifications table where the almost exactly same problem exists.
> fix: correct login names on auth and notification users

- .goreleaser.yaml
This will add support to auto create the necessary tap.
But be aware the draft we currently publish will not be available to download.
> fix(goreleaser): fix tap and disable discord for the moment

- README.md
Fixed a typo in the readme.  Secure was misspelled.
> docs: Fixed sucure/secure typo in Passwordless Login section

- internal/api/ui/login/static/i18n/de.yaml
The correct spelling for email in german is "E-Mail"
> fix: "EMail" typo

- internal/ui/login/handler/renderer.go
currently the language is rendered with region as incorrect string, e.g. `en-u-rg-uszzzz`
`{{.Lang}}` can be used in templates, e.g. privacy policy link
with this PR {{.Lang}} will only render the base tag, e.g. `en`
> fix: render only base language in html

- .releaserc.js
- cmd/zitadel/startup.yaml
- internal/api/oidc/op.go
- operator/zitadel/kinds/iam/zitadel/configuration/desired.go
- operator/zitadel/kinds/iam/zitadel/configuration/literals.go
env vars:
```
DefaultAccessTokenLifetime: $ZITADEL_DEFAULT_ACCESS_TOKEN_LIFETIME
DefaultIdTokenLifetime: $ZITADEL_DEFAULT_ID_TOKEN_LIFETIME
DefaultRefreshTokenIdleExpiration: $ZITADEL_DEFAULT_REFRESH_TOKEN_IDLE_EXPIRATION
DefaultRefreshTokenExpiration: $ZITADEL_DEFAULT_REFRESH_TOKEN_EXPIRATION
```
operator yaml:
```
oidcLifetimes:
accessTokenLifetime: 12h
idTokenLifeTime: 12h
refreshTokenIdleExpiration: 720h
refreshTokenExpiration: 21260h
```
> feat: configurable OIDC lifetimes via env vars

- guides/development.md
The current development instructions reference non-existent files and currently fail because they assume that `DOCKER_BUILDKIT` is set. This change removes references to deprecated files and includes guidance on setting the `DOCKER_BUILDKIT` environment variable.
> docs(development): Remove references to deprecated files, add info on DOCKER_BUILDKIT

- internal/api/ui/login/external_login_handler.go
- internal/api/ui/login/external_register_handler.go
- internal/api/ui/login/policy_handler.go
- internal/api/ui/login/register_handler.go
- internal/api/ui/login/static/templates/external_not_found_option.html
- internal/api/ui/login/static/templates/external_register_overview.html
- internal/api/ui/login/static/templates/register.html
> fix: hide / show username suffix correctly on registration pages

- .goreleaser.yaml
(only skip latest manifest on prereleases)
> chore: always push docker image

- docs/docs/apis/ratelimits/ratelimits.md
When you only look at the api/ratelimits page then a reader would miss the context of the rate limit policy. specifically how the rate limit is implemnted (by IP address). The two docs are in different sections, so navigation is also not very clear.
> docs(api): link rate limit policy to rules

- internal/api/grpc/admin/import.go
- internal/command/instance_idp_config.go
- internal/command/project_grant_member.go
- internal/command/project_member.go
- internal/command/user_human_otp.go
- internal/command/user_idp_link.go
- internal/command/user_idp_link_test.go
- internal/eventstore/handler/crdb/handler_stmt_test.go
- internal/eventstore/handler/crdb/lock_test.go
- internal/user/repository/view/model/user.go
If import wasn't able to create the org and the org doesn't exist, additional data won't be created. `OTP` and `user idp link`  checks if the user exists.
> fix(import): check exists

- cmd/initialise/verify_zitadel.go
- cmd/setup/config.go
- internal/database/cockroach/config.go
- internal/database/postgres/config.go
- internal/eventstore/handler/crdb/handler_stmt.go
- internal/eventstore/handler/crdb/statement.go
- internal/eventstore/handler/crdb/statement_test.go
- internal/query/projection/app_test.go
- internal/query/projection/authn_key_test.go
- internal/query/projection/login_name_test.go
- internal/query/projection/sms_test.go
- internal/query/projection/user_grant_test.go
- internal/query/projection/user_test.go
- fix(cli): commands which were broken. The commands read their configuration correctly. 
- fix(database): configurations work now properly using env variables
- fix(database): `UPDATE` and `INSERT ON CONFLICT DO UPDATE` statements are now fully postgresql compatible
> fix: initial failures

- console/src/app/modules/footer/footer.component.html
The twitter account `zitadel_ch` doesn't exist. `zitadel` does.
> fix: twitter account link

- docs/docs/apis/introduction.mdx
A compact list of ZITADEL path prefixes helps users configure reverse proxies or other networking components.
For example: https://discord.com/channels/927474939156643850/928175516664602694/1017101014060503080
> docs: list path prefixes

- .gitignore
- internal/api/oidc/auth_request.go
- internal/api/oidc/client.go
- internal/auth/repository/eventsourcing/eventstore/token.go
- internal/auth/repository/eventsourcing/view/token.go
- internal/auth/repository/token.go
- internal/authz/repository/eventsourcing/eventstore/token_verifier.go
- internal/authz/repository/eventsourcing/view/token.go
- internal/user/repository/view/token_view.go
If userinfo is called using an opaque access token, the token is encoded into `tokenID:subject` if the last view letters were removed from the access token, the userinfo are still returned because the code currently does not check the subject while reading from the database. This fix changes this behaviour by always checking `tokenID` and `subject`.
Example:
`NsQonadRdZZ9HXaJ1dMF4cfaq99x9BuOVcH7cVYNuYRBnmXRaGnB-S0iYeS8DF1vtJlO7qA`: `178930652421292452: 178050570823800541`
remove the last 12 letters
`NsQonadRdZZ9HXaJ1dMF4cfaq99x9BuOVcH7cVYNuYRBnmXRaGnB-S0iYeS8`: `178930652421292452 : 1780505708`
The lower request should fail but doesn't at the moment because the subject is not checked
> fix(auth): always get token by id and user id

- CONTRIBUTING.md
- console/src/app/modules/project-members/project-members.component.html
- console/src/app/pages/domains/domains.component.html
- console/src/app/pages/home/home.component.html
- console/src/app/pages/instance/instance-members/instance-members.component.html
- console/src/app/pages/orgs/org-members/org-members.component.html
- console/src/app/pages/projects/apps/app-detail/app-detail.component.html
- console/src/app/pages/projects/granted-projects/granted-project-detail/granted-project-detail.component.html
- console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.html
- console/src/app/pages/projects/projects.component.html
- console/src/app/pages/users/user-detail/user-detail/user-detail.component.html
- docs/docs/apis/proto/management.md
- docs/docs/apis/proto/policy.md
- docs/docs/examples/call-zitadel-api/dot-net.md
I found some broken links in the UI to the moved documentation.
I used https://github.com/lycheeverse/lychee to scan for broken links.
```
$ cat <<'EOF' > .lycheeignore
^file://
^https://accounts\.exmaple\.com/saml/metadata$
^https://demo\.com/tos-%7B%7B.Lang%7D%7D$
^https://example\.auth0\.com/samlp/metadata\?connection=SAML-ZITADEL$
^https://gitlab\.com/dashboard/groups$%
EOF
$ lychee --verbose --no-progress --exclude-link-local --exclude-mail --exclude-loopback .
```
> fix: fixed broken documentation links

- internal/auth/repository/eventsourcing/eventstore/auth_request.go
> fix: clear potentially existing user information on auth request for domain discovery

- docs/docs/guides/integrate/azuread-oidc.md
Smaller updates to the AzureAD OIDC integration guide. Main update is that the `issuer` endpoint needs to be extracted from the OpenID Connect metadata (typically the tenant's url appended with /v2.0).
> docs(azuread): update azuread integration guide

- cmd/setup/05.sql
The statements caused an error for me because the columns were already existing.
> fix(database): create column only if not exists

- CONTRIBUTING.md
This avoids forgetting to lint the code.
This is triggered by https://discord.com/channels/927474939156643850/1060109150488629248/1060118559545626624
> docs: describe linting in the dev process

- internal/command/instance_member.go
- internal/command/instance_member_test.go
- internal/command/org_member.go
- internal/command/org_member_test.go
- internal/command/project_member.go
- internal/command/project_member_test.go
> fix(command): return empty object detail if not found

- console/src/app/modules/info-row/info-row.component.ts
Followup fix for #5055
Closes #4929
Only shows verified email and phone numbers as login options on the user pages
> fix(console): only show verified emails and phonenumbers as loginoptions

- docs/docs/guides/solution-scenarios/b2c.mdx
This PR removes the text `//TODO extend this passage` from [B2C#Federation](https://zitadel.com/docs/guides/solution-scenarios/b2c#federation)
```[tasklist]
```
> docs: remove TODO comment b2b/Federation section

- cmd/defaults.yaml
> fix: allow "org.read" and "policy.read" on ORG_USER_MANAGER

- internal/api/ui/login/external_provider_handler.go
- internal/api/ui/login/jwt_handler.go
- internal/idp/providers/azuread/azuread_test.go
- internal/idp/providers/github/github_test.go
- internal/idp/providers/gitlab/gitlab_test.go
- internal/idp/providers/google/google_test.go
- internal/idp/providers/oauth/oauth2.go
- internal/idp/providers/oauth/oauth2_test.go
- internal/idp/providers/oidc/oidc.go
- internal/idp/providers/oidc/oidc_test.go
> fix(providers): set prompt select_account again

- internal/database/postgres/config.go
uses the postgres database when connecting as admin
```[tasklist]
```
> fix(postgres): set dbname=postgres in admin mode

- proto/zitadel/object.proto
> chore: define default offset for better UX

- docs/docs/legal/support-services.md
Small editorial changes to the support services page: 
- Corrected definition of custom SLA for cloud
- Added missing links
- Formatting of self-hosting support services
- Replace CAOS with ZITADEL to avoid confusion; reference to legal entity
> docs(legal): support services editorial changes

- internal/auth/repository/eventsourcing/eventstore/auth_request.go
> fix: use correct resource owner in checkExternalUserLogin

- internal/api/grpc/idp/converter.go
- internal/api/ui/login/external_provider_handler.go
- internal/command/idp.go
- internal/command/idp_model.go
- internal/command/instance_idp.go
- internal/command/instance_idp_model.go
- internal/command/instance_idp_test.go
- internal/command/org_idp.go
- internal/command/org_idp_model.go
- internal/command/org_idp_test.go
- internal/idp/providers/oidc/oidc.go
- internal/idp/providers/oidc/session.go
- internal/query/idp_login_policy_link_test.go
- internal/query/idp_template.go
- internal/query/idp_template_test.go
- internal/query/idp_user_link_test.go
- internal/query/projection/idp_template.go
- internal/query/projection/idp_template_test.go
- internal/repository/idp/oidc.go
- internal/repository/instance/idp.go
- internal/repository/org/idp.go
- proto/zitadel/admin.proto
- proto/zitadel/idp.proto
- proto/zitadel/management.proto
> fix: use idToken for mapping when using old configs

- docs/docs/examples/login/nextjs.md
Adjusting the port number in the Next.JS docs text to match the rest of the tutorial.
> docs: fix port number in nextjs tutorial

- docs/docs/examples/introduction.mdx
> docs: Typo in SPA examples

- internal/query/idp_login_policy_link_test.go
- internal/query/projection/idp_login_policy_link.go
- internal/query/projection/idp_login_policy_link_test.go
> fix: remove instance IDPs correctly from org policies

- internal/command/project_application_saml_model.go
fixes the following panic:
```
runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xf79054]
at github.com/zitadel/zitadel/internal/command.removeAppIDFromEntityIDs ( [/home/runner/work/zitadel/zitadel/internal/command/project_application_saml_model.go:261](https://console.cloud.google.com/debug?referrer=fromlog&file=%2Fhome%2Frunner%2Fwork%2Fzitadel%2Fzitadel%2Finternal%2Fcommand%2Fproject_application_saml_model.go&line=261&project=zitadel-domains) )
```
```[tasklist]
```
> fix(saml): correct handling of remove

- console/src/app/modules/filter-events/filter-events.component.html
- console/src/app/pages/events/events.component.html
- e2e/cypress/e2e/events/events.cy.ts
- internal/query/event.go
Bug found while reviewing #5580
With this PR...
- 0 retention duration is ignored
- all events from the search result are checked
- filtering events in the console is e2e tested
```[tasklist]
```
> fix: ignore 0 retention on event search

- .github/workflows/zitadel.yml
> chore: remove duplicate step

- internal/domain/human.go
- internal/domain/human_test.go
> fix: set displayname correctly in EnsureDisplayName

- console/angular.json
> fix(console): disallow inline fonts, critical styles

- docs/docs/apis/actions/external-authentication.md
- docs/docs/concepts/features/identity-brokering.md
- docs/docs/guides/manage/console/instance-settings.mdx
- docs/docs/guides/manage/customize/behavior.md
- docs/docs/guides/solution-scenarios/configurations.mdx
- docs/sidebars.js
I've created automatic overviews for some integration sections. Makes it easier to share a link to the group of idps, tools, services etc.
Also for consistency I've moved identity brokering to concepts/features to explain the general features with links on how to manage and the guides. 
```[tasklist]
```
> docs(integrate): create automatic overviews, move brokering

- internal/api/oidc/key.go
- internal/api/saml/certificate.go
- internal/eventstore/handler/handler_projection.go
- internal/eventstore/v1/spooler/spooler.go
> fix: switch log level of failed locks to debug

- internal/api/ui/login/renderer.go
> fix: render authrequest id only if possible

- cmd/start/start.go
- internal/api/api.go
- internal/api/grpc/server/gateway.go
- internal/api/http/middleware/access_interceptor.go
- internal/api/ui/console/console.go
Reuses methods from http.AccessInterceptor to set the expired or not expired exhausted cookie with the environment.json.
> fix: set exhausted cookie with env json

- docs/sidebars.js
Before "Authenticate service users" was nested under "Access ZITADEL API's" giving the impression that SU can only be used with our APIs. In fact SU can be used for m2m and for accessing the APIs.
Moved the section up and added a link in the subsection to the main section. Also updated the description.
> docs(integrate): move authenticate service users up

- console/src/app/modules/idp-table/idp-table.component.html
- console/src/app/modules/idp-table/idp-table.component.ts
- console/src/app/services/overlay/workflows.ts
- console/src/assets/i18n/de.json
- console/src/assets/i18n/en.json
- console/src/assets/i18n/es.json
- console/src/assets/i18n/fr.json
- console/src/assets/i18n/it.json
- console/src/assets/i18n/ja.json
- console/src/assets/i18n/pl.json
- console/src/assets/i18n/zh.json
If you click on an instance IDP but the view is in the organization context, you will get a warning that the context is switched..
Partially closes #5654
> fix(console): show warn dialog when view switched to instance

- internal/api/grpc/management/user.go
- internal/command/user_machine_secret.go
- internal/command/user_machine_secret_test.go
Take the preferred login name from the query side, so that it is printed correctly in the client credential creation prompt for a machine user.
Fixes #5919
> fix: display loginname in machine client credentials

- internal/api/ui/login/external_provider_handler.go
> fix: check linked users before postAuthentication action

- console/src/app/directives/back/back.directive.ts
- console/src/app/pages/projects/apps/app-create/app-create.component.ts
- console/src/app/pages/projects/owned-projects/project-role-create/project-role-create.component.ts
- console/src/app/pages/projects/project-create/project-create.component.ts
- console/src/app/pages/users/user-create-machine/user-create-machine.component.ts
- console/src/app/pages/users/user-create/user-create.component.ts
@mffap detected in #5069 that after creating a new client and go on the back button the create app dialog starts again.
This is a video showing the current situation:
https://github.com/zitadel/zitadel/assets/30386061/4a0f8b97-38b0-4f18-8452-1328a8922924
The same behavior should apper after creating a project, a user, a machine user and a project role. As a workaround once of those elements are created I suggest adding a query param: new=true. When the back directive is applied after clicking the back button if the new param exists, a new back navigation is performed so the create dialog is not shown. Maybe is not the most elegant solution with going back twice.
This is a video showing the proposed change:
https://github.com/zitadel/zitadel/assets/30386061/57bc2855-0725-4feb-b315-49d56dd1f …
> fix: back button in detail view should not navigate to create dialog again

- internal/api/grpc/session/v2/session_integration_test.go
- internal/api/grpc/user/v2/passkey.go
- internal/api/grpc/user/v2/passkey_integration_test.go
- internal/api/grpc/user/v2/passkey_test.go
- internal/api/grpc/user/v2/u2f.go
- internal/api/grpc/user/v2/u2f_integration_test.go
- internal/api/grpc/user/v2/u2f_test.go
- internal/command/user_v2_passkey.go
- internal/command/user_v2_passkey_test.go
- internal/command/user_v2_u2f.go
- internal/command/user_v2_u2f_test.go
- internal/domain/user_v2_passkey.go
This PR implements the registration of U2F tokens in the user V2 API.
Protobuf definitions are already committed in #6017
Related #5470
> feat(v2): register user u2f

- cmd/defaults.yaml
- cmd/setup/03.go
- cmd/setup/config.go
- cmd/setup/setup.go
- cmd/setup/steps.yaml
- internal/api/grpc/system/instance_converter.go
> fix: nil pointer on create instance add machine

- internal/domain/application_oidc.go
A two-line code change as described in the title.
> fix: typo at function's name: checkApplicationType

- proto/zitadel/user/v2alpha/user_service.proto
This PR updates the summary for v2 alpha,  user u2f registration. There was a copy/paste type which we forgot to change from passkey to u2f.
> fix(v2): typo in register u2f endpoint summary

- .github/workflows/integration.yml
- cmd/defaults.yaml
- internal/api/grpc/oidc/v2/oidc.go
- internal/api/grpc/user/v2/user_integration_test.go
- internal/api/oidc/auth_request.go
- internal/api/oidc/auth_request_converter.go
- internal/api/oidc/auth_request_converter_v2.go
- internal/api/oidc/auth_request_integration_test.go
- internal/api/oidc/client.go
- internal/api/oidc/client_converter.go
- internal/api/oidc/op.go
- internal/auth/repository/eventsourcing/eventstore/auth_request.go
- internal/command/auth_request.go
- internal/command/auth_request_model.go
- internal/command/auth_request_test.go
- internal/domain/auth_request.go
- internal/integration/config/zitadel.yaml
- internal/integration/integration.go
- internal/query/projection/auth_request.go
- internal/query/projection/auth_request_test.go
- internal/repository/authrequest/auth_request.go
> fix: separate auth request v2 implementation from v1

- internal/api/grpc/oidc/v2/oidc.go
- internal/command/auth_request.go
- internal/command/auth_request_model.go
- internal/command/auth_request_test.go
> fix: check the authRequest login client in command

- docs/docs/legal/privacy-policy.mdx
The legal form of our EU representative has changed from UG to GmbH. With this change we update the address in our privacy policy.
> docs(legal): update address of EU representative

- cmd/defaults.yaml
- go.mod
- go.sum
- internal/crypto/passwap.go
- internal/crypto/passwap_test.go
This change brings pbkdf2 support for password hashing and verification.
Related to:
- https://github.com/zitadel/zitadel/issues/4157
- https://github.com/zitadel/passwap/issues/1
> feat(crypto): add pbkdf2 support

- internal/notification/handlers/telemetry_pusher.go
ConcurrentInstances is not customizable by configuration as it's missing here:
https://github.com/zitadel/zitadel/blob/main/internal/query/projection/projection.go#L174-L192
> fix: project telemetry once for all instances

- internal/api/grpc/management/user_integration_test.go
- internal/eventstore/handler/handler_projection.go
Even if there are no events to trigger, we should reset the request timestamp for `AS OF SYSTEM TIME` as the getting of
events might be locked by the subscription. This leads to the illusion the project is up to date.
Closes #5808
> fix: always update the timestamp in trigger

- internal/api/ui/login/external_provider_handler.go
- internal/command/idp_intent.go
- internal/command/idp_intent_test.go
Issue reported by a customer, that after migrating to 2.31.5 the access_token was not provided in the postAuthentication action.
> fix: provide tokens in azuread idp session

- internal/api/grpc/session/v2/session.go
- internal/api/grpc/session/v2/session_integration_test.go
- internal/api/grpc/session/v2/session_test.go
- internal/command/session.go
- internal/command/session_model.go
- internal/command/session_test.go
- internal/integration/integration.go
- internal/query/projection/session.go
- internal/query/projection/session_test.go
- internal/query/session.go
- internal/query/sessions_test.go
- internal/repository/session/eventstore.go
- internal/repository/session/session.go
- proto/zitadel/session/v2alpha/session.proto
- proto/zitadel/session/v2alpha/session_service.proto
This change implements Time-based One-Time Password (TOTP) on the v2alpha session API.
Closes #5477
> feat(api/v2): implement TOTP session check

- cmd/defaults.yaml
The ExternalDomain and ExternalPort config environmental variable settings are incorrectly listed - both have an underscore after `EXTERNAL`, which is not needed
> docs: fix external domain and external key env var names

- internal/api/grpc/management/user_integration_test.go
- internal/authz/repository/eventsourcing/eventstore/token_verifier.go
- internal/eventstore/handler/handler_projection.go
> fix: Cherry pick session

- internal/api/ui/login/external_provider_handler.go
bug reported in [Discord](https://discord.com/channels/927474939156643850/1135929532394766397) where metadata set in action would not be applied when the user is created at the same time
> fix: handle metadata from post authentication on auto creation

- docs/docs/guides/integrate/token-introspection/basic-auth.mdx
This just adds syntax highlighting to the code blocks on base-auth.mdx, which is this [page](https://zitadel.com/docs/guides/integrate/token-introspection/basic-auth) in the docs.
> docs: Update basic-auth.mdx - add syntax highlighting to code blocks

- .github/workflows/console.yml
- README.md
excludes the `dist` folder when building the cache-key, so we're able to get a primary cache hit and do not need to rebuild console everytime even if there aren't any changes
> chore(workflow): exclude console dist folder from cache

- internal/command/org_policy_login.go
- internal/command/org_policy_login_model.go
- internal/command/org_policy_login_test.go
> fix: change force local mfa on org

- docs/docs/guides/integrate/login-ui/external-login.mdx
- proto/zitadel/user/v2alpha/user_service.proto
Fixes #6436 by removing the `/start` from the REST path of the StartIdentityProviderIntent and therefore ensuring the correct binding again.
> fix: rest path for StartIdentityProviderIntent

- internal/authz/repository/eventsourcing/eventstore/token_verifier.go
There was a comented TODO in authMethodsFromSession, resulting in users not getting a confirmed MFA when using password+TOTP in session v2 API.
Bug was verified on my local instance and also confirmed fixed after the change.
Fixes #6450
> fix(sessions/v2): resolve tOTP TODO for Auth Methods

- internal/eventstore/eventstore.go
- internal/eventstore/handler/handler_projection.go
Instances are cached and requested based on the `projections.RequeueEvery` configuration
> fix(eventstore): cache instances

- internal/api/ui/login/init_user_handler.go
- internal/api/ui/login/static/templates/change_password.html
- internal/api/ui/login/static/templates/init_user.html
- internal/api/ui/login/static/templates/password.html
A customer with 'Hide Loginname suffix' enabled reported, that the browser will try to save the suffixed login.
> fix: improve autofill values

- internal/admin/repository/eventsourcing/handler/styling.go
- [ X] I am happy with the code
The colors configured in the instance resp. project settings for the font were not used for labels. See #5505 for more infos.
> fix(account-selection): use font color as color for labels

- cmd/defaults.yaml
Options that are completely commented-out in the yaml file(s) do not get parsed from the envionment variables.
This was also to the case for the
`ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_VERIFIERS` option.
This change just uncomments the yaml option, so that users
can use the envorment variable to set a list of verifiers they wish to
enable.
I've tested the fix locally by disabling `Verifiers` in my yaml and with docker compose where
```
environment:
ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_VERIFIERS: pbkdf2
```
Imported a pbkdf2 password user and logged in succesfully.
> fix(defaults): uncomment Verifiers

- console/src/app/modules/providers/provider-apple/provider-apple.component.ts
- docs/docs/guides/integrate/identity-providers/apple.mdx
- [ X ] I am happy with the code
- [ X ] Short description of the feature/issue is added in the pr description
- [ X ] PR is linked to the corresponding user story
- [ X ] Acceptance criteria are met
- [ X ] All open todos and follow ups are defined in a new ticket and justified
- [ X ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ X ] No debug or dead code
- [ X ] My code has no repetitions
- [ X ] Critical parts are tested automatically
- [ X ] Where possible E2E tests are implemented
- [ X ] Documentation/examples are up-to-date
- [ X ] All non-functional requirements are met
- [ X ] Functionality of the acceptance criteria is checked manually on the dev system.
When adding Apple as identity provider, there was an error depending on the …
> fix: apple idp configuration

- internal/auth/repository/eventsourcing/eventstore/auth_request.go
- internal/auth/repository/eventsourcing/eventstore/auth_request_test.go
- internal/auth/repository/eventsourcing/repository.go
- internal/auth_request/repository/mock/repository.mock.go
closes https://github.com/zitadel/zitadel/issues/6574
> fix: only reuse active session and use correct policies (from user org)

- internal/authz/repository/eventsourcing/eventstore/token_verifier.go
a customer reported, that he would randomly get "APP-BxUSiL: invalid token" errors.
it seems that when querying the token (call _1_), it's not yet present in the database, therefore the latest token sequence will be loaded (call _2_). in some cases, the sequence might have been updated in the meantime (after call _1_), resulting in the loss of events for the current check.
to fix potential loss, this PR changes the order of the both calls and always load the sequence (previously _2_) first and only us that if the token was not found (previously _1_)
> fix: ensure no events are skipped on token check

- internal/api/authz/context.go
There were many request in discord from developers, that send an origin header either when using a PAT or some other service user based token. Current checks would deny such requests.
With this PR, we will only check origin for tokens issued to users through apps (Code / Implicit Flow) and ignore on tokens for service accounts (Client Credentials / JWT Profile / PAT)
> fix: reduce origin check to tokens issued through code and implicit flow

- proto/buf.yaml
- proto/zitadel/feature.proto
- proto/zitadel/system.proto
following up the short discussion during the sprint review, i've changed the int to a enum
> fix: use enum for instance feature in system api

- internal/crypto/passwap.go
- internal/crypto/passwap_test.go
In `defaults.yam` we specify bcrypt with a default `Cost` parameter. When a hasher that does not take a `Cost` parameter is used, (like Argon2), the `Cost` parameter remains present in the config map. This because viper is merging the config map recursively. During startup we let the decoder error on unused keys. Hence, it is impossible to start zitadel with an argon2 hasher.
To reproduce, start a released or `main` version of zitadel (locally) with the following in a config file (not `defaults.yaml`):
```yaml
SystemDefaults:
PasswordHasher:
Hasher:
Algorithm: "argon2id"
Time: 1
Memory: 65536
Threads: 4
```
Zitadel will fail to start with an error
This PR fixes the behavior by allowing unused keys.
Reported through discord: https://discord.com/channels/927474939156643850/115317940116968660 …
> fix: allow unused keys in hasher config

- cmd/setup/steps.yaml
The yaml schema has a `Machine` object nested inside another one, which was improperly represented in the corresponding environment variable.
> docs: fix environment variable name for steps

- internal/api/http/middleware/origin_interceptor.go
- internal/api/http/middleware/origin_interceptor_test.go
The PR fixes issues introduced with #6628 and reported [on Discord](https://discord.com/channels/927474939156643850/1163733984224747582)
1. To construct a requests origin, reading the header values falls back to other headers by properties, not by existence of headers. Like this, for example the host can be defined with the *Forwarded* header and the protocol can be defined with the *X-Forwarded-Proto* header or it can also be omitted.
3. As proxies should [append their values to the forwarded header(s)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded#syntax), we now read the **first** value to get the **oldest** value instead of the last most recent value.
2. As non-default ports should be included in the *Forwarded* directive *host*, in the *X-Forwarded-Host* header …
> fix: origin from proxies

- internal/command/existing_label_policies_model.go
- internal/command/instance_domain_model.go
- internal/command/instance_model.go
- internal/command/instance_test.go
- internal/command/org_domain_model.go
- internal/command/preparation/command.go
- internal/command/quota_model.go
- internal/command/system_model.go
- internal/command/unique_constraints_model.go
- internal/eventstore/eventstore.go
- internal/eventstore/eventstore_test.go
- internal/eventstore/repository/mock/repository.mock.go
- internal/eventstore/repository/mock/repository.mock.impl.go
- internal/eventstore/repository/sql/crdb.go
- internal/eventstore/repository/sql/query.go
- internal/eventstore/repository/sql/query_test.go
- internal/eventstore/search_query.go
Directly reduce each event obtained from a sql.Rows scan, so that we do not have to allocate all events in a slice.
We can can further optimize this solution by:
1. Port all functions that use `eventstore.Filter()` to `eventstore.FilterToReducer()` or `eventstore.FilterToQueryReducer()` . Currently there are 161 uses in Zitadel and most of them through the `preparation` package.
2. Refactor the `eventstore.reducer` interface so that every Event can be directly reduced, without calling `AppendEvents` first. This means that for all implementations we can get merge the `AppendEvents` with `Reduce` and can get rid of each `for` loop.
3. See if we can get rid of the `Eventstore.interceptorMutex`. It seems only needed for parallel tasks during startup and the map doesn't change during requests. …
> fix(eventstore): prevent allocation of filtered events

- README.md
- deploy/knative/cockroachdb-statefulset-single-node.yaml
- docs/docs/self-hosting/deploy/docker-compose-sa.yaml
- docs/docs/self-hosting/deploy/docker-compose.yaml
- docs/docs/self-hosting/deploy/linux.mdx
- docs/docs/self-hosting/deploy/loadbalancing-example/docker-compose.yaml
- docs/docs/self-hosting/deploy/macos.mdx
- docs/docs/self-hosting/manage/configure/docker-compose.yaml
- e2e/config/localhost/docker-compose.yaml
ZITADEL always is tested agains the latest stable tag of cockroachdb. We should also advise our users to use this tag
> docs: replace fix cockroachdb version with latest stable

- internal/eventstore/handler/v2/handler.go
- internal/query/app.go
- internal/query/auth_request.go
- internal/query/authn_key.go
- internal/query/domain_policy.go
- internal/query/idp.go
- internal/query/idp_template.go
- internal/query/instance.go
- internal/query/lockout_policy.go
- internal/query/login_policy.go
- internal/query/notification_policy.go
- internal/query/org.go
- internal/query/org_metadata.go
- internal/query/password_age_policy.go
- internal/query/password_complexity_policy.go
- internal/query/privacy_policy.go
- internal/query/project.go
- internal/query/project_grant.go
- internal/query/project_role.go
- internal/query/session.go
- internal/query/user.go
- internal/query/user_grant.go
- internal/query/user_metadata.go
- internal/query/user_personal_access_token.go
Does not trace each `handler.Trigger`. Trigger is now only traced if the trigger happens in the `query`-package
> chore: correct tracing of trigger function

- internal/eventstore/v3/eventstore.go
- internal/eventstore/v3/unique_constraints.go
Version 2.39.0 silently introduced a breaking change to the error type returned when pushing is not possible because of a unique constraint error, the previous error type is now returned.
Postgres and Cockroach return unique constraint errors in different formats. ZITADEL now is able to handle both formats.
> fix(eventstore): differentiate unique constraint error

- internal/auth/repository/eventsourcing/eventstore/auth_request.go
Closes #6731 , changes used attribute for display_name in the user link from DisplayName to PreferredUsername.
> fix: use username with external idp linking

- internal/repository/deviceauth/device_auth.go
- internal/repository/feature/feature.go
- internal/repository/flow/flow.go
- internal/repository/policy/policy_login_identity_provider.go
A customer reported to support, that on some organisation, the configured action flows would not be executed / listed in the UI.
This PR fixes the serialization of the Flow events as well as others, by omitting the BaseEvent data in the payload. The data was never meant to be part of the payload. With the eventstore optimizations (Version [2.39.0](https://github.com/zitadel/zitadel/releases/tag/v2.39.0), resp.  [PR #5940](https://github.com/zitadel/zitadel/pull/5940)) EventMappers were changed to no longer use `json.Unmarshal` the event data directly but rather use the provided `Unmarshal` function on the passed event. This resulted in an overwrite of the `baseEvent`
https://github.com/zitadel/zitadel/pull/5940/files#diff-834871e35a5a7fad01386720d0583439c94e97b26421a44398a3ae7a1e200e2dL50- …
> fix: payload (de)serialization of some events

- internal/api/grpc/admin/event.go
- internal/api/grpc/auth/user.go
- internal/eventstore/repository/search_query.go
- internal/eventstore/repository/sql/query.go
- internal/eventstore/search_query.go
- internal/query/event.go
- proto/zitadel/admin.proto
Reported on [Discord](https://discord.com/channels/927474939156643850/1169210538157412452)
Fixes a bug introduced with #6744: If an audit log retention was configured, it overwrote the event queries creation_date filter.
Fixes the described behavior of the creation_date filter in relation to the asc ordering property.
> fix: creation date argument in search events filters

- internal/api/oidc/op.go
- internal/api/oidc/server.go
- internal/api/oidc/server_test.go
This PR closes #6810 by using the configured signing key algorithm for the discovery configuration instead of calling the database.
> perf(oidc): remove db call for discovery configuration

- internal/query/instance.go
- internal/query/instance_test.go
Some users reported multiple intances that were returned in the dashboard.
This was caused by the filter-sub query, where each domain results in an instance ID in the join so multiple domains on an instance returns that instance multiple times. The second join then quantifies the problem.
This PR fixes that by using a `distinct` clause on the filter table.
> fix(system-api): use distinct in intances filter query

- internal/api/ui/login/login.go
Raised by multiple people (https://discord.com/channels/927474939156643850/1172633019060858890, https://github.com/zitadel/zitadel/discussions/6911, ...) that the CSRF cookie will always set a SameSite `Lax` cookie even when the `iframe allowed` option was activated in the `Security Settings` of the instance.
This PR adds a missing check and changes the default `Lax` mode to `None` if the option mentioned above is active.
> fix: set samesite mode for CSRF cookie based on security policy

- internal/command/session.go
- internal/command/session_webauhtn.go
closes #6784 by removing the resource owner restriction of a user when creating webauthn challenges.
https://github.com/zitadel/zitadel/issues/6623 will further improve the resource owner handling in the session.
> fix: allow webauthn checks for users of other orgs

- internal/auth/repository/eventsourcing/handler/token.go
- internal/project/repository/eventsourcing/model/project.go
- internal/project/repository/eventsourcing/model/project_test.go
A Customer reported, that after some time a PAT would just stop working. It was discovered, that project deactivations and removals would lead to PAT invalidations.
This PR fixes the event handling of project deactivate and remove events (unmarshalling) and further checks that no empty ids are passed to the handler afterwards.
> fix: handle project deactivate and remove correctly on tokens

- internal/api/oidc/client_integration_test.go
- internal/integration/client.go
- internal/query/embed/userinfo_by_id.sql
- internal/query/testdata/userinfo_human.json
- internal/query/testdata/userinfo_human_grants.json
- internal/query/testdata/userinfo_human_no_md.json
- internal/query/testdata/userinfo_machine.json
- internal/query/userinfo_test.go
during QA I found some user info and org ID was missing.
This change adds those missing fields.
Included the missing fields to the integration test as well.
> fix(oidc): add missing fields to introspection

- CONTRIBUTING.md
- internal/integration/config/docker-compose.yaml
Let's locally test against the latest DB versions.
Like we do in the Pipelines.
> test(postgres): always test against latest release

- .github/ISSUE_TEMPLATE/BUG_REPORT.yaml
Sometimes we get bug reports that are only reproducible when zitadel is running against a certain database. This change adds database related questions to the issue template, as it is something people don't tend to describe in the detail fields.
> chore: add database questions to bug report template

- internal/api/ui/login/static/templates/register.html
In #6491 @kbumsik noted that there was a missing ← left arrow it we try to register a user. This PR replaces the back button (login) in the bottom with the common left arrow.
Closes #6491
> fix: replace back button with <- in user register

- internal/query/projection/restrictions.go
- internal/query/projection/restrictions_test.go
- internal/query/restrictions_test.go
updates the version of the `projections.restrictions` table, so the new column will be added
> fix: projection version of restrictions

- cmd/setup/18.go
- cmd/setup/18.sql
- cmd/setup/config.go
- cmd/setup/setup.go
- internal/api/grpc/management/user.go
- internal/api/grpc/session/v2/session.go
- internal/api/grpc/session/v2/session_test.go
- internal/api/oidc/client.go
- internal/api/saml/storage.go
- internal/api/ui/login/init_password_handler.go
- internal/api/ui/login/password_reset_handler.go
- internal/auth/repository/eventsourcing/view/user.go
- internal/notification/handlers/mock/queries.mock.go
- internal/notification/handlers/queries.go
- internal/query/projection/login_name.go
- internal/query/user.go
- internal/query/user_by_id.sql
- internal/query/user_by_login_name.sql
- internal/query/user_notify_by_id.sql
- internal/query/user_notify_by_login_name.sql
back port of  #6537 for 2.42.x
> fix(query): user performance

- docs/docs/self-hosting/deploy/linux.mdx
Thanks to @candlerb report, I've updated docs changing the bash snippet to download, unpack and copy the binary.
As uname -m returns x86_64, I've used this suggested case to get amd64 or arm64:  https://unix.stackexchange.com/a/751330
I've tested this bash script in my Ubuntu 22.04.3 LTS machine.
Closes #7067
> docs(linux): fix download and unpack release bash snippet

- cmd/defaults.yaml
- internal/eventstore/handler/v2/handler.go
We discovered, that esp. after a setup, latest events might be older than the default `HandleActiveInstances`, which can cause incomplete projections.
As most systems only have a single instance or very few instances, the default of `HandleActiveInstances` will be changed to 0. If set to 0, all instances will be considered active and handled for the projection.
It was currently intended, that if a projection was initialized, the projection should not directly start after the start of the binary, but should start a new cycle after the configured `RequeueEvery`. Due to a bug it would always start immediately even if already initialized. This PR fixes the bug and further randomizes the start time of the projections to reduce the load on startup.
It further removes the unhandled …
> fix(projections): handle every instance by default and randomize start

- internal/eventstore/handler/v2/state.go
- internal/eventstore/handler/v2/statement.go
- internal/eventstore/repository/search_query.go
- internal/eventstore/search_query.go
For future migrations positions can get bigger and needs a higher offset in the handler. The datatype of the offset is changed to an uint32
> fix(handler): allow uint32 offset for migration scenarios

- internal/api/oidc/auth_request.go
- internal/command/user_human_refresh_token.go
Due to a mis-alignment of OIDC interface and concrete implementations in zitadel, requesting a refresh token for device authorization would fail.
This change adds the possibility to to use the op.IDTokenRequest directly.
Also, the UserAgentID is dropped as required parameter, as devices do not have a user agent.
> fix(oidc): refresh token for device authorization

- internal/api/grpc/oidc/v2/oidc_integration_test.go
- internal/api/oidc/client_converter.go
- internal/api/oidc/client_integration_test.go
- internal/api/oidc/oidc_integration_test.go
- internal/integration/oidc.go
The PR implements glob pattern support for redirects, which allows for more flexible and powerful URL redirection based on wildcard patterns.
fixes #5110
> feat: allow glob redirects

- internal/api/oidc/client_integration_test.go
- internal/api/oidc/introspect.go
- internal/integration/oidc.go
This fixes a nil pointer panic when client basic auth is attempted on a client without secret in introspection.
Extra integration tests are provided to test the corner cases.
> fix(oidc): nil check for client secret

- cmd/setup/19.go
- cmd/setup/19.sql
- cmd/setup/config.go
- cmd/setup/setup.go
- internal/eventstore/v3/sequence.go
- internal/eventstore/v3/sequence_test.go
- internal/eventstore/v3/sequences_query.sql
Creates a new index on eventstore.events2 table which is used to query current sequences of aggregates
Changes the query of current states to drastially reduce latency on bigger datasets
> fix(eventstore): increase performance on push

- .github/workflows/build.yml
- .github/workflows/version.yml
Allows to push sha versions to docker registry on workflow dispatch
> ci: publish sha to docker registry

- .gitignore
- internal/database/database.go
- internal/query/search_query.go
- internal/query/search_query_test.go
- internal/view/repository/query.go
- internal/view/repository/query_test.go
* fix(query): escape like wildcards
* test: search query wildcards
* add do nothing
> fix(query): escape wildcards in text search (#7131)

- internal/authz/repository/eventsourcing/view/token.go
- internal/eventstore/handler/v2/handler.go
While investigating an issue on production (missing loginnames on a user in the auth projection), we found out that the error is overwritten and thus the maxFailureCount gets ignored.
> fix: correctly respect maxFailureCount

- docs/docs/legal/service-description/support-services.mdx
With the last pricing change we removed professional support from the free plan. Customers in the free plan should turn to community support for help.
We had however a response time stated in the free plan, which is an error carried over from the previous plans. 
This PR removes 'best effort'. Also it mentiones in the community support section that time critical issues should be reported through professional support, if eligible.
> docs(legal): clarify response time in free plan

- docs/docs/apis/actions/complement-token.md
During a TAM session, it was noted that it is not clear to customers that the `pre userinfo creation` is not only executed for the userinfo endpoint, but among others also for the id_token
> docs(complement token): clarify when `pre userinfo creation` is executed

- cmd/start/start.go
- internal/api/http/middleware/origin_interceptor.go
- internal/api/http/middleware/origin_interceptor_test.go
This PR ensures that if neither a Forwarded nor an X-Forwarded-Proto header is sent in requests to ZITADEL, links in messages like Email verifications use https if ExternalSecure is true or http if ExternalSecure is false.
Before this PR, the requests TLS config was used, which did not make sense. The TLS config does not tell if a client in front of a proxy used http or https. ExternalSecure does.
> fix(origin): fall back to ExternalSecure

- .github/workflows/build.yml
- .github/workflows/core-unit-test.yml
- internal/eventstore/local_crdb_test.go
- internal/eventstore/repository/sql/local_crdb_test.go
Cockroach created new versions (23.2.0 and 23.1.14), which are not yet publicly available, but the testserver used in the eventstore unit tests, checks for the latests stable version (which returns 23.2.0).
This PR allows to specify a specific version to use in the pipeline for unit tests and sets it currently to 23.1.13.
> chore: pin crdb version for unit tests

- docs/src/components/subprocessors.jsx
We have discontinued Cockroach Labs as subprocessor by moving managed database services to Google LLC. Clickhouse only used briefly and replaced by Google LLC for datawarehouse services. We have introduced Hubspot for handling customer management, marketing automation, and support services. Hubspot will not receive end-user data.
All existing customers will be informed.
> chore: remove cockroach, clickhouse and add hubspot from third party sub-processors

- internal/api/grpc/auth/password.go
- internal/api/grpc/user/v2/password.go
- internal/api/ui/login/change_password_handler.go
- internal/api/ui/login/init_password_handler.go
- internal/api/ui/login/init_user_handler.go
- internal/command/user_human_init.go
- internal/command/user_human_init_test.go
- internal/command/user_human_password.go
- internal/command/user_human_password_test.go
- internal/command/user_v2_human.go
While testing the user sessions improvements (https://github.com/zitadel/zitadel/pull/7199) i noticed, that the `user agent id` was never set on the password changed event.
This apparently was accidentally changed in the the user v2 PR (https://github.com/zitadel/zitadel/pull/6996) released in 2.43.
This PR adds the information again where available (login handlers). This way user must not reenter the password during the login process, e.g. when changing the password.
> fix: set userAgentID in password change event if available

- internal/api/ui/login/login.go
- internal/idp/providers/saml/saml.go
[A customer noted](https://github.com/zitadel/zitadel/discussions/7286#discussioncomment-8340193), that the auto form submit for POST binding was blocked due to the CSP. While testing we also noticed, that the configured binding is not used, but rather the (first) from the metadata.
This PR therefore adds the hash of the form submit JS to the CSP of the login UI and further makes sure to set the binding if set.
> fix: use configured binding on SAML IDPs and make sure CSP doesn't block POST binding

- internal/notification/messages/email.go
A customer had an issue where the email was received by the end-user. They noted that the user's SMTP provider did not support `SMTPUTF8`.
This PR changes the encoding for the subject from "Q" to "B" (base64).
> fix(smtp): support UTF-8 subjects

- cmd/defaults.yaml
- internal/eventstore/config.go
- internal/eventstore/eventstore.go
- internal/eventstore/eventstore_test.go
This change retries pushing of events if there is an unique constraint violation on the primary key of the eventstore.
Because we do a `SELECT .. FOR UPDATE` to establish the latest sequence number, many concurent pushes on the same aggregate ID might result in duplicate sequence numbers and the push will fail. We will now retry the complete push transaction, only if the error was created by the specific constraint `events2_pkey` with SQL state `23505`.
A `MaxRetries` field is added to the event store config to prevent endless retries is the context timeout is not set. `defaults.yaml` sets the value to 5. As during reproduction of the issue, the bug seems to occur a few times out of 1000 requests, 5 retries should be more than enough. If the unique constraint error still exists after 5 …
> fix(eventstore): retry push on primary key sequence violation

- docs/docs/guides/integrate/login-ui/external-login.mdx
- docs/docs/guides/integrate/login-ui/logout.mdx
- docs/docs/guides/integrate/login-ui/mfa.mdx
- docs/docs/guides/integrate/login-ui/oidc-standard.mdx
- docs/docs/guides/integrate/login-ui/passkey.mdx
- docs/docs/guides/integrate/login-ui/password-reset.mdx
- docs/docs/guides/integrate/login-ui/select-account.mdx
- docs/docs/guides/integrate/login-ui/username-password.mdx
- proto/zitadel/session/v2beta/session_service.proto
The headings for the custom login UI are confusing. "Passkeys in ZITADEL" means in fact how to use passkeys when building a custom login UI with ZITADEL. The PR updates the headings to reflect the actual intent. 
Also x-ref from Session API to the guides.
> docs:  update headings for custom login ui

- .github/workflows/issues.yml
- cmd/defaults.yaml
- cmd/setup/steps.yaml
- docs/docs/self-hosting/manage/configure/configure.mdx
Closes https://github.com/zitadel/zitadel-charts/issues/110
Makes it clearer how to use the DefaultInstance and the FirstInstance sections.
Especially for configuring a ZITADEL Helm chart, where we don't differentiate between setup and runtime config, this helps understanding the concepts.
> docs: describe DefaultInstance vs FirstInstance

- internal/api/grpc/admin/event.go
- internal/api/grpc/admin/event_test.go
- internal/eventstore/eventstore.go
To optimise response times and database load aggregate types are added to the query if needed and not defined the request payload.
> perf(ListEvents): add aggregate types to filter if not set

- docs/docs/examples/login/go.md
The example was falsely stating that the key was used for a json private key, obtained from zitadel.
This lead to confusion as we do not use JWT assertion in the example, but PKCE.
Instead, the key is used for symmetric encryption.
https://stackoverflow.com/questions/78080163/zitadel-example-go-webapp-encryption-key/78087242#78087242
> docs: correct usage of key parameter in go login example

- docs/docs/self-hosting/deploy/loadbalancing-example/loadbalancing-example.mdx
- docs/docs/self-hosting/manage/configure/_compose.mdx
- docs/docs/self-hosting/manage/configure/_linuxunix.mdx
Setting a randomly generated masterkey as environment variable is bad, as this value is lost as soon as the environment is shut down. Therefore, we should not propose to do so in our docs.
This was reported on Discord: https://discord.com/channels/927474939156643850/927866013545025566/1213157574569107497
> docs: don't propose setting a random masterkey to env

- internal/query/instance_by_domain.sql
On zitadel cloud we noticed an increase in database CPU usage and slightly higher response times.
By analyzes we found that the instance by domain query was wrongly joining all instance_feature rows against all instances.
This PR adds an additional CTE to limit the join set to only the features that apply to the found instance.
The query was introduced with https://github.com/zitadel/zitadel/pull/7356 and part of the v2.47 release.
> fix(query): optimize instance by domain query

- console/angular.json
Developers noted that the size of the ZITADEL image / binary suddenly increased by a lot.
This was due to the copied images from docs to include the frameworks in console.
This PR changes the path to use the frameworks folder only.
> refactor: copy only required frameworks icons from docs in console

- internal/api/ui/login/mfa_init_verify_handler.go
- internal/api/ui/login/renderer.go
Customers reported, that the QR Code for the TOTP setup was not rendered anymore, but rather plain HTML was displayed.
This was due to the recent change to sanitize the HTML of the login pages. This PR explicitly switches the `QrCode` field of the `totpData` from `string` to `template.HTML` to allow the rendering again. 
closes #7542
> fix: rendering of TOTP QR code

- internal/renderer/renderer.go
When we fixed the template rendering to prevent HTML injection by queries, this changed also custom texts in the login UI, which include HTML. These are now rendered as raw strings.
This PR changes the behaviour back for custom texts to also render HTML.
To do so, the translation function (used to provide the texts in the login UI) returns now a `template.HTML` instead of a `string`.
closes #7556
> fix(login): (re)allow HTML in custom login texts

- docs/docs/apis/actions/external-authentication.md
- internal/api/ui/login/custom_action.go
External authentication actions now provide `ctx.org.getMetadata()`-method
closes https://github.com/zitadel/zitadel/issues/7482
> feat(actions): `ctx.org.getMetadata()` in external authentication

- internal/query/embed/userinfo_by_id.sql
- internal/query/projection/user_grant.go
- internal/query/projection/user_grant_test.go
- internal/query/user_grant_test.go
Correct resourceowner of usergrant in reduce function and create new projection to fill everything.
> fix: fill resourceowner of project into usergrant projection

- internal/api/grpc/auth/metadata_converter.go
- internal/api/grpc/management/org_converter.go
- internal/api/grpc/management/user_converter.go
- internal/api/grpc/metadata/metadata.go
Corrects the mapping of metadata queries.
> fix(api): correct mapping of metadata queries

- .github/workflows/release.yml
Triggers the workflow in github.com/zitadel/homebrew-tap to update the versions of the tap
closes https://github.com/zitadel/zitadel/issues/6385
> chore: trigger update homebrew tap on latest release

- docs/docs/apis/actions/complement-token.md
- internal/api/oidc/client.go
- internal/api/oidc/userinfo.go
This PR prevents actions to use any claims with a prefix of `urn:zitadel:iam`, which could lead to possible security vulnerabilities.
> fix: prevent custom urn:zitadel:iam claims

- go.mod
- go.sum
- internal/api/assets/asset.go
With this PR, the mime type of an uploaded asset is no longer taken from the content-type header, but rather detected by the assets itself (using the binary header) to prevent content type spoofing for possible attacks.
> fix: detect mime type of uploaded asset

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/e2e.yml
This PR changes the pipeline to stop the `ZITADEL CI/CD` and `Code Scanning` workflows is a new workflow is started, e.g. after new changes or remerge of main. Additionally e2e tests now run on the GH public runners again, since it does not make any difference in speed.
> chore(workflow): stop previous GH action pipeline on new changes and move back to public runners

- internal/authz/repository/eventsourcing/eventstore/token_verifier.go
Fixes a potential panic in `verifyAccessTokenV1` logic if there is an error returned from the repo instead of a token
> fix: check error before using token

- docs/docs/apis/openidoauth/endpoints.mdx
- docs/docs/guides/integrate/token-exchange.mdx
This change adds an info box to the token exchange documentation, informing the reader of the beta state of the feature and how to enable it.
> docs(oidc): token exchange beta feature info

- internal/api/oidc/auth_request.go
- internal/api/oidc/device_auth.go
- internal/command/device_auth.go
- internal/command/device_auth_test.go
- internal/domain/request.go
- internal/query/device_auth.go
- internal/query/device_auth_model.go
- internal/query/device_auth_test.go
- internal/query/projection/device_auth.go
- internal/repository/deviceauth/device_auth.go
This change in device authorization adds the ability to extend the audience based on the project  IDs, using the [reserved scope](https://zitadel.com/docs/apis/openidoauth/scopes#reserved-scopes):
```
urn:zitadel:iam:org:project:id:{projectid}:aud
```
This unifies behavior with "regular" auth requests.
Closes https://github.com/zitadel/oidc/issues/425
As there a no integration tests for device auth, I've tested it manually using the OIDC client example:
```bash
export ISSUER="http://localhost:9000" CLIENT_ID="257793310637228036@tests" SCOPES="email profile openid 	urn:zitadel:iam:org:project:id:259254020357488642:aud urn:zitadel:iam:org:project:id:259254317079330818:aud"
go run ./example/client/device
```
With the returned opaque access token I called introspection:
```bash
curl -L -X …
```
> feat(oidc): allow additional audience based on scope in device auth

- docs/vercel.json
Slug to the service provider introduction page has changed.
> docs: redirect identity providers introduction

- internal/crypto/database/database.go
- internal/database/database.go
- internal/eventstore/handler/v2/handler.go
- internal/eventstore/v3/push.go
- internal/query/current_state.go
This changes adds a span around most db.BeginTx calls so we can get tracings about the connection pool acquire process.
This might help us pinpoint why sometimes some query package traces show longer execution times, while this was not reflected on database side execution times.
> fix(db): wrap BeginTx in spans to get acquire metrics

- docs/docs/guides/integrate/service-users/private-key-jwt.md
adjust incomplete, outdated and incorrect parts of the python example.
> docs(guides/integrate/service-users/private-key-jwt):

- .github/workflows/e2e.yml
Since moving the e2e tests to the GH runners, they randomly fail, which seems to relate the performance of the runners.
So as of now, the easiest solution is to just move them back to non standard runners.
> chore(workflow): run e2e on non standard runners

- e2e/cypress.config.ts
- internal/idp/providers/oidc/session.go
- internal/idp/providers/oidc/session_test.go
This change prevents the call of the Userinfo endpoint of a OIDC IDP if the IDP is configured to use the ID token for user information instead.
A unit test has been added to confirm the corrected behavior.
Closes #7373
> fix(idp): do not call userinfo when mapping from ID token is configured

- docs/docs/guides/migrate/sources/keycloak.md
- internal/api/ui/login/static/templates/register_option.html
Solves #7456 . Given an admin had configured at least one external IdP, when a user clicked on the Register button to register as a new user, the user would be redirected to the Register Options page. However, while clicking on the back arrow returns the user back to the original page to either log in or register, clicking on the Login page redirects to the default instance page, since the authRequestId is not included as a param.
Instead, it should redirect to the correct login page accordingly.
The changes add the authRequestID within the href of the Login button as well.
https://github.com/zitadel/zitadel/assets/68676914/cec4e09f-634a-48cc-bf41-019d531c7245
> fix: Update url to redirect to name change url

- internal/api/oidc/token_exchange_integration_test.go
- internal/command/user_human_refresh_token.go
A customer noticed that on token refresh, no new refresh token was returned. This PR corrects this behaviour (accidentally changed in 2.49.0)  and returns the refresh_token again.
> fix(oidc): correctly return new refresh token on refresh token grant

- docs/docs/legal/service-description/cloud-service-description.md
Customers requested more information around shared responsibilities in ZITADEL Cloud vs. self-hosted. The main point is mainly the responsibilities around threat detection, DDoS prevention etc. 
With this PR we add some more information to the service description, making those responsibilities more explicit.
> docs(legal): add responsibilities in service description

- internal/api/authz/session_token.go
- internal/api/oidc/auth_request.go
- internal/api/oidc/error.go
- internal/command/oidc_session.go
- internal/domain/refresh_token.go
We've recently noticed an increased amount of 500: internal server error status returns on zitadel cloud.
The source of these errors appear to be erroneous input in fields that are supposed to be bas64 formatted.
```bash
curl --request POST \
--url http://localhost:9000/oauth/v2/token \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data 'grant_type=refresh_token' \
--data 'refresh_token&refresh_token=xxxxxxxxx' \
--data 'client_id=257790446061813762@tests' | jq
```
Reponse:
```json
{
"error": "server_error",
"error_description": "Errors.Internal"
}
```
Printed zitadel logs:
```
time=2024-04-08T20:09:41.168Z level=ERROR msg="request error" oidc_error.parent="ID=OIDC-AhX2u Message=Errors.Internal Parent=(illegal base64 data at input byte 8)" …
```
> fix(oidc): return bad request for base64 errors

- internal/crypto/crypto.go
- internal/crypto/crypto_test.go
- internal/static/i18n/bg.yaml
- internal/static/i18n/cs.yaml
- internal/static/i18n/de.yaml
- internal/static/i18n/en.yaml
- internal/static/i18n/es.yaml
- internal/static/i18n/fr.yaml
- internal/static/i18n/it.yaml
- internal/static/i18n/ja.yaml
- internal/static/i18n/mk.yaml
- internal/static/i18n/nl.yaml
- internal/static/i18n/pl.yaml
- internal/static/i18n/pt.yaml
- internal/static/i18n/ru.yaml
- internal/static/i18n/zh.yaml
When creating an app without secret or other type of authentication method,
like JWT, and the authentication type is switched afterwards the app would remain without generated secret.
If then client authentication with secret is attempted, for example on the token endpoint, the handler would panic in the crypto.CompareHash function on the nile pointer to the CryptoValue.
This fix introduces a nil pointer check in crypt.CompareHash and returns a error.
The issue was reported over discord: https://discord.com/channels/927474939156643850/1222971118730875020
Possible fix was suggested here: https://github.com/zitadel/zitadel/pull/6999#discussion_r1553503088
This bug only applies to zitadel versions <=2.49.1.
> fix(crypto): check for nil client secret

- internal/api/oidc/access_token.go
- internal/api/oidc/userinfo.go
- internal/auth/repository/eventsourcing/eventstore/token.go
- internal/auth/repository/eventsourcing/view/token.go
During loadtesting we found some gaps in the userinfo metrics obtained from tracing. This PR adds some extra spans to fill the gaps.
> chore(oidc): add additional spans to userinfo code paths

- cmd/defaults.yaml
- cmd/setup/config.go
- cmd/start/config_test.go
The setup job fails if role <--> permission mappings are provided by an env var in JSON format, as described in the defaults.yaml.
This PR makes sure, role mappings provided as JSON string in the YAML or by env var is decoded into the target type authz.RoleMapping. Also, it updates the example value, to the minimal configuration necessary for the setup job to succeed.
Unit test that ensure correct decoding are added in the start package and by intention not duplicated to the setup package.
The bug [was reported on Discord](https://discord.com/channels/927474939156643850/1209156907487469598).
> fix(setup): decode role mappings

- internal/query/device_auth_test.go
- internal/query/projection/device_auth.go
This fixes the projection of events that have a null audience or scope.
As audience was added in v2.50, legacy events do not have an audience, this made replay of the old events not possible after an upgrade.
> fix(oidc): make device auth audience and scope nullable

- internal/query/event.go
This fix improves performance if many events are queried because it does a single database call for each editor instead of a call per event
> fix(query): query event editors only once per call

- internal/api/grpc/server/middleware/translation_interceptor.go
- internal/i18n/bundle.go
- internal/i18n/fs.go
- internal/i18n/translator.go
Instead of loading the translation files for each request the files are cached on startup.
> fix(middleware): init translation messages

- internal/command/command.go
- internal/eventstore/eventstore_pusher_test.go
- internal/eventstore/v3/push.go
During concurrent push of the same event type, cockroachDB could fail and retry the transaction. We only obtained the latest sequences once, so the transaction would keep failing.
An example event that would cause the original bug was the "Secret check succeeded" pushed async after every introspection call. On many concurrent requests the zitadel logs would print:
```
time="2024-04-18T09:17:33Z" level=error msg="could not push event \"project.application.api.secret.check.succeeded\"" caller="/home/tim/Repositories/zitadel/zitadel/internal/command/command.go:299" error="retrying txn failed after 50 attempts. original error: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: WriteTooOldError: write for key /Table/110/1/\"263288598801940483\"/\"project\"/\"263290668288311299\" …
```
> fix(crdb): obtain latest sequences when the tx is retried

- e2e/cypress/e2e/events/events.cy.ts
Ensures, that after applying the filter, only the filtered event is displayed.
> test(e2e): check for exactly one displayed event

- internal/api/grpc/management/user.go
- internal/api/grpc/management/user_converter.go
- internal/command/user_machine_key.go
- internal/command/user_machine_key_test.go
- internal/static/i18n/bg.yaml
- internal/static/i18n/cs.yaml
- internal/static/i18n/de.yaml
- internal/static/i18n/en.yaml
- internal/static/i18n/es.yaml
- internal/static/i18n/fr.yaml
- internal/static/i18n/it.yaml
- internal/static/i18n/ja.yaml
- internal/static/i18n/mk.yaml
- internal/static/i18n/nl.yaml
- internal/static/i18n/pl.yaml
- internal/static/i18n/pt.yaml
- internal/static/i18n/ru.yaml
- internal/static/i18n/zh.yaml
- proto/zitadel/management.proto
Closes #7554 
Adds the option of using a locally generated RSA key for a machine key instead of having it generated by the server.
This prevents sending private keys over the network which is generally advised against.
A user can use the optional "pubkey" field of the request to send a public key. If a public key is specified, then no private key will be returned. If no public key is specified the behaviour is as before.
> feat: allow using a local RSA key for machine keys

- internal/auth/repository/eventsourcing/eventstore/auth_request.go
- internal/auth_request/repository/cache/cache.go
- internal/domain/auth_request.go
A bug was introduced with #7824, which would not correctly reload policies and idps in case the organization was change during the authentication.
fixes https://github.com/zitadel/zitadel/issues/7837
> fix(login): correctly reload policies on auth request

- cmd/defaults.yaml
Since there were different issues regarding the caching, we want to reduce the amount of problems caused on other systems and disable the cache by default for the moment.
> fix: disable auth cache by default

- proto/zitadel/member.proto
- proto/zitadel/user.proto
- proto/zitadel/user/v2beta/query.proto
- proto/zitadel/user/v3alpha/query.proto
In #7850 @cskeppstedt reported an issue when performing search user queries for email addresses. 
The error reported, when searching email address that didn't follow the 2822 format, was: `invalid EmailQuery.EmailAddress: value must be a valid email address `.
This error is due to an email validation rule present in the EmailQuery definition for v2beta/users. In this PR that validation is removed and, for an homogeneous behavior, I've modified other EmailQuery proto definitions so no min length is required and the RFC 2822 mention is removed from descriptions as we can indeed search for text like foobar and not foobar@example.com
Here are some screenshots of the tests I've performed:
Should close #7850
> fix: remove email validation for SearchUsers v2beta/users

- cmd/setup/config.go
- internal/api/ui/login/external_provider_handler.go
- internal/idp/providers/apple/apple.go
A customer reported that the login with Apple not always works, but often an invalid_client is returned.
We saw duplicate invocation of the callback in the logs, but are missing detailed information.
This PR adds additional logs. Since the authentication is relying on JWT, we also change the `iat` by 2 seconds into the past to mitigate potential clock skew problems.
Additionally a previous unintended change in the config parsing is removed.
> fix: improve secret generation for apple idp

- console/src/app/pages/users/user-detail/auth-user-detail/edit-dialog/edit-dialog.component.html
In #7762 @sschoeb reported that an email was always sent when the email address was changed in the console no matter if the Email Verified checkbox was set.
There was an issue with the checkbox ngModel that no matter the value of the checkbox isVerified was always false therefore the state was initialized and the email was sent. 
Adding [ngModelOptions]="{standalone: true}" to the checkbox fixes the issue and the email is only sent if the Email Verified checkbox is not checked as intended.
Thanks @sschoeb for reporting the issue
Should close #7762
> fix(cnsl): Email Verified checkbox value was not updated

- console/src/app/modules/nav/nav.component.html
In this PR https://github.com/zitadel/zitadel/pull/7274 it is documented that:
> On a newly created instance when having a single organization, settings are hidden from the organizations menu
In issue #7819 a possible edge case is reported. Assuming that the instance has only one organization a user without iam permissions would not see the Default Settings button and as the Settings button is currently only shown if user has policy.read permissions and there are more than one organization, a user without iam permissions sould have to click on the Modify buttons. 
I propose this PR where the Settings button will be kept hidden for users with iam permissions and for orgs < 2 but it will be shown for users that has no iam permissions in any case.
Here's a screenshot for the IAM Owner user, …
> fix: show settings button for users w/o iam perms

- internal/static/i18n/bg.yaml
- internal/static/i18n/cs.yaml
- internal/static/i18n/de.yaml
- internal/static/i18n/en.yaml
- internal/static/i18n/es.yaml
- internal/static/i18n/fr.yaml
- internal/static/i18n/mk.yaml
- internal/static/i18n/nl.yaml
- internal/static/i18n/pl.yaml
- internal/static/i18n/zh.yaml
- proto/zitadel/management.proto
Add missing translations on event types and correct wrong example in api
> fix: translate missing event types

- internal/notification/messages/email.go
As noticed by a customer (relates to #7880), the `Mime-Version` and `Content-Type` were not properly formatted, which depending on the smtp relay led to bad spam scoring.
> fix: correct email headers (mime version and content-type)

- docs/docs/self-hosting/deploy/loadbalancing-example/example-zitadel-config.yaml
Fix a wrong stated comment in the loadbalancing example.
> docs: fix example for self hosting load balancing

- internal/api/ui/login/init_user_handler.go
- internal/api/ui/login/mfa_verify_otp_handler.go
- internal/command/user_human.go
fixes a nil pointer panic (introduced with https://github.com/zitadel/zitadel/pull/7815), which occurred after a user was registered through an IdP.
While checking the logs, further panics were discovered and fixed in this PR.
> fix: user registration through IdP

- internal/api/ui/login/static/i18n/fr.yaml
SMS OTP MFA translations are not displayed in FR language on the login ui
By changing the typo in the FR translation file 
- Closes #7945
- https://discordapp.com/channels/927474939156643850/1239843688633471006
> fix: typo in the fr translation file for login ui sms otp mfa

- docs/docs/legal/policies/rate-limit-policy.md
We identified some frequent rate limits in ZITADEL Cloud.
We increase the rate limits of some endpoint.
(Private) Relates to https://github.com/zitadel/DevOps/issues/43
> chore(cloud): increase rate limits

- internal/query/targets_by_execution_id.sql
- internal/query/targets_by_execution_ids.sql
Curretly loading targets fails on cockraochdb because the order of `with`-statements is wrong.
Changed the order of queries in the statements.
> fix(actions): correct statements to query targets

- internal/api/ui/login/auth_request.go
- internal/api/ui/login/change_password_handler.go
- internal/api/ui/login/device_auth.go
- internal/api/ui/login/external_provider_handler.go
- internal/api/ui/login/ldap_handler.go
- internal/api/ui/login/link_prompt_handler.go
- internal/api/ui/login/mfa_init_sms.go
- internal/api/ui/login/mfa_init_u2f.go
- internal/api/ui/login/mfa_init_verify_handler.go
- internal/api/ui/login/mfa_prompt_handler.go
- internal/api/ui/login/mfa_verify_handler.go
- internal/api/ui/login/mfa_verify_otp_handler.go
- internal/api/ui/login/mfa_verify_u2f_handler.go
- internal/api/ui/login/password_handler.go
- internal/api/ui/login/password_reset_handler.go
- internal/api/ui/login/passwordless_login_handler.go
- internal/api/ui/login/select_user_handler.go
- internal/api/ui/login/username_change_handler.go
Potential nil pointers leading to a panic in the login UI.
As of now the login UI did not always check if the authRequest was actually retrieved form the database, which is ok for some endpoints which can also be called outside of an auth request.
There are now methods added to ensure the request is loaded.
None
Closes https://github.com/zitadel/DevOps/issues/55
> fix(login): ensure auth request

- internal/user/repository/view/user_by_id.sql
A customer noted that after upgrade to 2.53.0, users were no longer able to reset their passwords through the login UI.
This was due to a accidental change in https://github.com/zitadel/zitadel/pull/7969
The `preferred_login_name` is now correctly read from the database.
None.
relates to #7969
> fix(login): correctly set preferred login name in the login ui

- docs/docs/support/advisory/a10009.md
- docs/docs/support/advisory/a10010.md
- docs/docs/support/technical_advisory.mdx
Among others #7822 changed the event type of the `user.token.added` to `user.token.v2.added`. To make customers aware of this in case they use it for calculating DAU / MAU, resp. for an audit trail, we want to raise awareness.
Technical advisory to state the change.
None.
Relates to #7822
> docs(advisory): add technical advisory for token type change

- internal/api/grpc/session/v2/session_integration_test.go
- internal/command/session.go
- internal/command/session_test.go
If an IdP intent succeeded with the user was not linked yet, the IdP link was then added, the following IdP check on the session API would then fail with `Intent meant for another user (COMMAND-O8xk3w)`.
This issue was introduced with when allowing IdP intents from other organizations (https://github.com/zitadel/zitadel/pull/7871)
The IdP link is now correctly checked in the session API (using the user's organization instead of the one from the intent).
- Improved the corresponding integration test to cover the exact bahvior.
- Tests, which had to be updated with newer cases where additionally changed to use expectEventstore instead of deprecated eventstoreExpect and the two eventstore mocks of the session_tests.go where combined.
- Relates to #7871 
- This issue was reported by a …
> fix: session idp intent check

- internal/api/oidc/introspect.go
- internal/api/ui/login/renderer.go
Introspection errors such as invalid audience and errors in the login UI such as invalid user agents where all logged as severity error.
- errors that are not internal errors are logged as `info`
None
- internal discussion
> fix(logging): reduce log level of errors in introspection and login UI

- internal/api/grpc/server/gateway.go
- internal/api/ui/login/init_password_handler.go
- internal/api/ui/login/login_handler.go
- internal/api/ui/login/mail_verify_handler.go
- internal/api/ui/login/passwordless_registration_handler.go
We identified some parts in the code, which could panic with a nil pointer when accessed without auth request.
Additionally, if a GRPC method was called with an unmapped HTTP method, e.g. POST instead of GET a 501 instead of a 405 was returned.
- Additional checks for existing authRequest
- custom http status code mapper for gateway
None.
- noted internally in OPS
> fix: potential panics in login and return proper http 405

- cmd/mirror/mirror.go
Corrects reading of default configuration, despite reading all default configs only required defaults are read.
Reading the defualt config of the `mirror`-command was moved to a pre-run step of the command instead of doing it during initialization of the executable.
- Closes https://github.com/zitadel/zitadel/issues/8059
- https://discord.com/channels/927474939156643850/1248594307267559535
> fix: read correct defaults

- cmd/defaults.yaml
- internal/database/cockroach/crdb.go
- internal/database/postgres/pg.go
The init job fails if no database called *postgres* or *defaultdb* for cockroach respectively exists.
The value is now configurable, for example by env variable *ZITADEL_DATABASE_POSTGRES_ADMIN_EXISTINGDATABASE*
- Closes #5810
> feat(init): configurable existing postgres db

- proto/zitadel/management.proto
Some management requests did not state that the `x-zitadel-orgid` can / needs to be sent as part of the request.
Added it as paart of the swagger / openAPI documentation.
None.
- noted by a customer
> docs(api): add missing x-zitadel-orgid header to IdP request

- docs/docs/apis/openidoauth/scopes.md
It is not clear that the phone number can be requested in a separat oidc scope
Added the phone scope to the scope documentation
> docs: add phone scope to docs

- docs/docs/self-hosting/deploy/docker-compose-sa.yaml
- docs/docs/self-hosting/deploy/docker-compose.yaml
- docs/docs/self-hosting/deploy/loadbalancing-example/docker-compose.yaml
- docs/docs/self-hosting/manage/configure/docker-compose.yaml
- docs/docs/self-hosting/manage/reverseproxy/docker-compose.yaml
The docker-compose examples expose the database to the world.
Remove the `ports` config from the `db` service.
> chore(doc): do not expose database to public networks in examples

- console/src/app/modules/idp-table/idp-table.component.html
- console/src/app/modules/policies/idp-settings/idp-settings.component.html
- console/src/assets/i18n/en.json
- docs/docs/guides/integrate/identity-providers/azure-ad-saml.mdx
- docs/docs/guides/integrate/identity-providers/mocksaml.mdx
- docs/docs/guides/integrate/identity-providers/okta_saml.mdx
In the configuration of external idps we show SAML SP as provider which is confusing, as it is a SAML IdP which is configured
Rename SAML SP to SAML IdP
> fix: change saml sp to saml idp

- internal/eventstore/handler/v2/field_handler.go
Fixes a panic which can occur if there are no events to reduce in the fields handler
Check if there are any events to reduce
none
- Panic was added in https://github.com/zitadel/zitadel/pull/8191
> fix(eventstore): early return if no events in field handler

- docs/docs/guides/integrate/service-users/client-credentials.md
- docs/docs/guides/integrate/service-users/private-key-jwt.md
- It is not possible to introspect service user token if `urn:zitadel:iam:org:project:id:{projectid}:aud` scope is not added in token request.
- Adding this note to the document could reduce confusion and debugging time
- https://discord.com/channels/927474939156643850/1168857403945660436/1168930850029707386
> docs: note audience scope for service user

- internal/api/api.go
ZITADEL returned a 404 Unimplemented error if the client sent 'application/grpc+proto' or 'application/grpc+json' which are both valid content types.
changed the header matcher to regexp
Problem occured in https://github.com/zitadel/typescript/tree/grpc-transport
> fix(api): grpc content type matcher all grpc types

- internal/api/api.go
While #8285 also checked for `+proto` and `+json` grpc content types, it accidentally matched all grpc-web requests to grpc. 
- fixed the regex by checking for an exact match (added start `^` and end `$` anchors)
None
- relates to #8285
> fix: correctly differ between grpc and grpc-web

- internal/api/ui/login/static/i18n/zh.yaml
- Corrected a typo in the file `internal/api/ui/login/static/i18n/zh.yaml` where "Migrosoft" was changed to "Microsoft".
- Updated the misspelled word "Migrosoft" to "Microsoft" for consistency and accuracy.
- None
- None
> fix: Correct misspelling in zh.yaml file

- console/src/app/pages/users/user-detail/detail-form/detail-form.module.ts
- The UI layout is broken in Upload your Profile Picture
- MatDialog module was missing
Here's a screenshot showing the fix
- Closes #8284
> fix(console): missing styles for ProfilePictureComponent dialog

- cmd/defaults.yaml
- docs/docs/self-hosting/manage/database/_postgres.mdx
- e2e/config/host.docker.internal/zitadel.yaml
- e2e/config/localhost/zitadel.yaml
- internal/crypto/database/database.go
- internal/database/cockroach/crdb.go
- internal/database/database.go
- internal/database/postgres/pg.go
- internal/eventstore/handler/v2/field_handler.go
- internal/eventstore/handler/v2/handler.go
- internal/eventstore/v3/push.go
- internal/integration/config/postgres.yaml
- internal/query/current_state.go
The connection pool of go uses a high amount of database connections.
The standard lib connection pool was replaced by `pgxpool.Pool`
The `db.BeginTx`-spans are removed because they cause to much noise in the traces.
The default connection pool size was changed to 15 MaxOpenConns and 12 MaxIdleConns and 3 pusher connections and 2 spooler connections
- part of https://github.com/zitadel/zitadel/issues/7639
> refactor(database): exchange connection pool

- cmd/mirror/mirror.go
- cmd/zitadel.go
The mirror command read the configurations in the wrong order
The Pre execution run of `mirror` reads the default config first and then applies the custom configs
- requires backports to 2.54.x, 2.55.x and 2.56.x
> fix(mirror): read config correctly

- console/src/app/utils/framework.ts
The default vue logout URL doesn't work with the @zitadel/vue defaults
A trailing slash is added to the default logout URL.
Found while testing https://github.com/zitadel/zitadel-vue/pull/53
> fix: vue logout url

- e2e/cypress/e2e/organization/organizations.cy.ts
The e2e tests fail because the organization selection is too fast.
Wait until console has loaded properly.
- The tests still use the wrong browser, #8404 describes the problem
- closes https://github.com/zitadel/zitadel/issues/8378
> test(e2e): wait before select org

- internal/eventstore/handler/v2/field_handler.go
- internal/eventstore/v3/field.go
If the processing time of serializable transactions in the fields handler take too long, the next iteration can fail.
Changed the isolation level of the current states query to Read Commited
> fix(fields): use read commit isolation level in trigger

- .github/pull_request_template.md
In the PR template we have added some ideas about additional context, but we link to existing prs and issues as an example.
So everytime someone doesn't change the description when creating the issue, its a mention to that issue or pr.
replace with non existing values
> fix: change pr template to not link to existing issues and prs

- docs/sidebars.js
- internal/query/projection/web_key.go
- internal/query/web_key_by_state.sql
- internal/query/web_key_list.sql
- internal/query/web_key_public_keys.sql
- proto/zitadel/resources/webkey/v3alpha/webkey_service.proto
When Web keys with a large RSA Bitsize were generated, the new web key did not get projected.
Zitadel logs printed the following errors:
```
time="2024-08-15T09:18:47Z" level=debug msg="execution of statements failed" caller="/home/tim/Repositories/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:518" error="statement failed: ID=CRDB-pKtsr Message=exec failed Parent=(ERROR: index row size 3400 exceeds btree version 4 maximum 2704 for index \"web_keys_web_key_state_idx\" (SQLSTATE 54000))" lastProcessedIndex=-1 projection=projections.web_keys
```
Remove the the `WithInclude` option with the Private key from the `web_keys` projection index and bump the projection version.
- Correct RPC summaries for documentation
- Fix docs slug in sidebar.js
- Found during release review.
> fix(webkeys): remove include private key from projection index

- internal/authz/repository/eventsourcing/eventstore/token_verifier.go
When using a JWT access_token on a ZITADEL API, the token was considered invalid If the `WebKey` feature flag is enabled.
- Merge the new and old web keys if flag is enabled (as already done for the keys endpoint).
None
relates to #8449
> fix: internal check of JWT access tokens

- proto/zitadel/resources/action/v3alpha/action_service.proto
- proto/zitadel/resources/user/v3alpha/user_service.proto
- proto/zitadel/resources/userschema/v3alpha/user_schema_service.proto
- proto/zitadel/resources/webkey/v3alpha/webkey_service.proto
Alpha APIs are not available accessible using REST.
The base_path property for the swagger definition has nothing to do with the reverse proxy generation. Reusing it and omitting its segments in the individual methods leads to a wrong path mapping. To fix this, the full paths are added to all the GW mappings.
Replace this example with links to related issues, discussions, discord threads, or other sources with more context.
Use the Closing #issue syntax for issues that are resolved with this PR.
- Closes #8507
> fix: map gRPC Gateway paths correctly

- internal/auth/repository/eventsourcing/eventstore/auth_request.go
- internal/auth/repository/eventsourcing/eventstore/auth_request_test.go
When checking for the next step for the login UI and a user did not yet have an IdP linked, they would always be presented the password check screen, even if the local authentication was disabled.
- Correctly check the login policy for the `Allow Username Password` option
- In case the user has no IdP linked yet, fallback to the organizations configuration (and redirect if possible)
- the user can be auto-linked based on the username / email after successfully authenticating at the IdP
None
- closes https://github.com/zitadel/zitadel/issues/5106
- closes https://github.com/zitadel/zitadel/issues/7502
- requires backports (>=2.55.x)
> fix: check if pw login allowed

- internal/api/grpc/resources/webkey/v3/integration_test/webkey_integration_test.go
Deal with eventual consistency in the webkey integration tests.
Use an eventual with T for the list state check.
- none
- none
> fix(tests): check eventual web key state

- internal/integration/config/postgres.yaml
defaults.yaml only specifies defaults for cockroach. Therefore, options omitted for postgresql are actually set to `0`.
This means that the connections timeouts are set to `0` and connections were not reused, resulting in a performance penalty while running the integration tests.
Set MaxConnLifeTime and MaxConnIdleTime options in postgres
- none
- none
> chore(test): set connection lifetimes for postgresql

- e2e/config/localhost/docker-compose.yaml
Fix crdb to version v24.2.1 for e2e tests
> chore: fix crdb version on v24.2.1

- internal/api/authz/system_token.go
The integration tests noted a race condition when loading the key used to verify the signature of a System API JWT.
- Changed the mutex to a `RWMutex` and `RLock` before accessing the `cachedKeys` map
None
noticed in https://github.com/zitadel/zitadel/actions/runs/10850005593/job/30111110726?pr=8602#step:8:403
> fix: race condition in system jwt signature check

- console/src/app/modules/user-grants/user-grants.component.html
- console/src/app/modules/user-grants/user-grants.component.ts
- console/src/app/pages/grants/grants.component.html
- console/src/app/pages/projects/granted-projects/granted-project-detail/granted-project-detail.component.html
- console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.html
- console/src/app/pages/users/user-detail/auth-user-detail/auth-user-detail.component.html
- console/src/app/pages/users/user-detail/user-detail/user-detail.component.html
- internal/api/grpc/auth/user_grant.go
- internal/api/grpc/user/user_grant.go
- internal/api/oidc/client.go
- internal/api/saml/storage.go
- internal/auth/repository/eventsourcing/repository.go
- internal/query/user_grant.go
- internal/query/userinfo_by_id.sql
- proto/zitadel/auth.proto
ZITADEL's user grants deactivation mechanism did not work correctly. Deactivated user grants were still provided in token, which could lead to unauthorized access to applications and resources.
Additionally, the management and auth API always returned the state as active or did not provide any information about the state.
- Correctly check the user grant state on active for tokens and user information (userinfo, introspection, saml attributes)
- Map state in API and display in Console
> fix: user grants deactivation

- internal/api/authz/context.go
- internal/api/oidc/integration_test/token_client_credentials_test.go
- internal/api/oidc/integration_test/token_jwt_profile_test.go
- internal/domain/request.go
Calls with tokens issued through JWT Profile or Client Credentials Grants were no longer possible and threw a "could not read projectid by clientid (AUTH-GHpw2)" error.
ZITADEL checks the allowed origins of an application and load its projectID into the context on any API call.
Tokens from service accounts did not contain any clientID and therefore never did that check.
But due to a change in https://github.com/zitadel/zitadel/pull/8580, were the service user id was set as client_id in the OIDC session to fix the introspection response (https://github.com/zitadel/zitadel/issues/8590).
- Check if the project and origin were retrieved and only then check the origins
None.
- closes https://github.com/zitadel/zitadel/issues/8676
- relates to https://github.com/zitadel/zitadel/pull/8580 …
> fix: ignore projectID and origin check for service accounts

- internal/api/authz/context.go
- internal/api/grpc/user/v2/integration_test/user_test.go
V2 and V3 APIs allow setting the organization context by providing the organization domain in the request. Users currently experience the following error: "rpc error: code = Unauthenticated desc = context missing (AUTH-rKLWEH)"
Correctly check the org domain when set.
None
- support request
> fix(API): select org context by domain

- docs/docs/self-hosting/manage/reverseproxy/nginx/nginx-disabled-tls.conf
- docs/docs/self-hosting/manage/reverseproxy/nginx/nginx-enabled-tls.conf
- docs/docs/self-hosting/manage/reverseproxy/nginx/nginx-external-tls.conf
The Host header reaching ZITADEL must be the same like it is requested by the browser, or all sorts of issues arise. However, in the NginX docs, it is appended by the port.
Port is removed from examples
- Closes https://github.com/zitadel/zitadel/issues/7804
- Relates to https://github.com/netbirdio/netbird/issues/1395
> docs(nginx): pass host as received from client

- internal/query/lockout_policy.go
- internal/query/password_age_policy.go
- internal/query/password_complexity_policy.go
Errors messages are mixed up for some policies
Define new error IDs and correct the messages.
None
None
> fix: correct error messages for policy queries

- docs/docs/apis/introduction.mdx
The `/oauth/v1` path prefix is duplicated, which is an error in most proxies.
Remove the duplicate path prefix from the docs.
> docs: remove duplicate from API path prefixes

- internal/command/user_model.go
A customer reported, that after a created user (in initial state) got (manually) locked and a new initial code would be created, the user could not be locked again.
Query for the initial code added event
None
- reported by a customer
> fix: correctly compute user state

- internal/query/projection/milestones.go
- internal/query/projection/milestones_test.go
Since the optiimzation of the token endpoint, we longer push the `user.token.added` event. However, the milestone projection keeps quering for it, including a payload query.
This incured a static waste of DB resources.
Remove the `user.token.added` event reducer from the milestone projection
- none
- Related to https://github.com/zitadel/zitadel/issues/8742. Other changes ommitted so this PR can be backported to stable.
> perf(milestones): remove legacy token event reducer

- internal/auth/repository/eventsourcing/eventstore/auth_request.go
Admins can set the branding to be used from the project's organization. Until now, only the branding (colors) were respected, but texts were still loaded from the user's organization.
Respect the setting when loading the texts for the login pages.
None
- closes #8502
> fix: respect PrivateLabelingSetting on project for login texts

- internal/command/session_otp.go
- internal/domain/session.go
- internal/notification/handlers/user_notifier.go
- proto/zitadel/session/v2/challenge.proto
- proto/zitadel/user/v2/auth.proto
- proto/zitadel/user/v2/email.proto
- proto/zitadel/user/v2/password.proto
- proto/zitadel/user/v2/user.proto
OTP Email links currently could not use / include the sessionID they belong to. This prevents an easy use for redirecting and handling OTP via email through the session API.
Added the sessionID as placeholder for the OTP Email link template.
List all available placeholders in the url_templates of V2 endpoints.
- discussed in a customer meeting
> fix: pass sessionID to OTP email link

- internal/idp/providers/saml/session.go
If SAML response validation in crewjam/saml fails, a generic "Authentication failed" error is thrown. This makes it challenging to determine the actual cause, since there are a variety of reasons response validation may fail.
Add a log statement if we receive a response validation error from crewjam/saml that logs the internal `InvalidResponseError.PrivateErr` error from crewjam/saml to stdout. We continue to return a generic error message to the client to prevent leaking data.
Verified by running `go test -v ./internal/idp/providers/saml` in verbose mode, which output the following line for the "response_invalid" test case:
```
time="2024-10-03T14:53:10+01:00" level=info msg="invalid SAML response details" caller="/Users/sdouglas/Documents/thirdparty-repos/zitadel/internal/idp/providers/s …
```
> fix(SAML): log underlying error if SAML response validation fails

- internal/api/ui/login/external_provider_handler.go
- internal/api/ui/login/register_handler.go
There is currently the possibility that you can jump to the register path, even if register is disallowed through the settings.
Check before handling the HTTP requests if register is allowed.
Function to determine the resourceowner for all register related functionality in the login.
closes #8123
> fix: add allowRegister check for register handling in login

- docs/docs/concepts/features/actions_v2.md
- proto/zitadel/management.proto
- The addorgmember request shows a wrong example in the api documentation
- Broken Links on actions feature description
- Change example of AddOrgMember API Docs
- Point towards correct links
> docs: fix wrong examples and links

- internal/api/grpc/admin/integration_test/iam_member_test.go
- internal/api/grpc/admin/integration_test/iam_settings_test.go
- internal/api/grpc/org/v2/integration_test/query_test.go
- internal/api/grpc/resources/action/v3alpha/integration_test/execution_target_test.go
- internal/api/grpc/resources/action/v3alpha/integration_test/query_test.go
- internal/api/grpc/resources/action/v3alpha/integration_test/server_test.go
- internal/api/grpc/resources/userschema/v3alpha/integration_test/query_test.go
- internal/api/grpc/settings/v2/integration_test/settings_test.go
- internal/api/grpc/settings/v2beta/integration_test/settings_test.go
- internal/api/grpc/user/v2/integration_test/idp_link_test.go
- internal/api/grpc/user/v2/integration_test/passkey_test.go
- internal/api/grpc/user/v2/integration_test/query_test.go
- internal/api/grpc/user/v2beta/integration_test/query_test.go
Eventual consistency is handled wrongly in the newly improved integration tests.
Correct the usage of the require package with the assert package where necessary, to remove the panics where the EventuallyWithT functions can rerun.
Modify the timeout values for some EventuallyWithT which can vary when a instance is freshly setup.
None
> chore: correct require usage to assert for eventual consistency

- internal/api/grpc/oidc/v2/integration_test/oidc_test.go
- internal/api/grpc/oidc/v2beta/integration_test/oidc_test.go
- internal/api/grpc/resources/action/v3alpha/integration_test/execution_target_test.go
- internal/api/grpc/resources/action/v3alpha/integration_test/query_test.go
- internal/api/grpc/resources/webkey/v3/integration_test/webkey_integration_test.go
- internal/api/grpc/user/v2/integration_test/query_test.go
- internal/api/grpc/user/v2/integration_test/user_test.go
- internal/api/grpc/user/v2beta/integration_test/user_test.go
- internal/integration/assert.go
- internal/integration/oidc.go
In integration tests there is waiting for the application, but the project is also included if the token can be created.
Wait for project not only for the application in the integration tests.
Some more corrections in integration tests.
None
> chore: add await for project to oidc integration tests

- internal/api/grpc/org/converter.go
- internal/api/grpc/org/v2/integration_test/query_test.go
- internal/api/grpc/org/v2/query.go
- internal/query/org.go
Searching orgs by domain currently only looked for the primary domain, but should be possible with all verified domains (as documented)
- fixed the search query
None
- closes https://github.com/zitadel/zitadel/issues/8749
> fix: correctly search for verified domain

- docs/docs/concepts/architecture/software.md
- docs/docs/concepts/architecture/solution.md
- docs/docs/self-hosting/deploy/overview.mdx
- docs/docs/self-hosting/manage/database/_postgres.mdx
- docs/docs/self-hosting/manage/production.md
As we switched to PostgreSQL with our cloud zitadel, we now want to recommend it instead of CockroachDB.
Replaced the recommend section with postgresql
> docs: change recommendation from cockroachDB to postgreSQL

- internal/api/ui/login/static/templates/register_org.html
Closes #8838 
This fixes a bug of the `/register/org` page where scripts where not referenced correctly
> fix(login): org register script references

- internal/repository/milestone/events.go
- internal/repository/milestone/type_enumer.go
Migration of milestones failed on our QA due to the new milestone Type enum being 0-indexed. The valid range was 0 till 5, inclusive. While on the previous zitadel version this was 1 till 6, inclusive.
Offset the first constant with `1`.
- none
Introduced in https://github.com/zitadel/zitadel/pull/8788
> fix(milestones): offset the type enum

- docs/docusaurus.config.js
Duplicate section in the doc
Change the category link source to add a introduction section
> docs(v2): fix duplicate section of user, session,  oidc and settings services

- cmd/mirror/verify.go
Fixes 'column "instance_id" does not exist' errors from #8558.
The instanceClause / WHERE clause in the query for the respective tables is excluded.
I have successfully created a mirror with this change.
> fix(mirror): Fix instance_id check for tables without

- internal/migration/step.go
The setup filter for previous steps and kept getting slower. This is due to the filter, which did not provide any instanceID and thus resulting in a full table scan.
- Added an empty instanceID filter (since it's on system level)
None
Noticed internally and during migrations on some regions
> fix(setup): improve search query to use index

- cmd/defaults.yaml
- go.mod
- go.sum
- internal/cache/connector/redis/circuit_breaker.go
- internal/cache/connector/redis/circuit_breaker_test.go
- internal/cache/connector/redis/connector.go
- internal/cache/connector/redis/redis_test.go
If a redis cache has connection issues or any other type of permament error,
it tanks the responsiveness of ZITADEL.
We currently do not support things like Redis cluster or sentinel. So adding a simple redis cache improves performance but introduces a single point of failure.
Implement a [circuit breaker](https://learn.microsoft.com/en-us/previous-versions/msp-n-p/dn589784(v=pandp.10)?redirectedfrom=MSDN) as [`redis.Limiter`](https://pkg.go.dev/github.com/redis/go-redis/v9#Limiter) by wrapping sony's [gobreaker](https://github.com/sony/gobreaker) package. This package is picked as it seems well maintained and we already use their `sonyflake` package
- The unit tests constructed an unused `redis.Client` and didn't cleanup the connector. This is now fixed.
Closes #8864
> feat(cache): redis circuit breaker

- cmd/defaults.yaml
By having default entries in the `Username` and `ClientName` fields, it was not possible to unset there parameters. Unsetting them is required for GCP connections
Set the fields to empty strings.
- none
- none
> fix(cache): unset client and user names in defaults

- internal/command/org_flow.go
- internal/query/action_flow.go
- internal/query/action_flow_test.go
The order of actions on a trigger was not respected on the execution and not correctly returned when retrieving the flow, for example in Console.
The supposed correction of the order (e.g. in the UI) would then return a "no changes" error since the order was already as desired.
- Correctly order the actions of a trigger based on their configuration (`trigger_sequence`). 
- replaced a `reflect.DeepEqual` with `slices.Equal` for checking the action list
- reported by a customer
- requires backports
> fix(actions): preserve order of execution

- internal/command/user_human.go
- ImportHuman was not checking for a `UserStateDeleted` state on import, resulting in "already existing" errors when attempting to delete and re-import a user with the same id 
Use the `Exists` helper method to check for both `UserStateUnspecified` and `UserStateDeleted` states on import 
N/A
N/A
> fix: use correct check for user existing on import

- internal/eventstore/repository/sql/crdb.go
- internal/eventstore/repository/sql/query.go
- internal/eventstore/repository/sql/query_test.go
- internal/eventstore/v3/push.go
Noisy neighbours can introduce projection latencies because the projections only query events older than the start timestamp of the oldest push transaction.
During push we set the application name to `zitadel_es_pusher_<instance_id>` instead of `zitadel_es_pusher` which is used to query events by projections.
> fix(eventstore): set application name during push to instance id

- internal/command/instance_debug_notification_log_test.go
- internal/database/database.go
- internal/eventstore/eventstore.go
- internal/eventstore/eventstore_bench_test.go
- internal/eventstore/eventstore_pusher_test.go
- internal/eventstore/eventstore_test.go
- internal/eventstore/repository/mock/repository.mock.go
- internal/eventstore/repository/mock/repository.mock.impl.go
- internal/eventstore/v3/eventstore.go
- internal/eventstore/v3/field.go
- internal/eventstore/v3/push.go
- internal/eventstore/v3/sequence.go
- internal/eventstore/v3/unique_constraints.go
Push is not capable of external transactions.
A new function `PushWithClient` is added to the eventstore framework which allows to pass a client which can either be a `*sql.Client` or `*sql.Tx` and is used during push.
Added interfaces to database package.
- part of https://github.com/zitadel/zitadel/issues/8931
> feat(eventstore): accept transaction in push

- internal/eventstore/eventstore.go
`eventstore.PushWithClient` required the wrong type of for the client parameter.
Changed type of client from `database.Client` to `database.QueryExecutor`
> fix(eventstore): correct database type in `PushWithClient`

- cmd/setup/39.go
- cmd/setup/39.sql
- cmd/setup/config.go
- cmd/setup/setup.go
- internal/repository/org/org.go
When an org is removed, the corresponding fields are not deleted. This creates issues, such as recreating a new org with the same verified domain.
Remove the search fields by the org aggregate, instead of just setting the removed state.
- Cleanup migration script that removed current stale fields.
- Closes https://github.com/zitadel/zitadel/issues/8943
- Related to https://github.com/zitadel/zitadel/pull/8790
> fix(eventstore): cleanup org fields on remove

- internal/database/cockroach/crdb.go
- internal/database/postgres/pg.go
- internal/eventstore/v3/push.go
- internal/eventstore/v3/push_without_func.go
Sometimes the projection spooler misses events, resulting in gaps in the projection. Normally the spooler should wait on active push transaction for a given appname that includes the instance ID.
1. In the new push the appname was never set. Thus the spooler would never wait
2. Previously this behaviour was seen infrequently and might have resulted from a race condition between the moment the transaction started and the app_name was set.
Set the application_name in the Before Acquire hook of the PGX connection pool.
Reset the application_name in the After Release hook.
- https://discord.com/channels/927474939156643850/1308717775362986004
- Possibly introduced or amplified by https://github.com/zitadel/zitadel/pull/8918
> fix(eventstore): set app_name in acquire

- cmd/defaults.yaml
- internal/api/ui/login/init_password_handler.go
- internal/api/ui/login/init_user_handler.go
- internal/api/ui/login/invite_user_handler.go
- internal/api/ui/login/mail_verify_handler.go
- internal/api/ui/login/mfa_verify_otp_handler.go
- internal/notification/handlers/notification_worker.go
- internal/notification/handlers/user_notifier.go
- internal/notification/handlers/user_notifier_legacy.go
- internal/notification/handlers/user_notifier_legacy_test.go
- internal/notification/projections.go
- internal/notification/types/domain_claimed.go
- internal/notification/types/email_verification_code.go
- internal/notification/types/email_verification_code_test.go
- internal/notification/types/init_code.go
- internal/notification/types/invite_code.go
- internal/notification/types/otp.go
- internal/notification/types/password_change.go
- internal/notification/types/password_code.go
- internal/notification/types/passwordless_registration_link.go
- internal/notification/types/passwordless_registration_link_test.go
- internal/notification/types/phone_verification_code.go
- internal/notification/types/types_test.go
There are some problems related to the use of CockroachDB with the new notification handling (#8931). 
See #9002 for details.
- Brought back the previous notification handler as legacy mode.
- Added a configuration to choose between legacy mode and new parallel workers.
- Enabled legacy mode by default to prevent issues.
None
- closes https://github.com/zitadel/zitadel/issues/9002
- relates to #8931
> fix(notifications): bring back legacy notification handling

- internal/eventstore/repository/sql/query.go
- internal/eventstore/repository/sql/query_test.go
In eventstore queries with aggregate ID exclusion filters, filters on events creation date where not passed to the sub-query. This results in a high amount of returned rows from the sub-query and high overall query cost.
When CreatedAfter and CreatedBefore are used on the global search query, copy those filters to the sub-query. We already did this for the position column filter.
- none
- Introduced in https://github.com/zitadel/zitadel/pull/8940
> fix(eventstore): set created filters to exclusion sub-query

- cmd/setup/39.sql
Migration step 39 is supposed to cleanup stale organization entries in the eventstore.fields table. In order to do this it used the projection to check which orgs still exist.
During initial setup of ZITADEL the first instance with the organization is created. Howevet, the projections are filled after all migrations are done. With the organization projection empty, the fields of the first org would be deleted.
This was discovered during development of a new field type. The accosiated events did not yet have any projection based filled assigned. It seems fields with a pre-fill projection are somehow restored. Therefore a restoration migration isn't required IMO.
Query the event store for `org.removed` events instead. This has the drawback of using a sequential scan on the eventstore, …
> fix(migrations): clean stale org fields using events

- proto/zitadel/user/v2/user_service.proto
The `CreateInviteCode` and `VerifyInviteCode` methods missed the body mapping.
Added the mapping.
None
Noticed during internal login UI tests using REST
> fix(api): map REST request body in user invite requests

- docs/docs/apis/observability/health.md
- Fixed a typo in docs/docs/apis/observability/health.md where `Enpoints` should be `Endpoints`
> docs: fix typo where Enpoints should be Endpoints

- cmd/setup/41.go
- cmd/setup/config.go
- cmd/setup/setup.go
setup step 41 cannot handle downgrades at the moment. This step writes the instance domain to the fields table. If there are new instances created during the downgraded version is running there would be domain missing in the fields afterwards.
Make step 41 repeatable
> fix(setup): make step 41 repeatable

- cmd/setup/39.go
- cmd/setup/39.sql
- cmd/setup/config.go
- cmd/setup/setup.go
When downgrading zitadel and upgrading it again, it might be that orgs deleted in this period still have stale entries in the fields table.
- Make the cleanup repeatable
- Scope the query by instance so that an index is used.
> fix(setup): make step 39 repeatable

- internal/i18n/translator.go
If a browsers default language is not allowed by instance restrictions, the login still renders it if it finds any custom texts for this language. In that case, the login tries to render all texts on all screens in this language using custom texts, even for texts that are not customized.
If a custom messages language is not allowed, it is not added to the i18n library's translations bundle. The library correctly falls back to the instances default language.
This library method only receives messages for allowed languages
Reported via support request
> fix(login): avoid disallowed languages with custom texts

- internal/idp/providers/saml/saml.go
- internal/idp/providers/saml/saml_test.go
SAML IdPs exposing an `EntitiesDescriptor` using an `xsd:duration` time format for the `cacheDuration` property (e.g. `PT5H`) failed parsing.
Handle the unmarshalling for `EntitiesDescriptor` specifically. [crewjam/saml](https://github.com/crewjam/saml/blob/bbccb7933d5f60512ebc6caec7120c604581983d/metadata.go#L88-L103) already did this for `EntitiyDescriptor` the same way.
None
- reported by a customer
- needs to be backported to current cloud version (2.66.x)
> fix(saml): parse xsd:duration format correctly

- internal/api/ui/login/static/i18n/de.yaml
Type in the word Microsoft on the init mfa otp screen
Fix typo
> fix: Typo in Init MFA OTP screen

- internal/api/ui/login/external_provider_handler.go
IdPs using form callback were not always correctly handled with the newly introduced cache mechanism (https://github.com/zitadel/zitadel/pull/9097).
Get the data from cache before parsing it.
None
Relates to https://github.com/zitadel/zitadel/pull/9097
> fix(idp): correctly get data from cache before parsing

- internal/cache/connector/redis/get.lua
When `LastUseAge` was configured properly, the Redis LUA script uses manual cleanup for `MaxAge` based expiry. The expiry obtained from Redis apears to be a string and was compared to an int, resulting in a script error.
Convert expiry to number.
- none
- Introduced in #8822
- LastUseAge was fixed in #9097
- closes https://github.com/zitadel/zitadel/issues/9140
> fix(cache): convert expiry to number

- cmd/defaults.yaml
- internal/api/oidc/key.go
- internal/api/oidc/op.go
It was possible to set a diffent algorithm for the legacy signer. This is not supported howerver and breaks the token endpoint. 
Remove the OIDC.SigningKeyAlgorithm config option and hard-code RS256 for the legacy signer.
- none
Only RS256 is supported by the legacy signer. It was mentioned in the comment of the config not to use it and use the webkeys resource instead.
- closes #9121
> fix(oidc): ignore algorithm for legacy signer

- internal/api/scim/authz.go
- internal/api/scim/integration_test/users_get_test.go
- internal/api/scim/resources/resource_handler.go
- internal/api/scim/resources/resource_handler_adapter.go
- internal/api/scim/resources/user.go
- internal/api/scim/resources/user_mapping.go
- internal/api/scim/resources/user_metadata.go
- internal/api/scim/server.go
- internal/integration/assert.go
- internal/integration/assert_test.go
- internal/integration/scim/client.go
- Adds support for the get user SCIM v2 endpoint
- Adds support for the get user SCIM v2 endpoint under `GET /scim/v2/{orgID}/Users/{id}`
Part of #8140
Replaces https://github.com/zitadel/zitadel/pull/9154 as requested by the maintainers, discussions see https://github.com/zitadel/zitadel/pull/9154.
> feat: get user scim v2 endpoint

- internal/api/scim/authz.go
- internal/api/scim/integration_test/testdata/users_create_test_minimal_inactive.json
- internal/api/scim/integration_test/testdata/users_replace_test_full.json
- internal/api/scim/integration_test/testdata/users_replace_test_minimal.json
- internal/api/scim/integration_test/testdata/users_replace_test_minimal_with_external_id.json
- internal/api/scim/integration_test/users_create_test.go
- internal/api/scim/integration_test/users_delete_test.go
- internal/api/scim/integration_test/users_get_test.go
- internal/api/scim/integration_test/users_replace_test.go
- internal/api/scim/resources/resource_handler.go
- internal/api/scim/resources/resource_handler_adapter.go
- internal/api/scim/resources/user.go
- internal/api/scim/resources/user_mapping.go
- internal/api/scim/resources/user_metadata.go
- internal/api/scim/server.go
- internal/command/user_human.go
- internal/command/user_model.go
- internal/command/user_v2_human.go
- internal/integration/assert.go
- internal/integration/scim/client.go
- Adds support for the replace user SCIM v2 endpoint
- Adds support for the replace user SCIM v2 endpoint under `PUT /scim/v2/{orgID}/Users/{id}`
- Respect the `Active` field in the SCIM v2 create user endpoint `POST /scim/v2/{orgID}/Users`
- Eventually consistent read endpoints used in SCIM tests are wrapped in `assert.EventuallyWithT` to work around race conditions
Part of #8140
> feat: replace user scim v2 endpoint

- internal/api/scim/resources/user_metadata.go
- include tzdata in the binary to correctly validate time zones in the scim layer if the os doesn't have timezone data available.
- by importing the go pkg `"time/tzdata"`
Part of https://github.com/zitadel/zitadel/issues/8140
> fix: include tzdata to validate timezones in scim

- cmd/setup/40.go
- cmd/setup/40/cockroach/40_init_push_func.sql
https://github.com/zitadel/zitadel/pull/9186 introduced the new `push` sql function for cockroachdb. The function used the wrong database function to generate the position of the event and would therefore insert events at a position before events created with an old Zitadel version. 
Instead of `EXTRACT(EPOCH FROM NOW())`, `cluster_logical_timestamp()` is used to calculate the position of an event.
- Introduced in https://github.com/zitadel/zitadel/pull/9186
- Affected versions: https://github.com/zitadel/zitadel/releases/tag/v2.67.3
> fix(eventstore): correct crdb sql push function

- internal/notification/handlers/notification_worker.go
The subquery of the notification requested and retry requested is missing the aggregate_type filter that would allow it to utilize the `es_projection` or `active_instances_events` on the eventstore.events2 table. 
Add additional filter on subquery. Final query: 
```sql
SELECT <all the fields omitted> FROM eventstore.events2
WHERE
instance_id = $1
AND aggregate_type = $2
AND event_type = $3
AND created_at > $4
AND aggregate_id NOT IN (
SELECT aggregate_id
FROM eventstore.events2
WHERE
aggregate_type = $5 <-- NB: previously missing
AND event_type = ANY ($6)
AND instance_id = $7
AND created_at > $8
)
ORDER BY "position", in_tx_order
LIMIT $9
FOR UPDATE SKIP LOCKED
```
> fix: add aggregate type to subquery to utilize indexes

- internal/notification/handlers/user_notifier_legacy.go
- internal/notification/handlers/user_notifier_legacy_test.go
#9185 changed that if a notification channel was not present, notification workers would no longer retry to send the notification and would also cancel in case Twilio would return a 4xx error.
However, this would not affect the "legacy" mode.
- Handle `CancelError` in legacy notifier as not failed (event).
None
- relates to #9185 
- requires back port to 2.66.x and 2.67.x
> fix(notifications): cancel on missing channels and Twilio 4xx errors

- cmd/setup/setup.go
Paths for setup steps are joined with "\" when binary is started under Windows, which results in wrongly joined paths.
Replace the usage of "filepath" with "path" package, which does only join with "/" and nothing OS specific.
None
Closes #9227
> fix: change usage from filepath to path

- internal/api/scim/resources/filter/filter_query_builder.go
- internal/api/scim/resources/filter/filter_query_builder_test.go
- internal/api/scim/resources/user_query_builder.go
- internal/query/search_query.go
- internal/query/search_query_test.go
- when listing users via scim v2.0 filters applied to the username are applied case-sensitive
- when a query filter is appleid on the username it is applied case-insensitive
Part of https://github.com/zitadel/zitadel/issues/8140
> fix: scim 2 filter: the username should be treated case-insensitive

- cmd/defaults.yaml
- internal/api/scim/config/config.go
- internal/api/scim/integration_test/service_provider_config_test.go
- internal/api/scim/integration_test/testdata/service_provider_config_expected.json
- internal/api/scim/integration_test/testdata/service_provider_config_expected_resource_type_user.json
- internal/api/scim/integration_test/testdata/service_provider_config_expected_resource_types.json
- internal/api/scim/integration_test/testdata/service_provider_config_expected_schemas.json
- internal/api/scim/integration_test/testdata/service_provider_config_expected_user_schema.json
- internal/api/scim/resources/bulk.go
- internal/api/scim/resources/resource_handler.go
- internal/api/scim/resources/resource_handler_adapter.go
- internal/api/scim/resources/resource_list.go
- internal/api/scim/resources/user.go
- internal/api/scim/resources/user_mapping.go
- internal/api/scim/resources/user_query_builder.go
- internal/api/scim/schemas/schema_builder.go
- internal/api/scim/schemas/schemas.go
- internal/api/scim/schemas/string.go
- internal/api/scim/server.go
- internal/api/scim/service_provider.go
- internal/integration/scim/client.go
* Adds support for the service provider configuration SCIM v2 endpoints
* Adds support for the service provider configuration SCIM v2 endpoints
* `GET /scim/v2/{orgId}/ServiceProviderConfig`
* `GET /scim/v2/{orgId}/ResourceTypes`
* `GET /scim/v2/{orgId}/ResourceTypes/{name}`
* `GET /scim/v2/{orgId}/Schemas`
* `GET /scim/v2/{orgId}/Schemas/{id}`
Part of #8140
> feat: add scim v2 service provider configuration endpoints

- internal/api/scim/integration_test/testdata/users_update_test_full.json
- internal/api/scim/resources/patch/patch.go
- Some SCIM clients send "op" of a patch operation in PascalCase
- Well known "op" values of patch operations are matched case-insensitive.
Related to #8140
> fix: scim 2.0 patch ignore op casing

- internal/api/scim/resources/user.go
- when a scim user is provisioned, a init email could be sent
- no init email should be sent => hard code false for the email init param
Related to https://github.com/zitadel/zitadel/issues/8140
> fix: scim create users dont send init emails

- cmd/setup/46/06-permitted_orgs_function.sql
After updating to version 2.69.0, my zitadel instance refuse to start with this error log :
```
time="2025-02-03T19:46:47Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:66" name=46_init_permission_functions
time="2025-02-03T19:46:47Z" level=info msg="execute statement" caller="/home/runner/work/zitadel/zitadel/cmd/setup/46.go:29" file=01-role_permissions_view.sql migration=46_init_permission_functions
time="2025-02-03T19:46:47Z" level=info msg="execute statement" caller="/home/runner/work/zitadel/zitadel/cmd/setup/46.go:29" file=02-instance_orgs_view.sql migration=46_init_permission_functions
time="2025-02-03T19:46:47Z" level=info msg="execute statement" caller="/home/runner/work/zitadel/zitadel/cmd/setup/46.go:29" …
```
> fix(setup): Fix query alias on 46-06

- internal/api/scim/integration_test/bulk_test.go
- internal/api/scim/integration_test/testdata/users_update_test_full.json
- internal/api/scim/integration_test/users_create_test.go
- internal/api/scim/integration_test/users_get_test.go
- internal/api/scim/integration_test/users_list_test.go
- internal/api/scim/integration_test/users_replace_test.go
- internal/api/scim/integration_test/users_update_test.go
- internal/api/scim/resources/user.go
- internal/api/scim/resources/user_mapping.go
- internal/api/scim/resources/user_patch_test.go
- internal/api/scim/schemas/bool.go
- internal/api/scim/schemas/bool_test.go
- Microsoft Entra invokes the user patch endpoint with `"active": "True"` / `"active": "False"` when patching a user. This is a well-known bug in MS Entra (see [here](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/application-provisioning-config-problem-scim-compatibility)), but the bug fix has not landed yet and/or the feature flag does not work.
- To ensure compatibility with MS Entra, the parsing of the the boolean active flag of the scim user is relaxed and accepts strings in any casing that resolve to `true` or `false` as well as raw boolean values.
Part of https://github.com/zitadel/zitadel/issues/8140
> fix: relax parsing of SCIM user 'active' flag to improve compatibility

- internal/api/scim/integration_test/bulk_test.go
- internal/api/scim/integration_test/users_create_test.go
- internal/api/scim/integration_test/users_get_test.go
- internal/api/scim/integration_test/users_list_test.go
- internal/api/scim/integration_test/users_replace_test.go
- SCIM tests are flaky due to metadata being set by the tests while shortly after being read by the application, resulting in a race condition
- whenever metadata is set, the projection is awaited
Part of #8140
> fix: ensure metadata is projected for scim tests to ensure stable tests

- cmd/setup/25.go
The login by email was not possible anymore. This was due to a newly generated user projection because of #9255 .
Internal logs showed that the computed lower case column for verified email was missing.
Update name of setup step 25 to rerun the step, since the underlying sql changed.
None
- relates to #9255
> fix(login): fix migration to allow login by email again

- internal/api/oidc/auth_request.go
As reported in #9311, even when providing a `x-zitadel-login-client` header, the auth request would be created as hosted login UI / V1 request.
This is due to a change introduced with #9071, where the login UI version can be specified using the app configuration.
The configuration set to V1 was not considering if the header was sent.
- Check presence of `x-zitadel-login-client` before the configuration. Use later only if no header is set.
None
- closes #9311 
- needs back ports to 2.67.x, 2.68.x and 2.69.x
> fix(oidc / login v2): always us login v2 if x-zitadel-login-client header is sent

- internal/api/grpc/oidc/v2/integration_test/oidc_test.go
- internal/api/grpc/oidc/v2/integration_test/server_test.go
- internal/api/grpc/oidc/v2/oidc.go
- internal/api/grpc/oidc/v2beta/integration_test/oidc_test.go
- internal/api/grpc/oidc/v2beta/integration_test/server_test.go
- internal/api/grpc/oidc/v2beta/oidc.go
- internal/api/grpc/saml/v2/integration/saml_test.go
- internal/api/grpc/saml/v2/integration/server_test.go
- internal/api/grpc/saml/v2/saml.go
- internal/api/grpc/session/v2/integration_test/query_test.go
- internal/api/oidc/integration_test/client_test.go
- internal/api/oidc/integration_test/oidc_test.go
- internal/command/auth_request.go
- internal/command/auth_request_test.go
- internal/command/main_test.go
- internal/command/saml_request.go
- internal/command/saml_request_test.go
- internal/domain/permission.go
- internal/integration/client.go
- internal/integration/oidc.go
- internal/integration/saml.go
- internal/notification/handlers/integration_test/telemetry_pusher_test.go
- internal/query/app.go
- internal/query/app_oidc_project_permission.sql
- internal/query/app_project_permission.sql
- internal/query/app_saml_project_permission.sql
Through configuration on projects, there can be additional permission checks enabled through an OIDC or SAML flow, which were not included in the OIDC and SAML services.
Add permission check through the query-side of Zitadel in a singular SQL query, when an OIDC or SAML flow should be linked to a SSO session. That way it is eventual consistent, but will not impact the performance on the eventstore. The permission check is defined in the API, which provides the necessary function to the command side.
Added integration tests for the permission check on OIDC and SAML service for every combination.
Corrected session list integration test, to content checks without ordering.
Corrected get auth and saml request integration tests, to check for timestamp of creation, not start of test.
Closes …
> feat: permission check on OIDC and SAML service session API

- internal/api/grpc/session/v2beta/integration_test/query_test.go
Ordering of sessions in v2beta is still relevant in the integration tests.
Correct the integration tests on session service v2beta like in v2.
None
Failing integration tests in pipeline.
> test: session v2beta corrected like v2

- internal/eventstore/handler/v2/handler.go
The success case of the handler.Trigger function was not handled.
Continue work without wait if there was no error.
> fix(handler): skip retry if trigger didn't fail

- internal/query/session.go
#9110 introduced more possibilities to search for "own" sessions. Due to this the permission checks for retrieving a session had to be updated accordingly. Internal calls, such as retrieving them for sending notifications do not require a permission, but the code was not properly adjusted and thus could lead to panics.
- Properly handled (do not require) permission check for internal only calls when retrieving the session by id.
None
- needs backports to 2.68.x, 2.69.x, 2.70.x
- closes zitadel/devops#117
> fix: prevent panic when retrieving session by id in internal calls

- cmd/setup/setup.go
- cmd/start/start.go
- internal/queue/queue.go
This PR clarifies configuration handling when using CockroachDB with notifications by enforcing that notifications.LegacyEnabled must be true.
If configuration `notifications.LegacyEnabled` is set to false when using cockroachdb as a database Zitadel start does not work and prints the following error: `level=fatal msg="unable to start zitadel" caller="github.com/zitadel/zitadel/cmd/start/start_from_init.go:44" error="can't scan into dest[0]: cannot scan NULL into *string"`
The combination of the setting and cockraochdb are checked and a better error is provided to the user.
- introduced with https://github.com/zitadel/zitadel/pull/9321
> fix(cmd): clarify notification config handling

- API_DESIGN.md
The API guidelines were not completely accurate on how we want to check permissions.
Made the description clearer and added examples.
Improved the error code example as initially intended in #9340
and added notes about the `limits` for listing resources.
popped up in PR review of https://github.com/zitadel/zitadel/pull/9445
> docs: improve api guidelines

- docs/docs/guides/integrate/login/hosted-login.mdx
We configured the default base URL for the hosted v2 login to `/ui/v2/login`. However, the docs still instruct readers to configure the URL explicitly. This is unneccesary mental overhead and a risk of self-DOS due to typos.
The docs instruct readers to not configure the base URL in order to use the default.
> docs(cloud login v2): use default login url

- internal/api/oidc/integration_test/token_exchange_test.go
- internal/api/oidc/token_exchange.go
When requesting a JWT (`urn:ietf:params:oauth:token-type:jwt`) to be returned in a Token Exchange request, ZITADEL would panic if the `actor` was not granted the necessary permission.
Properly check the error and return it.
None
- closes #9436
> fix(token exchange): properly return an error if membership is missing

- internal/api/oidc/auth_request.go
- internal/api/oidc/token_code.go
- internal/api/oidc/token_device.go
- internal/command/device_auth.go
- internal/command/device_auth_test.go
- internal/command/oidc_session.go
- internal/command/oidc_session_test.go
- internal/repository/session/session.go
When using a custom / new login UI and an OIDC application with registered BackChannelLogoutUI, no logout requests were sent to the URI when the user signed out.
Additionally, as described in #9427, an error was logged:
`level=error msg="event of type *session.TerminateEvent doesn't implement OriginEvent" caller="/home/runner/work/zitadel/zitadel/internal/notification/handlers/origin.go:24"`
- Properly pass `TriggerOrigin` information to session.TerminateEvent creation and implement `OriginEvent` interface.
- Implemented `RegisterLogout` in `CreateOIDCSessionFromAuthRequest` and `CreateOIDCSessionFromDeviceAuth`, both used when interacting with the OIDC v2 API.
- Both functions now receive the `BackChannelLogoutURI` of the client from the OIDC layer.
None
- closes #9427
> fix(OIDC): back channel logout work for custom UI

- internal/query/saml_request.go
- internal/query/saml_request_test.go
Without the login client header, there is no possible way to query the SAML requests.
Add a permission check to the query of SAML requests, equal to the AuthRequest query.
None
Related to https://github.com/zitadel/typescript/issues/66
> fix: add permission check for saml request query

- docs/docs/self-hosting/manage/reverseproxy/_proxy_guide_overview.mdx
- docs/docs/self-hosting/manage/reverseproxy/_proxy_guide_tls_mode.mdx
- docs/docs/self-hosting/manage/reverseproxy/caddy/caddy.mdx
- docs/docs/self-hosting/manage/reverseproxy/httpd/httpd.mdx
- docs/docs/self-hosting/manage/reverseproxy/nginx/nginx.mdx
- docs/docs/self-hosting/manage/reverseproxy/traefik/traefik.mdx
The reverse proxy docs have too many links to the third party proxy provider. This is noisy and might result in unintentional redirects.
The link to the proxy provider is only shown on the first occurence of the provider name instead of all occurences.
> docs: show proxy link only once

- README.md
- The current contrib.rocks link (`https://contrib.rocks`) does not directly preview the contributor graph for the zitadel/zitadel repository.
- Updated the contrib.rocks link to `https://contrib.rocks/preview?repo=zitadel/zitadel`, which directly shows the contributor graph for this repository.
> chore: Update contrib.rocks link in README.md

- internal/api/ui/login/renderer.go
Scripts and other assets for the hosted login UI are served with a public cache with `max-age` and `s-maxage`. After changing scripts or assets, old versions might be still used as they might be cached locally or in a shared cache (CDN, proxy, ...). This can lead to unwanted behaviour or even errors.
To ensure the correct file is served a query parameter with the build time is added to the assets filename dynamically. (`?v=2025-03-17...`)
None
- relates to #9485
- requires backport to at least 2.70.x
> fix(login): cache scripts and other assets correctly

- internal/api/grpc/admin/import.go
- internal/command/project_application_saml_test.go
- internal/id/sonyflake.go
- internal/notification/templates/template.go
- internal/query/message_text.go
- internal/renderer/renderer.go
- The `io/ioutil` package was deprecated in Go 1.16.  
- Reference: https://go.dev/doc/go1.16#ioutil  
- Replaced deprecated functions with their recommended alternatives:  
- `ioutil.ReadFile` → `os.ReadFile`  
- `ioutil.ReadAll` → `io.ReadAll`  
- `ioutil.NopCloser` → `io.NopCloser`
> chore: Replace deprecated `io/ioutil` functions with recommended alternatives

- build/workflow.Dockerfile
- deploy/knative/cockroachdb-statefulset-single-node.yaml
- e2e/config/localhost/docker-compose.yaml
E2E tests in pipelines started to fail randomly. While debugging it, i noticed that we use the `latest` tag of cockroach's docker image. They tagged 25.1 as latest yesterday.
Since we drop support for CRDB with version 3 as there are anyway multiple issues with various versions, I pinned the docker image tag to `latest-v24.3`.
None
relates to https://github.com/zitadel/zitadel/actions/runs/13917603587 and https://github.com/zitadel/zitadel/actions/runs/13904928050
> chore: use crdb 24.3

- internal/api/authz/authorization.go
- internal/api/authz/context.go
Remove the need of maintaining a channel for System user permission mapping, while still ensuring the mapping is built only once per request.
Build the slice of `SystemUserPermissionsDBQuery` once, when the context is being created in the context middleware. This slice will remain valid during the request lifetime as part of the context. This removes the need of "caching" and additional synchronization.
```sh
gci write . --skip-generated -s standard -s default -s 'prefix(github.com/zitadel/zitadel)' --custom-order
```
- Follow up on discussion https://github.com/zitadel/zitadel/pull/9460#discussion_r2006769497
> fix(authz): simplify system permission mapping

- internal/repository/permission/permission.go
When we recently changed some permission for the `SYSTEM_OWNER` role on QA, we noticed that there we multiple `permission.added` even when we removed specific permissions.
Fixed the event type when removing permissions.
None
Noticed when rolling out some changes on QA
> fix: correct event type for permission removed

- .github/pull_request_template.md
Sometimes our guidelines are missed by contributors. The same risk exists for the licensing terms under which contributions are submitted.
- Add comment with link to the relevant contribution guideline section
- Add comment with link to LICENSING.md
The comments are added as HTML comment which will be visible to the contributor, but won't be rendered in PR once submitted.
- none
- https://github.com/zitadel/zitadel/pull/9597#pullrequestreview-2716301670
> chore: add guidelines and licensing comment to PR template

- .github/dependabot.yml
Dependabot creates a PR for each individual dependency update. This is noisy and toil.
The easily mergable updates are grouped into fewer PRs.
Major updates and security updates are not grouped, as they might need special attention.
For the github-actions updates, also the major updates are grouped, as we have immediate and good enough feedback from the pipeline if a new major doesn't work.
The e2e dependencies are also auto-updated.
- We aggreed on grouping the dependabot PRs in todays Scrum daily.
- I don't know how to test the config. We might just have to merge it and look how it goes :man_shrugging:
> chore(deps): group easily mergable dependabot PRs

- cmd/mirror/config.go
With the change of #9561, the `mirror` command panics as there's no metrics provider configured.
Correctly initialize the provider (no-op by default) for the mirror command.
None
relates to #9561 -> needs backports to 2.66.x - 2.71.x and 3.0.0-rc
> fix(mirror): initialize meter to prevent panic

- docs/src/css/custom.css
- docs/src/theme/DocCardList/index.js
- docs/src/theme/DocSidebarItems/index.js
- docs/src/utils/deprecated-items.js
The docs overview pages and navs don't visually distinguish between deprecated and GA APIs.
This makes it hard to find the right methods for the job already.
As we are implementing the resource API and continously deprecate obsolete APIs, this only gets worse.
The UI items in docs overview pages are striked through and pushed to the bottom of the list.
This applies to side navs as well as card lists.
For example, [see management user methods](https://docs-git-strikethrough-deprecated-apis-zitadel.vercel.app/docs/apis/resources/mgmt/users):
A method is considered deprecated if it has this option set in the protos rpc definition:
```protobuf
option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
deprecated: true;
}
```
None
- Relates to #9680
> docs: strikethrough deprecated APIs

- console/src/app/modules/info-row/info-row.component.ts
- console/src/app/pages/users/user-list/user-table/user-table.component.ts
This pull request fixes a couple of minor issues with the user list and details pages in Console.
1. The total count in the users list was the total number of results
returned. This made the pagination not work when there were more than
`pageSize * 2` users.
2. The user details page did not show the created timestamp when viewing a
user.
1. The response includes the total number calculated by the backend. Use
that instead.
2. Inverse the ternary returning the creation date.
None
None
> fix(console): correct count for users list, show create timestamp in user details

- .github/workflows/container.yml
- .github/workflows/e2e.yml
While creating a new release, the [pipeline failed](https://github.com/zitadel/zitadel/actions/runs/14509737111/job/40705906723) as GH sunset the old actions cache service:
https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts
The `driver-opts` parameter is removed from the buildx actions to use the latest stable image. ([new cache service is used by BuildKit >= v0.20.0](https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api))
Updated docker/build-push-action to v6 in a first attempt to solve the issue, but kept it as it gave some more insights (incl. build summary)
Since the containers are only built on workflow triggers, here's the corresponding pipeline run: …
> chore(ci): fix container build

- API_DESIGN.md
Updating API_Design.md to include guidelines to specify all created resources created from an API call
This makes things clearer to the user if everything requested was actually created and helps with testing.
See  https://github.com/zitadel/zitadel/pull/9352
- Related https://github.com/zitadel/zitadel/issues/6305
- Related https://github.com/zitadel/zitadel/pull/9352
> docs(API_DESIGN.md): adding guidlines around API returns when multiple resources created

- .github/workflows/version.yml
https://github.com/zitadel/zitadel/pull/9765 fixed an issue for with actions cache service. The PR updated the push action, which now also provides a build summary. The "release" step tries to download all artifacts, which now fails: https://github.com/zitadel/zitadel/actions/runs/14660464768/job/41145285454
Only download relevant artifacts, which are published as part of the release.
None
None
> chore: only download release relevant artifacts

- internal/query/execution.go
- internal/query/execution_targets.sql
- internal/query/execution_test.go
- internal/query/projection/execution.go
- internal/query/projection/execution_test.go
In Actions v2, if a target is removed, which is still used in an execution, the target is still listed when list executions.
Removed targets are now also removed from the executions.
To be sure the list executions include a check if the target is still existing.
None
> fix: correct handling of removed targets

- cmd/setup/54.go
- cmd/setup/54.sql
Some projection queries took a long time to run. It seems that 1 or more queries couldn't make proper use of the `es_projection` index. This might be because of a specific complexity aggregate_type and event_type arguments, making the index unfeasible for postgres.
Following the index recommendation, add and index that covers just instance_id and position.
- none
- Related to https://github.com/zitadel/zitadel/issues/9832
> perf(eventstore): add instance position index

- cmd/defaults.yaml
- cmd/setup/38.go
- cmd/setup/55.go
- cmd/setup/55.sql
- cmd/setup/config.go
- cmd/setup/setup.go
- cmd/start/start.go
The execution handler projection handles all events to check if an execution has to be provided to the worker to execute.
In this logic all events would be processed from the beginning which is not necessary.
Add the current state to the execution handler projection, to avoid processing all existing events.
Add custom configuration to the default, so that the transactions are limited to some events.
None
> fix: add current state for execution handler into setup

- internal/query/user_by_login_name.sql
- internal/query/user_notify_by_login_name.sql
In rare cases there was a possibility that multiple users were found by a loginname. This prevented the corresponding user to sign in.
Fixed the corresponding query (to correctly respect the org domain policy).
None
Found during the investigation of a support request
> fix: correctly use single matching user (by loginname)

- cmd/mirror/projections.go
- internal/eventstore/handler/v2/field_handler.go
- internal/eventstore/handler/v2/handler.go
- internal/notification/projections.go
During the mirror command execution we saw high wait times for notification projections. 
As the events are skipped anyways because the notifications are sent out by the source Zitadel we skip the projections and just set the current state.
> fix(mirror): skip notification projections

- docs/docs/support/advisory/a10016.md
- docs/docs/support/technical_advisory.mdx
We are deploying precision fixes on the `position` values of the eventstore. The fix itself might break systems that were already affected by the bug.
Add a technical advisory that explains background and steps to fix the Zitadel database when affected.
- Original issue: [8671](https://github.com/zitadel/zitadel/issues/8671)
- Follow-up issue: [8863](https://github.com/zitadel/zitadel/issues/8863)
- Re-fix: https://github.com/zitadel/zitadel/pull/9881
> docs(advisory): position precision fix

- docs/docs/guides/manage/customize/notification-providers.mdx
Copy Paste typo in the description of the email notification provider, states sms are sent instead of email.
Replaces SMS with Email
> docs: fix typo in email notification provider description

- cmd/mirror/event_store.go
- cmd/mirror/projections.go
- internal/v2/readmodel/last_successful_mirror.go
1. After second execution, mirror starts to fail because of Primary key constraints on the events table. Because mirror always took the the first `system.mirror.succeeded` instead of the newest one
2. Mirror panicked during migration of fields tables
1. Adjusted the database query to order descending and limit 1
2. added missing assignment
- detailed logging if the copy from statement failed.
> fix(mirror): ensure multiple runs

- internal/api/grpc/org/v2/integration_test/query_test.go
List organization integration test fails sometimes due to incorrect sorting of results.
Add sorting column to request on list organizations endpoint and sort expected results.
None
None
> test: fix list orgs test with sort

- internal/admin/repository/eventsourcing/handler/handler.go
- internal/auth/repository/eventsourcing/handler/handler.go
- internal/database/database.go
- internal/eventstore/handler/v2/field_handler.go
- internal/eventstore/handler/v2/handler.go
- internal/eventstore/handler/v2/statement.go
- internal/query/projection/projection.go
1. The projection handler reported no error if an error happened but updating the current state was successful. This can lead to skipped projections during setup as soon as the projection has an error but does not correctly report if to the caller.
2. Mirror projections skipped as soon as an error occures, this leads to unprojected projections.
3. Mirror checked position wrongly in some cases
1. the error returned by the `Trigger` method will will only be set to the error of updating current states if there occured an error.
2. triggering projections checks for the error type returned and retries if the error had code `23505`
3. Corrected to use the `Equal` method
unify logging on mirror projections
> fix(handler): report error correctly

- internal/api/grpc/user/v2/integration_test/user_test.go
- internal/command/user_v2_invite.go
- internal/command/user_v2_invite_model.go
- internal/command/user_v2_invite_test.go
- proto/zitadel/user/v2/user.proto
- proto/zitadel/user/v2/user_service.proto
Users who started the invitation code verification, but haven't set up any authentication method, need to be able to do so. This might require a new invitation code, which was currently not possible since creation was prevented for users with verified emails.
- Allow creation of invitation emails for users with verified emails.
- Merged the creation and resend into a single method, defaulting the urlTemplate, applicatioName and authRequestID from the previous code (if one exists). On the user service API, the `ResendInviteCode` endpoint has been deprecated in favor of the `CreateInviteCode`
None
- Noticed while investigating something internally.
- requires backport to 2.x and 3.x
> fix: allow invite codes for users with verified mails

- internal/api/http/middleware/origin_interceptor.go
- internal/api/http/middleware/origin_interceptor_test.go
ZITADEL uses the notification triggering requests Forwarded or X-Forwarded-Proto header to build the button link sent in emails for confirming a password reset with the emailed code. If this header is overwritten and a user clicks the link to a malicious site in the email, the secret code can be retrieved and used to reset the users password and take over his account.
Accounts with MFA or Passwordless enabled can not be taken over by this attack.
- The `X-Forwarded-Proto` and `proto` of the Forwarded headers are validated (http / https).
- Additionally, when exposing ZITADEL through https. An overwrite to http is no longer possible.
None
None
> fix: validate proto header and provide https enforcement

- docs/docs/support/advisory/a10016.md
If the sql statement of technical advisory 10016 gets executed on cockroach the following error is raised:
```
ERROR: WITH clause "fixed" does not return any columns
SQLSTATE: 0A000
HINT: missing RETURNING clause?
```
Fixed the statement by adding `returning` to statement
> docs(10016): cockroach compatibility

- docs/sidebars.js
As we migrate resources to the new API, whenever a an implementation got merged, the API reference was added to the docs sidenav. As these new services and their implementation are not yet released, it can be confusing for developers as the corresponding endpoints return 404 or unimplemented errors.
Currently we just remove it from the sidenav and will add it once they're released. We're looking into a proper solution for the API references.
None
None
> docs(api): remove unreleased services from api reference

- internal/api/grpc/project/v2beta/integration/query_test.go
- internal/integration/client.go
IDs filter definition was changed in another PR and not changed in the Project service.
Correctly use the IDs filter.
Add timeout to the integration tests.
None
> fix: correct id filter for project service

- docs/package.json
- docs/yarn.lock
This pull request updates several dependencies in the `docs/package.json` file to their latest minor versions, ensuring compatibility and access to the latest features and fixes.
Dependency updates:
* Updated `@docusaurus/core`, `@docusaurus/faster`, `@docusaurus/preset-classic`, `@docusaurus/theme-mermaid`, and `@docusaurus/theme-search-algolia` from version `^3.8.0` to `^3.8.1` in the `dependencies` section.
* Updated `@docusaurus/module-type-aliases` and `@docusaurus/types` from version `^3.8.0` to `^3.8.1` in the `devDependencies` section.
> chore(docs): update docusaurus to 3.8.1

- Makefile
- login/.github/workflows/close_pr.yml
The close PR action currently fails because of unescaped backticks.
Backticks are escaped.
- Adding a login remote immediately fetches for better UX.
- Adding a subtree is not necessary, as it is already added in the repo.
- Fix and clarify PR migration steps.
- Add workflow dispatch event
> chore(typescript): improve close PR action

- docs/frameworks.json
- Broken or incorrect links on the "SDK Examples" introduction page. The links to the new client libraries section all reference the "java" section. This fixes it.
- Fixed the links to ensure they correctly point to the relevant sections in the documentation.
None.
None.
> docs: corrected the links for the client-libraries from the instroduction page

- .github/workflows/lint.yml
- .github/workflows/login-container.yml
The persistent depot runner lost connection to GitHub.
We mitigate by switching to GitHub ephemeral runners.
- Example of a failing run https://github.com/zitadel/zitadel/actions/runs/16505756293/job/46675827321
- Might be caused by https://github.com/zitadel/zitadel/actions/runs/16500656577/job/46658046270
> chore: use ephemeral GitHub runners

- internal/api/grpc/action/v2beta/integration_test/execution_target_test.go
- internal/api/oidc/introspect.go
- internal/api/oidc/token.go
- internal/api/oidc/token_exchange.go
- internal/api/oidc/userinfo.go
There is no information contained in the context info sent to Actions v2.
Add application information to the context information sent to Actions v2, to give more information about the execution.
None
Closes #9377
> feat: actions context information add clientID

- .devcontainer/base/docker-compose.yml
- .github/workflows/login-container.yml
Building the login container in the pipeline without build layer caches takes about 20 minutes.
We use cache-from and cache-to arguments to use the GitHub cache API.
Compare 1st and 2nd run [of this PRs pipeline](https://github.com/zitadel/zitadel/actions/runs/16590808510/job/46927893304)
- Follows up on #10343
> chore: use github for docker build layer caches

- docs/docs/apis/scim2.md
- docs/docs/guides/manage/user/scim2.md
- docs/sidebars.js
- proto/zitadel/org/v2beta/org_service.proto
The documentation API regarding organization v2 beta is not up to date.
The documentation regarding SCIM v2 is not up to date.
- Deprecate the existing v2beta endpoints `CreateOrganization` and `ListOrganizations` in favour of the v2 counterparst
- Remove the preview warning from SCIM v2 pages
- Closes #10311 and #10310
> docs: deprecate organization v2beta endpoints + remove scim preview notice

- .golangci.yaml
Not all NPM packages are excluded from go linting.
Missing exclusions are added.
Follows-up on #10331
> chore: exclude npm packages from go linting

- internal/eventstore/handler/v2/handler.go
- internal/query/projection/config.go
- internal/query/projection/projection.go
The current handling of event subscriptions for actions is bad, esp. on instances with a lot of events (https://github.com/zitadel/zitadel/issues/9832#issuecomment-2866236414). This led to severe problems on zitadel.cloud for such instances.
As a workaround until the handling can be improved, we introduce an option for projections to be disabled completely for specific instances: `SkipInstanceIDs`
None
- relates to https://github.com/zitadel/zitadel/issues/9832
> fix: allow disabling projections for specific instances

- load-test/src/app.ts
- load-test/src/login_ui.ts
- load-test/src/membership.ts
- load-test/src/oidc.ts
- load-test/src/org.ts
- load-test/src/project.ts
- load-test/src/session.ts
- load-test/src/user.ts
Adjust status checks across various functions to accept any 2xx HTTP response instead of only 200, improving the robustness of the API response validation.
fixes #10436
> fix(load-tests): accept any 2xx status as success

- internal/api/oidc/userinfo.go
- internal/api/saml/storage.go
- internal/api/ui/login/external_provider_handler.go
- internal/api/ui/login/metadata.go
- internal/api/ui/login/mfa_verify_handler.go
- internal/api/ui/login/mfa_verify_otp_handler.go
- internal/api/ui/login/mfa_verify_u2f_handler.go
- internal/api/ui/login/password_handler.go
- internal/api/ui/login/passwordless_login_handler.go
- internal/auth/repository/eventsourcing/eventstore/auth_request.go
User information in the context is necessary through the addition of the resource based API endpoints for user metadata, for the permission check.
Add user information to the action execution to add metadata to users.
None
Needs to be added to v4 releases, to provide the functionality to add metadata through actions v1 and actions v2 functions.
> fix: add user info to context for set metadata in actions

- internal/actions/object/metadata.go
- internal/api/ui/login/custom_action.go
disables trigger of org metadata projection in actions v1 when using `api.v1.getOrgMetadata()`
> fix(actionsV1): disable org metadata projection triggers

- apps/login/pnpm-lock.yaml
this updates the lockfile to represent the latest package version for latest
> chore: update lockfile to reflect 1.3.1 for packages

- internal/api/grpc/project/v2beta/integration_test/project_test.go
- internal/command/permission_checks.go
- internal/command/project.go
- internal/domain/permission.go
- internal/integration/client.go
When a user with an `ORG_PROJECT_CREATOR` role tries to create a project, the request fails with `No matching permissions found (AUTH-AWfge)` error. This is because `project.write` was set as the required permission instead of `project.create` during project creation.
By setting the right required permission (`project.create`) while creating new projects. 
N/A
- Closes #10399
> fix: create project with the right permission

- .github/workflows/container.yml
Docker image build on arm64 was timing out on multiple occasions.
Increase the Debug job timeout from 3 to 5 minutes.
- none
- https://github.com/zitadel/zitadel/actions/runs/17091081442/job/48465066443
- https://github.com/zitadel/zitadel/actions/runs/17071852582/job/48466980148
- https://github.com/zitadel/zitadel/actions/runs/17071852582/job/48403039843
> chore(ci): increase build-debug timeout

- console/src/app/modules/providers/provider-saml-sp/provider-saml-sp.component.html
- console/src/app/modules/providers/provider-saml-sp/provider-saml-sp.component.ts
- console/src/app/utils/enum.utils.ts
This PR fixes a problem for the SAML provider in console where the binding selection was not correctly applied when editing existing providers
- SAML provider binding selection was not correctly applied when editing existing providers
- Form used untyped reactive forms leading to potential runtime errors
- Hardcoded enum handling made the code fragile to API changes
- Created reusable utility functions (enum.utils.ts) that properly convert between numeric enum values (from backend) and string keys (for form controls)
- Improved type safety: Migrated from UntypedFormGroup/UntypedFormControl to strongly typed FormGroup<SAMLProviderForm> with FormControl<T>
> fix(console): Improve SAML SP form typing

- apps/login/constants/csp.js
Fix CSP img-src to allow ZITADEL instance assets
Login app was failing to load images (logos, branding assets) from ZITADEL instances due to Content Security Policy restrictions. The CSP img-src directive only allowed 'self' and https://vercel.com, blocking images from ZITADEL domains like https://login-*.zitadel.app.
- Dynamic CSP configuration: Extract hostname from ZITADEL_API_URL environment variable
- Fallback support: Use *.zitadel.cloud wildcard when no specific URL is configured
- Environment-aware: Works across dev/staging/prod without hardcoded domains
> fix(login): CSP img-src to allow instance assets

- apps/login/integration/integration/invite.cy.ts
- apps/login/integration/support/e2e.ts
- apps/login/next.config.mjs
Integration tests were failing with Minified React error 419 caused by React 19 Suspense boundary issues during server-side rendering (SSR) to client-side rendering (CSR) transitions.
The fix handles infrastructure-level SSR errors gracefully while maintaining proper error detection for actual application issues.
- Added Cypress error handling for React 19 SSR hydration errors that don't affect functionality
Enhanced Next.js configuration with React 19 compatibility optimizations:
- `optimizePackageImports`: @radix-ui/react-tooltip and @heroicons/react can have large bundle sizes if not optimized. Such packages are suggested to be optimized in https://nextjs.org/docs/app/api-reference/config/next-config-js/optimizePackageImports
- `poweredByHeader`: Not that important. Benefits are …
> fix(login): integration tests failing due to React 19 SSR errors

- internal/query/instance.go
We noticed a rapid growth of Redis memory usage. Instance By host did not set the zitadel version, so instance entries got set on every request again.
Set the version
- none
- internal incident
> fix(cache): set version in instance by host

- Makefile
[This PR](https://github.com/zitadel/zitadel/commit/61cab8878ee18ed32f44a63fd4633223f47f9e88) introduced wrong parameters to the integration tests of the backend. This PR reverts these changes
> fix(makefile): revert wrong integration test settings

- cmd/setup/40/02_func.sql
- cmd/setup/64.go
- cmd/setup/64.sql
- cmd/setup/config.go
- cmd/setup/setup.go
A timing issue (a race condition) was identified in our event processing system. Under specific circumstances, it was possible for the system to skip processing certain events, leading to potential data inconsistencies.
The system tracks its progress through the event log using timestamps. The issue occurred because we were using the timestamp from the start of a database transaction. If a query to read new events began after the transaction started but before the new event was committed, the query would not see the new event and would fail to process it.
The fix is to change which timestamp is used for tracking. We now use the precise timestamp of when the event is actually written to the database. This ensures that the event's timestamp is always correctly ordered, closing the timing …
> fix(projection): Prevent race condition with event push

- internal/query/user.go
- internal/query/user_test.go
#10415 added the possibility to filter users based on metadata. To prevent duplicate results an sql `DISTINCT` was added. This resulted in issues if the list was sorted on string columns like `username` or `displayname`, since they are sorted using `lower`. Using `DISTINCT` requires the `order by` column to be part of the `SELECT` statement.
Added the order by column to the statement.
None
- relates to #10415 
- backport to v4.x
> fix(api): sorting on list users endpoints

- internal/api/grpc/authorization/v2beta/integration_test/query_test.go
- internal/api/grpc/internal_permission/v2beta/administrator.go
- internal/api/grpc/internal_permission/v2beta/integration_test/administrator_test.go
- internal/api/grpc/internal_permission/v2beta/integration_test/query_test.go
- internal/api/grpc/management/project_grant.go
- internal/api/grpc/management/project_grant_converter.go
- internal/api/grpc/oidc/v2/integration_test/oidc_test.go
- internal/api/grpc/oidc/v2beta/integration_test/oidc_test.go
- internal/api/grpc/project/v2beta/project_grant.go
- internal/api/grpc/saml/v2/integration_test/saml_test.go
- internal/command/permission_checks.go
- internal/command/project_grant.go
- internal/command/project_grant_member.go
- internal/command/project_grant_member_test.go
- internal/command/project_grant_model.go
- internal/command/project_grant_test.go
- internal/command/user_grant_model.go
- internal/integration/client.go
- proto/zitadel/internal_permission/v2beta/internal_permission_service.proto
Project Grant ID would have needed to be unique to be handled properly on the projections, but was defined as the organization ID the project was granted to, so could be non-unique.
Generate the Project Grant ID even in the v2 APIs, which also includes fixes in the integration tests.
Additionally to that, the logic for some functionality had to be extended as the Project Grant ID is not provided anymore in the API, so had to be queried before creating events for Project Grants.
Included fix for authorizations, when an authorization was intended to be created for a project, without providing any organization information, which also showed some faulty integration tests.
Partially closes #10745
> fix: generated project grant id

- internal/api/grpc/session/v2/integration_test/query_test.go
- internal/api/grpc/session/v2/integration_test/session_test.go
While reviewing #9954, i noticed eventual consistency issues in the session integration tests. All creation and change dates as well as checked_at were tested using a `window` duration, typically one minute from `time.Now()`.  If some precondition took longer, they would all fail.
Changed the tests to use the information returned by the creation / set session calls and make sure they're in those timeframes.
Added a clock skew for the factor checks, since there's an inconsistency in the event payload and event date: #10791
None
- noted in #9954
- requires backport to v4.x
> test: make session integration tests less eventually consistent

- console/src/app/modules/providers/provider-saml-sp/provider-saml-sp.component.ts
- internal/api/ui/login/external_provider_handler.go
https://github.com/zitadel/zitadel/pull/10520 added the possibility to specify the signature algorithm for SAML auth requests. After releasing, customer noticed that the Console UI would not correctly display the selected algorithm and that it was not used in the login V1.
- Correctly map the algorithm in the UI
- Provide the option to the idp when creating a SAML request in login V1
None
- closes https://github.com/zitadel/zitadel/issues/10780
- closes https://github.com/zitadel/zitadel/issues/10792
- requires backport to v4.x
> fix(idp): SAML signature algorithm

- apps/login/src/lib/server/loginname.test.ts
- apps/login/src/lib/server/loginname.ts
Closes #10671
Users with only password authentication method were immediately shown an error "Username Password not allowed" when `loginSettings.allowUsernamePassword` was set to false. However, the IDP flow could potentially allow the user to register a new account or link an existing account, providing a better user experience than a dead-end error.
- Modified single password method case to attempt IDP redirect before showing error
- This allows users to potentially register or link accounts through the IDP flow instead of hitting an immediate error
- Only show error as last resort when no IDP alternative is available
> fix(login): Redirect to IDP flow when password auth is disabled

- internal/api/grpc/session/v2/session.go
- internal/api/grpc/session/v2beta/session.go
- internal/command/session.go
- internal/command/session_test.go
- proto/zitadel/action/v2/action_service.proto
- proto/zitadel/action/v2/execution.proto
- proto/zitadel/action/v2/query.proto
- proto/zitadel/action/v2/target.proto
- proto/zitadel/action/v2beta/action_service.proto
- proto/zitadel/oidc/v2/authorization.proto
- proto/zitadel/oidc/v2/oidc_service.proto
- proto/zitadel/oidc/v2beta/oidc_service.proto
- proto/zitadel/saml/v2/authorization.proto
- proto/zitadel/saml/v2/saml_service.proto
- proto/zitadel/session/v2/challenge.proto
- proto/zitadel/session/v2/session.proto
- proto/zitadel/session/v2/session_service.proto
- proto/zitadel/session/v2beta/session_service.proto
- proto/zitadel/user/v2beta/user_service.proto
- proto/zitadel/webkey/v2/key.proto
- proto/zitadel/webkey/v2/webkey_service.proto
- proto/zitadel/webkey/v2beta/webkey_service.proto
As part of our efforts to simplify the structure and versions of our APIs, were moving all existing v2beta endpoints to v2 and deprecate them. They will be removed in Zitadel V5.
- This PR deprecates all v2beta service and their endpoints, which have already a corresponding v2 version and should not be used anymore.
- The comments and have been improved and, where not already done, moved from swagger annotations to proto.
- All required fields have been marked with `(google.api.field_behavior) = REQUIRED` and validation rules have been added where missing.
- Removed the "required flag" comments on the Action and WebKey service endpoints, since they were removed in Zitadel v4.
- The `SetSession` endpoint already documented that the token does not have to be provided anymore and will be …
> fix(api): deprecate v2beta endpoints of existing v2 services

- docs/docusaurus.config.js
- docs/src/theme/ApiItem/index.jsx
This changes the source of a script to an internal url to prevent CSP errors.
Our documentation feedback script was not loaded due to being blocked by the CSP
By internally routing to a proxy, we do not have to add external urls to the CSP
> fix(docs): use internal script
